rem @echo off
rem Messages in some different contexts.
 set myt=\tests\
 set mys=
ECHO More msgs > t.t
 call progmsg 702 b
 call progmsg 1001 b
 call progmsg 1001 c
 call progmsg 1002 b
 call progmsg 1003 b
 call progmsg 1501 b
 call progmsg 1502 b
 call progmsg 1801 b
 call progmsg 1802 b
 call progmsg 1802 e
 call progmsg 1802 f
 call progmsg 1903 b
 call progmsg 1907 b
 call progmsg 2001 d
 call progmsg 2001 e
 call progmsg 2001 f
 call progmsg 2002 b
 call progmsg 2101 b
 call progmsg 2101 c
 call progmsg 2101 d
 call progmsg 2101 e
 call progmsg 2101 f
 call progmsg 2506 b
 call progmsg 3501 b
 call progmsg 3501 d
 call progmsg 3501 c
 call progmsg 3501 e
 call progmsg 3501 f
 call progmsg 3501 g
 call progmsg 3501 h
 call progmsg 3501 i
 call progmsg 3501 j
 call progmsg 3600 b
 call progmsg 3701 b
 call progmsg 3801 b
 call progmsg 3801 c
 call progmsg 3801 d
 call progmsg 3801 e
 call progmsg 3801 f
 call progmsg 3802 c
 call progmsg 3802 d
 call progmsg 4601 b
 call progmsg 5302 b
