$DoKeys:
 db $UNTIL-KeysBase,5,"UNTIL"
 db $WHILE-KeysBase,5,"WHILE"
Keys86:;1
Keys char $BY-KeysBase,2,"BY"
Keys171:;5
 db $FOR-KeysBase,3,"FOR"
Keys230:;10
Keys233:;10
 db $TO-KeysBase,18,"TO"
Keys215:;14
Keys214:;14
Keys137:;14
Keys54:;14
Keys0:;14
Keys286:;14
Keys31:;14
 db $ADDRESS-KeysBase,167,"ADDRESS",$ARG-KeysBase,3,"ARG"
 db $CALL-KeysBase,228,"CALL",$DO-KeysBase,66,"DO"
 db $DROP-KeysBase,4,"DROP",$ELSE-KeysBase,132,"ELSE"
 db $END-KeysBase,99,"END",$EXIT-KeysBase,4,"EXIT"
 db $IF-KeysBase,34,"IF",$INTERPRET-KeysBase,9,"INTERPRET"
 db $ITERATE-KeysBase,103,"ITERATE",$LEAVE-KeysBase,101,"LEAVE"
 db $NOP-KeysBase,3,"NOP",$NUMERIC-KeysBase,7,"NUMERIC"
 db $OPTIONS-KeysBase,7,"OPTIONS",$TRACE-KeysBase,197,"TRACE"
 db $PARSE-KeysBase,5,"PARSE",$PROCEDURE-KeysBase,9,"PROCEDURE"
 db $PULL-KeysBase,4,"PULL",$PUSH-KeysBase,4,"PUSH"
 db $QUEUE-KeysBase,5,"QUEUE",$RETURN-KeysBase,6,"RETURN"
 db $SAY-KeysBase,3,"SAY",$SELECT-KeysBase,6,"SELECT"
 db $SIGNAL-KeysBase,198,"SIGNAL",$THEN-KeysBase,132,"THEN"
Keys188:;194
Keys244:;194
 db $OTHERWISE-KeysBase,137,"OTHERWISE"
Keys112:;205
 db $WHEN-KeysBase,52,"WHEN"
Keys19:;211
 db $UPPER-KeysBase,5,"UPPER"
Keys111:;218
 db $ARG-KeysBase,3,"ARG",$LINEIN-KeysBase,6,"LINEIN"
 db $PULL-KeysBase,4,"PULL",$SOURCE-KeysBase,6,"SOURCE"
 db $VERSION-KeysBase,7,"VERSION",$VAR-KeysBase,3,"VAR"
Keys5:;259
Keys25:;259
 db $VALUE-KeysBase,21,"VALUE"
Keys114:;266
Keys113:;266
 db $LOSTDIGITS-KeysBase,10,"LOSTDIGITS",$SYNTAX-KeysBase,6,"SYNTAX"
 db $NOVALUE-KeysBase,7,"NOVALUE"
Keys78:;295
Keys81:;295
 db $NOTREADY-KeysBase,8,"NOTREADY",$FAILURE-KeysBase,7,"FAILURE"
 db $HALT-KeysBase,4,"HALT"
Keys276:;320
Keys278:;320
 db $ERROR-KeysBase,21,"ERROR"
Keys220:;327
Keys218:;327
 db $APPEND-KeysBase,6,"APPEND",$REPLACE-KeysBase,7,"REPLACE"
Keys219:;344
 db $NORMAL-KeysBase,6,"NORMAL"
Keys262:;352
Keys265:;352
 db $STEM-KeysBase,4,"STEM",$STREAM-KeysBase,22,"STREAM"
Keys8:;366
 db $FOREVER-KeysBase,7,"FOREVER"
Keys88:;375
Keys89:;375
$CondKeys:
 db $UNTIL-KeysBase,5,"UNTIL",$WHILE-KeysBase,21,"WHILE"
Keys17:;389
 db $DIGITS-KeysBase,6,"DIGITS",$FORM-KeysBase,196,"FORM"
 db $FUZZ-KeysBase,20,"FUZZ"
Keys23:;409
 db $VALUE-KeysBase,5,"VALUE"
Keys7:;416
 db $OFF-KeysBase,3,"OFF",$ON-KeysBase,18,"ON"
Keys163:;425
Keys161:;425
 db $ERROR-KeysBase,5,"ERROR"
Keys222:;432
 db $INPUT-KeysBase,5,"INPUT"
Keys273:;439
Keys275:;439
 db $OUTPUT-KeysBase,22,"OUTPUT"
Keys57:;447
 db $EXPOSE-KeysBase,22,"EXPOSE"
Keys184:;455
Keys162:;455
Keys110:;455
Keys74:;455
Keys73:;455
$WithKey:
 db $WITH-KeysBase,116,"WITH"
Keys192:;461
Keys165:;461
 db $NAME-KeysBase,244,"NAME"
Keys208:;467
Keys187:;467
Keys156:;467
Keys51:;467
 db $END-KeysBase,115,"END"
Keys49:;472
 db $ELSE-KeysBase,148,"ELSE"
Keys248:;478
Keys189:;478
Keys148:;478
Keys48:;478
$ThenKey:
 db $THEN-KeysBase,148,"THEN"
Keys224:;484
 db $ERROR-KeysBase,5,"ERROR"
Keys274:;491
Keys277:;491
 db $INPUT-KeysBase,21,"INPUT"
Keys223:;498
 db $ERROR-KeysBase,5,"ERROR",$OUTPUT-KeysBase,22,"OUTPUT"
Keys174:;513
 db $BY-KeysBase,2,"BY"
Keys231:;517
Keys235:;517
 db $FOR-KeysBase,19,"FOR"
Keys173:;522
 db $TO-KeysBase,2,"TO"
Keys234:;526
Keys236:;526
 db $BY-KeysBase,18,"BY"
Keys102:;530
 db $ENGINEERING-KeysBase,11,"ENGINEERING"
 db $SCIENTIFIC-KeysBase,10,"SCIENTIFIC",$VALUE-KeysBase,21,"VALUE",0,16
