/* To use the tests of builtins. */
  say "Look for Bifs OK"
/* Part 1
  call abbrev.cmd
  call abs.cmd
/*
  call address.cmd
*/
  call arg.cmd
  call bitand.cmd
  call bitor.cmd
  call bitxor.cmd
  call b2x.cmd
  call center.cmd
  call changestr.cmd
  call countstr.cmd
/*
  call charin.cmd
  call charout.cmd
  call chars.cmd
  call condition.cmd
*/
  call compare.cmd
  call copies.cmd
  call c2d.cmd
  call c2x.cmd
  call datatype.cmd
  call date.cmd
  call delstr.cmd
  call delword.cmd
  call digits.cmd
  call d2c.cmd
  call d2x.cmd
  call errortex.cmd
  call form.cmd
  call format.cmd
  call fuzz.cmd
  call insert.cmd
  call lastpos.cmd
  call left.cmd
  call length.cmd
/*
  call linein.cmd
  call lineout.cmd
  call lines.cmd
*/
  call max.cmd
  call min.cmd
  call overlay.cmd
  call pos.cmd
/*
  call qualify.cmd
  call queued.cmd
*/
  call random.cmd
  call reverse.cmd
  call right.cmd
  call sign.cmd
/*
  call sourceli.cmd
  call stream.cmd
*/
  call space.cmd
  call strip.cmd
  call substr.cmd
  call subword.cmd
/*
  call symbol.cmd
  call trace.cmd
  call trunc.cmd
*/
  call translat.cmd
  call value.cmd
  call verify.cmd
Part 1 */
  call word.cmd
  call wordinde.cmd
  call wordleng.cmd
  call wordpos.cmd
  call words.cmd
  call xrange.cmd
  call x2b.cmd
  call x2c.cmd
/*
  call x2d.cmd
*/
 say "Bifs OK"
