 erase t.t
 crx abbrev.cmd          >> t.t
 crx abs.cmd             >> t.t
rem nyi crx address.cmd         >> t.t
 crx arg.cmd             >> t.t
 crx bitand.cmd          >> t.t
 crx bitor.cmd           >> t.t
 crx bitxor.cmd          >> t.t
 crx b2x.cmd             >> t.t
 crx center.cmd          >> t.t
 crx changest.cmd        >> t.t
rem nyi crx charin.cmd          >> t.t
rem nyi crx charout.cmd         >> t.t
rem nyi crx chars.cmd           >> t.t
 crx compare.cmd         >> t.t
rem nyi crx conditio.cmd        >> t.t
 crx copies.cmd          >> t.t
 crx countstr.cmd        >> t.t
 crx c2d.cmd             >> t.t
 crx c2x.cmd             >> t.t
 crx datatype.cmd        >> t.t
 crx date.cmd            >> t.t
 crx delstr.cmd          >> t.t
 crx delword.cmd         >> t.t
 crx digits.cmd          >> t.t
 crx d2c.cmd             >> t.t
 crx d2x.cmd             >> t.t
 crx errortext.cmd       >> t.t
 crx form.cmd            >> t.t
 crx format.cmd          >> t.t
 crx fuzz.cmd            >> t.t
 crx insert.cmd          >> t.t
 crx lastpos.cmd         >> t.t
 crx left.cmd            >> t.t
 crx length.cmd          >> t.t
rem nyi crx linein.cmd          >> t.t
rem nyi crx lineout.cmd         >> t.t
rem nyi crx lines.cmd           >> t.t
 crx max.cmd             >> t.t
 crx min.cmd             >> t.t
 crx overlay.cmd         >> t.t
 crx pos.cmd             >> t.t
 crx qualify.cmd         >> t.t
rem nyi crx queued.cmd          >> t.t
 crx random.cmd          >> t.t
 crx reverse.cmd         >> t.t
 crx right.cmd           >> t.t
 crx sign.cmd            >> t.t
 crx sourceli.cmd        >> t.t
 crx space.cmd           >> t.t
rem nyi crx stream.cmd          >> t.t
 crx strip.cmd           >> t.t
 crx substr.cmd          >> t.t
 crx subword.cmd         >> t.t
 crx symbol.cmd          >> t.t
 crx time.cmd            >> t.t
 crx trace.cmd           >> t.t
 crx translat.cmd        >> t.t
 crx trunc.cmd           >> t.t
 crx value.cmd           >> t.t
 crx verify.cmd          >> t.t
 crx word.cmd            >> t.t
 crx wordinde.cmd        >> t.t
 crx wordleng.cmd        >> t.t
 crx wordpos.cmd         >> t.t
 crx words.cmd           >> t.t
 crx xrange.cmd          >> t.t
 crx x2b.cmd             >> t.t
 crx x2c.cmd             >> t.t
 crx x2d.cmd             >> t.t
