0 14 * 108 
1 1c 16 .MN
2 24 21 .RS
3 2c 26 .RESULT
4 34 35 .RC
5 3c 40 .SIGL
6 44 :24 47 1
7 4c :24 52 2
8 54 :24 57 3
9 5c :24 62 4
10 64 :24 67 5
11 6c :24 72 6
12 74 :24 77 7
13 7c :24 82 8
14 84 :24 87 9
15 8c :24 92 A
16 94 :24 97 B
17 9c 102 9
18 a4 105 0
19 ac 108 
20 b4 110 ENGINEERING
21 bc 123 SCIENTIFIC
22 c4 * 160 0
23 cc :32c2 163 BOTTOM
24 d4 :18 173 CHECKARGS
25 dc :ffda 196 ARG
26 e4 203 1
27 ec * 206 1
28 f4 :fffc 235 LENGTH
29 fc :fff7 245 SUBSTR
30 104 255 r
31 10c 260  
32 114 :58f 289 RAISE
33 11c 298 40.3
34 124 304 40.4
35 12c :d8 326 CHECKTYPE
36 134 339 40.5
37 13c 356 ANY
38 144 361 NUM
39 14c :350 366 CDATATYPE
40 154 379 N
41 15c 398 E
42 164 401 40.9
43 16c 407 40.11
44 174 414 WHOLE
45 17c :36d 421 EDATATYPE
46 184 434 W
47 18c 437 40.12
48 194 444 WHOLE>=0
49 19c 454 40.13
50 1a4 461 WHOLE>0
51 1ac 470 40.14
52 1b4 477 WHOLENUM
53 1bc 487 WHOLENUM>=0
54 1c4 500 0_90
55 1cc 518 90
56 1d4 * 522 90
57 1dc 526 .9
58 1e4 * 530 .9
59 1ec :fff5 534 POS
60 1f4 541 40.16
61 1fc 548 PAD
62 204 553 40.23
63 20c 560 HEX
64 214 :3200 565 DATATYPE
65 21c 577 X
66 224 580 40.25
67 22c 587 BIN
68 234 592 B
69 23c 595 40.24
70 244 602 SYM
71 24c 607 S
72 254 610 40.26
73 25c 617 ACEFILNOR
74 264 :ffc2 632 STRIP
75 26c 641 Left
76 274 647 ?
77 27c 650 L
78 284 :ffc9 653 TRANSLATE
79 28c :fff6 666 LEFT
80 294 674 40.28
81 29c 681 40.21
82 2a4 711 2
83 2ac * 714 2
84 2b4 :386 738 RERADIX
85 2bc 775 3
86 2c4 * 778 3
87 2cc 789 0123456789ABCDEF
88 2d4 807 ReRadix unable
89 2dc 825 16
90 2e4 * 829 16
91 2ec :ffd3 833 RIGHT
92 2f4 842 4
93 2fc * 845 4
94 304 :44f 848 TIME2DATE
95 30c 861 40.18
96 314 868 315537897600000000
97 31c :474 888 TIME2DATE2
98 324 902 18
99 32c 918 1000000
100 334 * 927 1000000
101 33c 955 60
102 344 * 959 60
103 34c 972 24
104 354 * 976 24
105 35c 994 366
106 364 * 999 366
107 36c 1004 365
108 374 * 1009 365
109 37c 1014 100
110 384 * 1019 100
111 38c 1024 400
112 394 * 1029 400
113 39c :569 1034 LEAP
114 3a4 1056 31 28 31 30 31 30 31 31 30 31 30 31
115 3ac :ffc5 1099 WORDS
116 3b4 :fff2 1118 WORD
117 3bc 1126 Raise at
118 3c4 :3df2 1136 !RAISE
119 3cc 1146 SYNTAX
120 3d4 :5aa 1154 _ABBREV
121 3dc 1165 rANY rANY oWHOLE>=0
122 3e4 :603 1216 _CENTRE
123 3ec :603 1227 _CENTER
124 3f4 1238 rANY rWHOLE>=0 oPAD
125 3fc :ffd6 1275 OVERLAY
126 404 :fff1 1286 COPIES
127 40c :662 1296 _CHANGESTR
128 414 1310 rANY rANY rANY
129 41c :6c3 1351 _COMPARE
130 424 1363 rANY rANY oPAD
131 42c :758 1402 _COPIES
132 434 1413 rANY rWHOLE>=0
133 43c :77a 1429 _COUNTSTR
134 444 1442 rANY rANY
135 44c :7c3 1453 _DATATYPE
136 454 1466 rANY oABLMNSUWX
137 45c :a78 1483 DTYPEONE
138 464 1499 abcdefghijklmnopqrstuvwxyz
139 46c 1531 ABCDEFGHIJKLMNOPQRSTUVWXYZ
140 474 1563 0123456789
141 47c 1575 A
142 484 :ffc3 1578 VERIFY
143 48c 1588 01
144 494 1607 M
145 49c :fff9 1610 SYMBOL
146 4a4 1620 BAD
147 4ac 1625 U
148 4b4 1628 CHAR
149 4bc :a60 1634 PLUS0
150 4c4 1654 Ee
151 4cc 1658 +-
152 4d4 1662 .
153 4dc 1695 abcdefABCDEF
154 4e4 1722 +
155 4ec 1725 -
156 4f4 :c3b 1728 DIGITRUN
157 4fc 1749 e
158 504 :c71 1790 _DELSTR
159 50c 1801 rANY rWHOLE>0 oWHOLE>=0
160 514 :cd4 1834 _DELWORD
161 51c :fff3 1854 WORDINDEX
162 524 :d41 1878 _INSERT
163 52c 1889 rANY rANY oWHOLE>=0 oWHOLE>=0 oPAD
164 534 1936 5
165 53c :dbd 1939 _LASTPOS
166 544 1951 rANY rANY oWHOLE>0
167 54c :e29 2006 _LEFT
168 554 :e5a 2015 _LENGTH
169 55c 2026 rANY
170 564 :2fcc 2043 CONFIG_LENGTH
171 56c :2fa4 2069 CONFIG_SUBSTR
172 574 :2f97 2086 CONFIG_C2B
173 57c 2100 23.1
174 584 :ffe6 2106 B2X
175 58c :e93 2113 _OVERLAY
176 594 2125 rANY rANY oWHOLE>0 oWHOLE>=0 oPAD
177 59c :f12 2160 _POS
178 5a4 :f73 2168 _REVERSE
179 5ac :fa2 2180 _RIGHT
180 5b4 :ff3 2190 _SPACE
181 5bc 2200 rANY oWHOLE>=0 oPAD
182 5c4 :fff4 2229 SUBWORD
183 5cc :1065 2240 _STRIP
184 5d4 2250 rANY oLTB oPAD
185 5dc 2282 T
186 5e4 :110e 2285 _SUBSTR
187 5ec 2296 rANY rWHOLE>0 oWHOLE>=0 oPAD
188 5f4 :11ae 2336 _SUBWORD
189 5fc :1247 2352 _TRANSLATE
190 604 2366 rANY oANY oANY oPAD
191 60c :2f7f 2387 CONFIG_UPPER
192 614 :31cd 2403 CONFIG_XRANGE
193 61c :132f 2436 _VERIFY
194 624 2447 rANY rANY oMN oWHOLE>0
195 62c :13d7 2486 _WORD
196 634 2495 rANY rWHOLE>0
197 63c :13ed 2510 _WORDINDEX
198 644 :144e 2530 _WORDLENGTH
199 64c :1465 2545 _WORDPOS
200 654 :ffc8 2564 SPACE
201 65c :14d7 2608 _WORDS
202 664 :14fd 2618 _XRANGE
203 66c 2629 oPAD oPAD
204 674 :1539 2640 _ABS
205 67c 2648 rNUM
206 684 :155b 2661 _FORMAT
207 68c 2672 rNUM oWHOLE>=0 oWHOLE>=0 oWHOLE>=0 oWHOLE>=0
208 694 2761 6
209 69c * 2764 6
210 6a4 * 2782 5
211 6ac 2785 40.38
212 6b4 2823 E+
213 6bc 2827 E-
214 6c4 :199a 2831 _MAX
215 6cc 2839  rNUM
216 6d4 :19f0 2855 _MIN
217 6dc :1a46 2867 _SIGN
218 6e4 :1a84 2876 _TRUNC
219 6ec 2886 rNUM oWHOLE>=0
220 6f4 2902 10
221 6fc * 2906 10
222 704 2910 0.
223 70c :ffd5 2914 INSERT
224 714 :1ae4 2924 _ADDRESS
225 71c 2967 ACTIVE.
226 724 2992 P
227 72c :1b85 3025 _ARG
228 734 3041 oWHOLE>0 oENO
229 73c 3056 rWHOLE>0 rENO
230 744 3084 O
231 74c :1bec 3099 _CONDITION
232 754 3113 oCDEIS
233 75c 3121 C
234 764 3136 D
235 76c 3179 I
236 774 :1c37 3222 _DIGITS
237 77c :1c43 3233 _ERRORTEXT
238 784 3247 r0_90 oSN
239 78c :1c7e 3278 _FORM
240 794 :1c8a 3287 _FUZZ
241 79c :1c96 3303 _SOURCELINE
242 7a4 3318 oWHOLE>0
243 7ac 3341 40.34
244 7b4 :1cd2 3348 _TRACE
245 7bc 3358 oACEFILNOR
246 7c4 :1d61 3394 _B2X
247 7cc 3402 rBIN
248 7d4 :1d7c 3408 _BITAND
249 7dc :1d7c 3419 _BITOR
250 7e4 :1d7c 3429 _BITXOR
251 7ec 3440 rANY oANY oPAD
252 7f4 3478 BITAND
253 7fc 3486 BITOR
254 804 3493 BITXOR
255 80c :ffe8 3501 X2C
256 814 :1e7a 3508 _C2D
257 81c 3516 rANY oWHOLE>=0
258 824 :ffe0 3537 XRANGE
259 82c :ffe3 3547 ABS
260 834 3554 40.35
261 83c :1f35 3561 _C2X
262 844 :1f5d 3569 _D2C
263 84c 3577 rWHOLENUM>=0
264 854 3591 rWHOLENUM rWHOLE>=0
265 85c 3612 8
266 864 * 3615 8
267 86c :2f8a 3618 CONFIG_B2C
268 874 :201b 3632 _D2X
269 87c 3640 F
270 884 :20a2 3643 _X2B
271 88c 3651 rHEX
272 894 :20cc 3657 _X2C
273 89c :2116 3665 _X2D
274 8a4 3673 rHEX oWHOLE>=0
275 8ac :fffe 3689 MIN
276 8b4 :ffe7 3704 X2B
277 8bc :21b9 3711 _CHARIN
278 8c4 3722 oANY oWHOLE>0 oWHOLE>=0
279 8cc :3020 3762 CONFIG_POSITION
280 8d4 3781 CHARIN
281 8dc 3789 40.27
282 8e4 :2fdd 3796 CONFIG_CHARIN
283 8ec 3813 NULL
284 8f4 :30d8 3819 CONFIG_STREAMQUERY
285 8fc 3862 READY
286 904 3869 NOTREADY
287 90c :2284 3879 _CHAROUT
288 914 3891 oANY oANY oWHOLE>0
289 91c 3911 CHAROUT
290 924 :30b8 3940 CONFIG_CHAROUT
291 92c :2369 3958 _CHARS
292 934 3968 oANY oNIC
293 93c :30eb 3979 CONFIG_STREAMCOUNT
294 944 :23ac 4001 _LINEIN
295 94c 4020 LINEIN
296 954 4028 40.42
297 95c :2482 4053 _LINEOUT
298 964 4065 LINEOUT
299 96c :2567 4074 _LINES
300 974 4084 oANY oCNI
301 97c :25aa 4095 _QUALIFY
302 984 4107 oANY
303 98c :30cf 4113 CONFIG_QUALIFIED_NAME
304 994 :25d3 4138 _STREAM
305 99c 4149 rANY rCDS rANY
306 9a4 4165 rANY oCDS
307 9ac :3097 4186 CONFIG_STREAMCOMMAND
308 9b4 :309f 4210 CONFIG_STREAMSTATE
309 9bc :265e 4245 _DATE
310 9c4 4254 oBDEMNOSUW oANY oBDENOSU
311 9cc 4280 40.19
312 9d4 :3100 4310 CONFIG_TIME
313 9dc 4360 January February March April May June July
314 9e4 4404 August September October November December
315 9ec 4457 Monday Tuesday Wednesday Thursday Friday Saturday Sunday
316 9f4 :28e1 4515 DATEFORMAT
317 9fc 4544 NS
318 a04 4556 12
319 a0c * 4560 12
320 a14 4564 EOU
321 a1c 4569 /
322 a24 4575 BD
323 a2c 4587 50
324 a34 * 4591 50
325 a3c 4595 0 31 59 90 120 151 181 212 243 273 304 334
326 a44 4645 86400
327 a4c * 4652 86400
328 a54 4664 7
329 a5c * 4667 7
330 a64 :2a0f 4670 _QUEUED
331 a6c :2fd6 4681 CONFIG_QUEUED
332 a74 :2a1d 4698 _RANDOM
333 a7c 4709 oWHOLE>=0 oWHOLE>=0 oWHOLE>=0
334 a84 4756 100000
335 a8c * 4764 100000
336 a94 4772 40.31
337 a9c 4779 999
338 aa4 * 4784 999
339 aac 4789 40.32
340 ab4 4796 40.33
341 abc :31af 4803 CONFIG_RANDOM_SEED
342 ac4 :31be 4825 CONFIG_RANDOM_NEXT
343 acc :2abe 4847 _SYMBOL
344 ad4 :2abe 4858 _TIME
345 adc 4867 oCEHLMNORS oANY oCHLMNS
346 ae4 :2c5a 4892 TIMEFORMAT
347 aec 4906 ERO
348 af4 4911 40.29
349 afc 4946 :
350 b04 4952 pm
351 b0c 4956 H
352 b14 :ffc6 4959 TRUNC
353 b1c 4968 12:
354 b24 4973 am
355 b2c 4977 R
356 b34 4992 1E-6
357 b3c * 4998 1E-6
358 b44 5004 1E+6
359 b4c * 5010 1E+6
360 b54 5016 3600
361 b5c * 5022 3600
362 b64 :2e04 5028 _VALUE
363 b6c 5038 rANY oANY oANY
364 b74 5054 rSYM oANY oANY
365 b7c :30f2 5075 CONFIG_GET
366 b84 5099 40.36
367 b8c 5106 40.37
368 b94 :30f9 5113 CONFIG_SET
369 b9c :31fc 5129 VAR_VALUE
370 ba4 :31fc 5148 VAR_SET
371 bac :ffe5 5173 C2X
372 bb4 :fff8 5182 QUEUED
373 bbc :ffc1 5203 STREAM
374 bc4 :ffbd 5213 CHARIN
375 bcc 5223 
376 bd4 :ffbf 5244 LINEIN
377 bdc :ffbe 5254 CHAROUT
378 be4 :ffc0 5284 LINEOUT
379 bec 5314 Done
380 bf4 :30e0 5320 CONFIG_STREAMCLOSE
381 bfc :ffb9 5345 DATE
382 c04 :ffba 5353 TIME
383 c0c 5361 /:.
384 c14 5366 20
385 c1c 5370 19
386 c24 :313e 5374 DATE2TIME
387 c2c :ffe1 5387 RANDOM
388 c34 5403 
389 c3c 5406 ÿ
390 c44 5409 
Sorry, can't do things that require keeping history from call to call.
391 c4c 5481 This version is not conversational
392 c54 :3db4 5517 NOVALUE
393 c5c :339a 5528 GLOBAL_VARS
394 c64 5551 answer=_
395 c6c 5561 ()
396 c74 5565 SOURCELINE
397 c7c 5577 [
398 c84 5580 ]
399 c8c 5590 13
400 c94 * 5594 13
401 c9c 5626 999999
402 ca4 * 5634 999999
403 cac 5657 250
404 cb4 * 5662 250
405 cbc * 5702 9
406 cc4 5705 777
407 ccc * 5710 777
408 cd4 5715 99
409 cdc * 5719 99
410 ce4 5723 Whatever
411 cec :ffdc 5749 TRACE
412 cf4 :ffd9 5758 ADDRESS
413 cfc 5769 ECST
414 d04 5792 ECSP
415 d0c 5819 ECSN
416 d14 5842 ECDT
417 d1c 5870 ECDP
418 d24 5902 ECDN
419 d2c 5930 OFF
420 d34 6025 ERROR
421 d3c 6043 FAILURE
422 d44 6052 HALT
423 d4c 6064 NOVALUE
424 d54 6073 Error <value> running <source>, line <linenumber>:
425 d5c 6125 Error <value> in interactive trace:
426 d64 6162 Interactive trace.  "Trace Off" to end debug. 
427 d6c 6210 ENTER to continue.
428 d74 6230 Failure during finalization
429 d7c 6259 Failure during finalization: <description>
430 d84 6303 Failure during initialization
431 d8c 6334 Failure during initialization: <description>
432 d94 6380 Program interrupted
433 d9c 6401 Program interrupted with HALT condition
434 da4 6442 System resources exhausted
435 dac 6470 System resources exhausted: <description>
436 db4 6513 Unmatched "/*" or quote
437 dbc 6538 Unmatched comment delimiter ("/*")
438 dc4 6574 Unmatched single quote (')
439 dcc 6602 Unmatched double quote (")
440 dd4 6630 WHEN or OTHERWISE expected
441 ddc 6658 SELECT on line <linenumber> requires WHEN;
442 de4 6702 found "<token>"
443 dec 6719 SELECT on line <linenumber> requires WHEN, OTHERWISE,
444 df4 6774 or END; found "<token>"
445 dfc 6799 All WHEN expressions of SELECT on line <linenumber> are
446 e04 6856 false; OTHERWISE expected
447 e0c 6883 Unexpected THEN or ELSE
448 e14 6908 THEN has no corresponding IF or WHEN clause
449 e1c 6953 ELSE has no corresponding THEN clause
450 e24 6992 Unexpected WHEN or OTHERWISE
451 e2c 7022 WHEN has no corresponding SELECT
452 e34 7056 OTHERWISE has no corresponding SELECT
453 e3c 7095 Unexpected or unmatched END
454 e44 7124 END has no corresponding DO or SELECT
455 e4c 7163 END corresponding to DO on line <linenumber>
456 e54 7209 must have a symbol following that matches
457 e5c 7252 the control variable (or no symbol);
458 e64 7290 must not have a symbol following it because
459 e6c 7335 there is no control variable;
460 e74 7366 END corresponding to SELECT on line <linenumber>
461 e7c 7416 must not have a symbol following;
462 e84 7451 END must not immediately follow THEN
463 e8c 7489 END must not immediately follow ELSE
464 e94 7527 Invalid character in program
465 e9c 7557 Invalid character in program "<character>"
466 ea4 7601 ('<hex-encoding>'X)
467 eac 7622 Incomplete DO/SELECT/IF
468 eb4 7647 14
469 ebc 7651 DO instruction requires a matching END
470 ec4 7691 SELECT instruction requires a matching END
471 ecc 7735 THEN requires a following instruction
472 ed4 7774 ELSE requires a following instruction
473 edc 7813 Invalid hexadecimal or binary string
474 ee4 7851 15
475 eec 7855 Invalid location of blank in position
476 ef4 7894 <position> in hexadecimal string
477 efc 7928 <position> in binary string
478 f04 7957 Only 0-9, a-f, A-F, and blank are valid in a
479 f0c 8003 hexadecimal string; found "<char>"
480 f14 8039 Only 0, 1, and blank are valid in a
481 f1c 8076 binary string; found "<char>"
482 f24 8107 Label not found
483 f2c 8124 Label "<name>" not found
484 f34 8150 Cannot SIGNAL to label "<name>" because it is
485 f3c 8197 inside an IF, SELECT or DO group
486 f44 8231 Cannot invoke label "<name>" because it is
487 f4c 8275 Unexpected PROCEDURE
488 f54 8297 17
489 f5c 8301 PROCEDURE is valid only when it is the first
490 f64 8347 instruction executed after an internal CALL
491 f6c 8392 or function invocation
492 f74 8416 THEN expected
493 f7c 8431 IF keyword on line <linenumber> requires
494 f84 8473 matching THEN clause; found "<token>"
495 f8c 8512 WHEN keyword on line <linenumber> requires
496 f94 8556 String or symbol expected
497 f9c 8583 String or symbol expected after ADDRESS keyword;
498 fa4 8633 String or symbol expected after CALL keyword;
499 fac 8680 String or symbol expected after NAME keyword;
500 fb4 8727 String or symbol expected after SIGNAL keyword;
501 fbc 8776 String or symbol expected after TRACE keyword;
502 fc4 8824 Symbol expected in parsing pattern;
503 fcc 8861 Name expected
504 fd4 8876 Name required; found "<token>"
505 fdc 8908 Found "<token>" where only a name is valid
506 fe4 8952 Invalid data on end of clause
507 fec 8983 21
508 ff4 8987 The clause ended at an unexpected token;
509 ffc 9029 Invalid character string
510 1004 9055 22
511 100c 9059 Invalid character string '<hex-encoding>'X
512 1014 9103 Invalid data string
513 101c 9124 23
514 1024 9128 Invalid data string '<hex-encoding>'X
515 102c 9167 Invalid TRACE request
516 1034 9190 TRACE request must be one character of
517 103c 9230 "ACEFILNOR"; found "<value>"
518 1044 9260 Invalid sub-keyword found
519 104c 9287 25
520 1054 9291 CALL ON must be followed by one of the
521 105c 9331 keywords <keywords>; found "<token>"
522 1064 9369 CALL OFF must be followed by one of the
523 106c 9410 SIGNAL ON must be followed by one of the
524 1074 9452 SIGNAL OFF must be followed by one of the
525 107c 9495 ADDRESS WITH must be followed by one of the
526 1084 9540 INPUT must be followed by one of the
527 108c 9578 OUTPUT must be followed by one of the
528 1094 9617 APPEND must be followed by one of the
529 109c 9656 REPLACE must be followed by one of the
530 10a4 9696 NUMERIC FORM must be followed by one of the
531 10ac 9741 11
532 10b4 9745 PARSE must be followed by one of the
533 10bc 9783 UPPER must be followed by one of the
534 10c4 9821 ERROR must be followed by one of the
535 10cc 9859 NUMERIC must be followed by one of the
536 10d4 9899 FOREVER must be followed by one of the
537 10dc 9939 keywords <keywords> or nothing; found "<token>"
538 10e4 9988 PROCEDURE must be followed by the keyword
539 10ec 10031 EXPOSE or nothing; found "<token>"
540 10f4 10067 Invalid whole number
541 10fc 10089 26
542 1104 10093 Whole numbers must fit within current DIGITS
543 110c 10139 setting(<value>); found "<value>"
544 1114 10174 Value of repetition count expression in DO instruction
545 111c 10230 must be zero or a positive whole number;
546 1124 10272 found "<value>"
547 112c 10289 Value of FOR expression in DO instruction
548 1134 10332 Positional pattern of parsing template
549 113c 10372 must be a whole number; found "<value>"
550 1144 10413 NUMERIC DIGITS value
551 114c 10435 must be a positive whole number; found "<value>"
552 1154 10485 NUMERIC FUZZ value
553 115c 10505 Number used in TRACE setting
554 1164 10535 Operand to right of the power operator ("**")
555 116c 10582 Result of <value> % <value> operation would need
556 1174 10632 exponential notation at current NUMERIC DIGITS <value>
557 117c 10688 Result of % operation used for <value> // <value>
558 1184 10739 operation would need
559 118c 10761 Invalid DO syntax
560 1194 10780 27
561 119c 10784 Invalid use of keyword <token> in DO clause
562 11a4 10829 Invalid LEAVE or ITERATE
563 11ac 10855 28
564 11b4 10859 LEAVE is valid only within a repetitive DO loop
565 11bc 10908 ITERATE is valid only within a repetitive DO loop
566 11c4 10959 Symbol following LEAVE ("<token>") must
567 11cc 11000 either match control variable of a current
568 11d4 11044 DO loop or be omitted
569 11dc 11067 Symbol following ITERATE ("<token>") must
570 11e4 11110 Environment name longer than
571 11ec 11140 characters
572 11f4 11152 29
573 11fc 11156 Environment name exceeds
574 1204 11182 characters "<name>"
575 120c 11203 Name or string too long
576 1214 11228 30
577 121c 11232 Name exceeds
578 1224 11246 Literal string exceeds
579 122c 11270 Name starts with number or "."
580 1234 11302 31
581 123c 11306 A value cannot be assigned to a number;
582 1244 11347 Variable symbol must not start with a number;
583 124c 11394 Variable symbol must not start with a ".";
584 1254 11438 Invalid expression result
585 125c 11465 33
586 1264 11469 Value of NUMERIC DIGITS ("<value>")
587 126c 11506 must exceed value of NUMERIC FUZZ "(<value>)"
588 1274 11553 must not exceed
589 127c 11570 Result of expression following NUMERIC FORM
590 1284 11615 must start with "E" or "S"; found "<value>"
591 128c 11660 Logical value not "0" or "1"
592 1294 11690 34
593 129c 11694 Value of expression following IF keyword
594 12a4 11736 must be exactly "0" or "1"; found "<value>"
595 12ac 11781 Value of expression following WHEN keyword
596 12b4 11825 Value of expression following WHILE keyword
597 12bc 11870 Value of expression following UNTIL keyword
598 12c4 11915 Value of expression to left
599 12cc 11944 of logical operator "<operator>"
600 12d4 11978 Value of expression to right
601 12dc 12008 Invalid expression
602 12e4 12028 35
603 12ec 12032 Invalid expression detected at "<token>"
604 12f4 12074 Unmatched "(" in expression
605 12fc 12103 36
606 1304 12107 Unexpected "," or ")"
607 130c 12130 37
608 1314 12134 Unexpected ","
609 131c 12150 Unmatched ")" in expression
610 1324 12179 Invalid template or pattern
611 132c 12208 38
612 1334 12212 Invalid parsing template detected at "<token>"
613 133c 12260 Invalid parsing position detected at "<token>"
614 1344 12308 PARSE VALUE instruction requires WITH keyword
615 134c 12355 Incorrect call to routine
616 1354 12382 40
617 135c 12386 External routine <name> failed
618 1364 12418 Not enough arguments in invocation of <bif>;
619 136c 12464 minimum expected is <argnumber>
620 1374 12497 Too many arguments in invocation of <bif>;
621 137c 12541 maximum expected is <argnumber>
622 1384 12574 Missing argument in invocation of <bif>;
623 138c 12616 argument <argnumber> is required
624 1394 12650 <bif> argument <argnumber>
625 139c 12678 Exponent exceeds
626 13a4 12696 digits
627 13ac 12704 must be a number; found "<value>"
628 13b4 12739 must be zero or positive; found "<value>"
629 13bc 12782 must be positive; found "<value>"
630 13c4 12817 must fit in <value> digits; found "<value>"
631 13cc 12862 Requires a whole number fitting within
632 13d4 12902 DIGITS(<value>); found "<value>"
633 13dc 12936 <bif> argument 1
634 13e4 12954 must have an integer part in the range 0:90 and a
635 13ec 13005 decimal part no larger than .9; found "<value>"
636 13f4 13054 <bif> conversion must
637 13fc 13077 have a year in the range 0001 to 9999
638 1404 13116 <bif> argument 2, "<value>", is not in the format
639 140c 13167 described by argument 3, "<value>"
640 1414 13203 <bif> argument <argnumber> must not be null
641 141c 13248 must be a single character or null;
642 1424 13285 must be a single character; found "<value>"
643 142c 13330 must be a binary string; found "<value>"
644 1434 13372 must be a hexadecimal string; found "<value>"
645 143c 13419 must be a valid symbol; found "<value>"
646 1444 13460 must be a valid stream name; found "<value>"
647 144c 13506 must start with one of "<optionslist>";
648 1454 13547 <bif> conversion to format "<value>" is not allowed
649 145c 13600 <bif> argument 1 ("<value>") must not exceed 100000
650 1464 13653 <bif> the difference between argument 1 ("<value>") and
651 146c 13710 argument 2 ("<value>") must not exceed 100000
652 1474 13757 32
653 147c 13761 <bif> argument 1 ("<value>") must be less than
654 1484 13809 or equal to argument 2 ("<value>")
655 148c 13845 or equal to the number of lines
656 1494 13878 in the program (<sourceline()>)
657 149c 13911 <bif> argument 1 cannot be expressed as a whole number;
658 14a4 13968 must be the name of a variable in the pool;
659 14ac 14013 <bif> argument 3
660 14b4 14031 must be the name of a pool; found "<value>"
661 14bc 14076 is not large enough to format "<value>"
662 14c4 14117 must be within the bounds of the stream;
663 14cc 14159 41
664 14d4 14163 <bif> argument 3 is not zero or one; found "<value>"
665 14dc 14217 42
666 14e4 14221 Bad arithmetic conversion
667 14ec 14248 Non-numeric value ("<value>")
668 14f4 14279 to left of arithmetic operation "<operator>"
669 14fc 14325 to right of arithmetic operation "<operator>"
670 1504 14372 used with prefix operator "<operator>"
671 150c 14412 Value of TO expression in DO instruction
672 1514 14454 must be numeric; found "<value>"
673 151c 14488 Value of BY expression in DO instruction
674 1524 14530 Value of control variable expression of DO instruction
675 152c 14586 digits;
676 1534 14595 Arithmetic overflow/underflow
677 153c 14626 Arithmetic overflow detected at
678 1544 14659 "<value> <operation> <value>";
679 154c 14691 exponent of result requires more than
680 1554 14730 Arithmetic underflow detected at
681 155c 14764 Arithmetic overflow; divisor must not be zero
682 1564 14811 Routine not found
683 156c 14830 43
684 1574 14834 Could not find routine "<name>"
685 157c 14867 Function did not return data
686 1584 14897 44
687 158c 14901 No data returned from function "<name>"
688 1594 14942 No data specified on function RETURN
689 159c 14980 45
690 15a4 14984 Data expected on RETURN instruction because
691 15ac 15029 routine "<name>" was called as a function
692 15b4 15072 Invalid variable reference
693 15bc 15100 46
694 15c4 15104 Extra token ("<token>") found in variable
695 15cc 15147 reference; ")" expected
696 15d4 15172 Unexpected label
697 15dc 15190 47
698 15e4 15194 INTERPRET data must not contain labels;
699 15ec 15235 found "<name>"
700 15f4 15251 Failure in system service
701 15fc 15278 48
702 1604 15282 Failure in system service: <description>
703 160c 15324 Interpretation Error
704 1614 15346 49
705 161c 15350 Interpretation Error: <description>
706 1624 15387 Unrecognized reserved symbol
707 162c 15417 Unrecognized reserved symbol "<token>"
708 1634 15457 Invalid function name
709 163c 15480 51
710 1644 15484 Unquoted function names must not end with a period;
711 164c 15537 Result returned by <name> is longer than
712 1654 15579 52
713 165c 15583 Invalid option
714 1664 15599 53
715 166c 15603 String or symbol or variable reference expected
716 1674 15652 after STREAM keyword; found "<token>"
717 167c 15691 Symbol or variable reference expected
718 1684 15730 after STEM keyword; found "<token>"
719 168c 15767 Argument to STEM must have one period,
720 1694 15807 as its last character; found "<name>"
721 169c 15846 Invalid STEM value
722 16a4 15866 54
723 16ac 15870 For this STEM APPEND, the value of "<name>" must be a
724 16b4 15925 count of lines; found: "<value>"
725 16bc :3db4 15959 SYNTAX
726 16c4 15969 ?R
727 16cc :ffdb 15978 CONDITION
728 16d4 :ffdf 15996 SOURCELINE
729 16dc 16016 Line
730 16e4 16022 condition raised:
731 16ec :ffc7 16041 ERRORTEXT
732 16f4 16085 <
733 16fc 16095 >
734 1704 16098 $SYN$

10: AssignConst '0'<c4> !NOTJ18{38}; Signal "BOTTOM"<cc>; '1'<ec> 
1a:BifqARG1 @CHECKLIST{40} ""<ac> AssignStem ARGTYPE.{48}; AssignConst 
24:'0'<c4> ARGPOS{58}; AssignConst '0'<c4> MINARGS{60}; '1'<ec> 
2f:Number CHECKLIST{40} Length To ControlVar J{68}[87]; ARGPOS{58} 
3b:'1'<ec> Add @ARGPOS{58} CHECKLIST{40} J{68} '1'<ec> BifSUBSTR3 
48:"r"<104> Seq[54] MINARGS{60} '1'<ec> Add @MINARGS{60} RepEver[86]; 
57:J{68} CHECKLIST{40} Length Bool Lt While J{68} '1'<ec> Add 
64:@J{68} CHECKLIST{40} J{68} '1'<ec> BifSUBSTR3 @T{70} Unstore 
71:" "<10c> Seq[77] Leave; ARGPOS{58} Dots(0) ARGTYPE.{48} T{70} 
7f:Abut ARGPOS{58} AssignDots ARGTYPE.{48}; Iterate; IterCV; 
87:ARGPOS{58} @MAXARGS{78} "0"<a4> Dots(0) !BIF_ARG.{88} @NUMARGS{80} 
93:Unstore MINARGS{60} Lt[a0] "40.3"<11c> MINARGS{60} Call "RAISE"<114>; 
a0:NUMARGS{80} MAXARGS{78} Gt[ae] "40.4"<124> MAXARGS{78} Call 
ac:"RAISE"<114>; '1'<ec> Number NUMARGS{80} To ControlVar ARGPOS{58}[d7]; 
b9:ARGPOS{58} Dots(0) !BIF_ARGEXISTS.{98} Then[c8]; Call "CHECKTYPE"<12c>; 
c5:Jump[d6] ARGPOS{58} MINARGS{60} Le[d6] "40.5"<134> ARGPOS{58} 
d3:Call "RAISE"<114>; IterCV; Return; ARGPOS{58} Dots(0) !BIF_ARG.{88} 
de:@VALUE{a8} ARGPOS{58} Dots(0) ARGTYPE.{48} @TYPE{b0} Unstore 
e9:"ANY"<13c> Seq[f2] Nop; Jump[34f] TYPE{b0} "NUM"<144> Seq[12b] 
f9:VALUE{a8} "N"<154> Invoke(2) "CDATATYPE"<14c> Not Then[121]; 
105:!DATATYPERESULT{b8} "E"<15c> Seq[118] "40.9"<164> ARGPOS{58} 
110:VALUE{a8} Call "RAISE"<114>; Jump[121] "40.11"<16c> ARGPOS{58} 
11c:VALUE{a8} Call "RAISE"<114>; !DATATYPERESULT{b8} ARGPOS{58} 
125:AssignDots !BIF_ARG.{88}; Jump[34f] TYPE{b0} "WHOLE"<174> 
12f:Seq[151] VALUE{a8} "W"<184> Invoke(2) "EDATATYPE"<17c> Not 
13b:Then[147]; "40.12"<18c> ARGPOS{58} VALUE{a8} Call "RAISE"<114>; 
147:!DATATYPERESULT{b8} ARGPOS{58} AssignDots !BIF_ARG.{88}; 
14e:Jump[34f] TYPE{b0} "WHOLE>=0"<194> Seq[187] VALUE{a8} "W"<184> 
15c:Invoke(2) "EDATATYPE"<17c> Not Then[16d]; "40.12"<18c> ARGPOS{58} 
168:VALUE{a8} Call "RAISE"<114>; !DATATYPERESULT{b8} '0'<c4> 
171:Lt[17d] "40.13"<19c> ARGPOS{58} VALUE{a8} Call "RAISE"<114>; 
17d:!DATATYPERESULT{b8} ARGPOS{58} AssignDots !BIF_ARG.{88}; 
184:Jump[34f] TYPE{b0} "WHOLE>0"<1a4> Seq[1bd] VALUE{a8} "W"<184> 
192:Invoke(2) "EDATATYPE"<17c> Not Then[1a3]; "40.12"<18c> ARGPOS{58} 
19e:VALUE{a8} Call "RAISE"<114>; !DATATYPERESULT{b8} '0'<c4> 
1a7:Le[1b3] "40.14"<1ac> ARGPOS{58} VALUE{a8} Call "RAISE"<114>; 
1b3:!DATATYPERESULT{b8} ARGPOS{58} AssignDots !BIF_ARG.{88}; 
1ba:Jump[34f] TYPE{b0} "WHOLENUM"<1b4> Seq[1e3] VALUE{a8} "W"<184> 
1c8:Invoke(2) "CDATATYPE"<14c> Not Then[1d9]; "40.12"<18c> ARGPOS{58} 
1d4:VALUE{a8} Call "RAISE"<114>; !DATATYPERESULT{b8} ARGPOS{58} 
1dd:AssignDots !BIF_ARG.{88}; Jump[34f] TYPE{b0} "WHOLENUM>=0"<1bc> 
1e7:Seq[219] VALUE{a8} "W"<184> Invoke(2) "CDATATYPE"<14c> Not 
1f3:Then[1ff]; "40.12"<18c> ARGPOS{58} VALUE{a8} Call "RAISE"<114>; 
1ff:!DATATYPERESULT{b8} '0'<c4> Lt[20f] "40.13"<19c> ARGPOS{58} 
20a:VALUE{a8} Call "RAISE"<114>; !DATATYPERESULT{b8} ARGPOS{58} 
213:AssignDots !BIF_ARG.{88}; Jump[34f] TYPE{b0} "0_90"<1c4> 
21d:Seq[279] VALUE{a8} "N"<154> Invoke(2) "EDATATYPE"<17c> Not 
229:Then[235]; "40.11"<16c> ARGPOS{58} VALUE{a8} Call "RAISE"<114>; 
235:!DATATYPERESULT{b8} @VALUE{a8} Unstore ARGPOS{58} AssignDots 
23d:!BIF_ARG.{88}; VALUE{a8} '1'<ec> IntDivide @MAJOR{c0} VALUE{a8} 
248:MAJOR{c0} Subtract @MINOR{c8} MAJOR{c0} '0'<c4> Bool Lt MAJOR{c0} 
255:'90'<1d4> Bool Gt Or MINOR{c8} '.9'<1e4> Bool Gt Or "E"<15c> 
263:VALUE{a8} BifqPOS2 '0'<c4> Bool Gt Or Then[276]; "40.16"<1f4> 
271:VALUE{a8} Call "RAISE"<114>; Jump[34f] TYPE{b0} "PAD"<1fc> 
27d:Seq[294] VALUE{a8} Length '1'<ec> Ne[291] "40.23"<204> ARGPOS{58} 
28c:VALUE{a8} Call "RAISE"<114>; Jump[34f] TYPE{b0} "HEX"<20c> 
298:Seq[2b1] VALUE{a8} "X"<21c> Invoke(2) "DATATYPE"<214> Not 
2a4:Then[2ae]; "40.25"<224> VALUE{a8} Call "RAISE"<114>; Jump[34f] 
2b1:TYPE{b0} "BIN"<22c> Seq[2ce] VALUE{a8} "B"<234> Invoke(2) 
2be:"DATATYPE"<214> Not Then[2cb]; "40.24"<23c> VALUE{a8} Call 
2c9:"RAISE"<114>; Jump[34f] TYPE{b0} "SYM"<244> Ceq[2eb] VALUE{a8} 
2d7:"S"<24c> Invoke(2) "DATATYPE"<214> Not Then[2e8]; "40.26"<254> 
2e3:VALUE{a8} Call "RAISE"<114>; Jump[34f] TYPE{b0} "ACEFILNOR"<25c> 
2ef:Ceq[31a] VALUE{a8} "L"<27c> "?"<274> BifqSTRIP3 @VAL{d0} 
2fc:Unstore '1'<ec> BifqLEFT2 BifqTRANSLATE1 "ACEFILNOR"<25c> 
305:BifqPOS2 '0'<c4> Eq[317] "40.28"<294> ARGPOS{58} TYPE{b0} 
312:VALUE{a8} Call "RAISE"<114>; Jump[34f] VALUE{a8} ""<ac> Seq[328] 
321:"40.21"<29c> ARGPOS{58} Call "RAISE"<114>; VALUE{a8} '1'<ec> 
32c:BifqLEFT2 BifqTRANSLATE1 ARGPOS{58} AssignDots !BIF_ARG.{88}; 
335:ARGPOS{58} Dots(0) !BIF_ARG.{88} TYPE{b0} BifqPOS2 '0'<c4> 
341:Eq[34f] "40.28"<294> ARGPOS{58} TYPE{b0} VALUE{a8} Call "RAISE"<114>; 
34f:Return; !LEVEL{e8} Dots(0) !DIGITS.{d8} Numeric(0); !LEVEL{e8} 
35a:Dots(0) !FORM.{f0} Numeric(4); '1'<ec> BifqARG1 '2'<2ac> 
366:BifqARG1 Invoke(2) "DATATYPE"<214> Returns; !BIF{110} Dots(0) 
371:!CONFIG_DIGITS.{100} Numeric(0); "SCIENTIFIC"<bc> Numeric(4); 
379:'1'<ec> BifqARG1 '2'<2ac> BifqARG1 Invoke(2) "DATATYPE"<214> 
385:Returns; Raise(2) '1'<ec> BifqARG1 @SUBJECT{118} '2'<2ac> 
390:BifqARG1 @FROMRADIX{120} '3'<2c4> BifqARG1 @TORADIX{128} 
39a:AssignConst '0'<c4> INTEGER{130}; '1'<ec> Number SUBJECT{118} 
3a4:Length To ControlVar J{68}[3d4]; INTEGER{130} FROMRADIX{120} 
3af:Multiply SUBJECT{118} J{68} '1'<ec> BifSUBSTR3 "0123456789ABCDEF"<2cc> 
3ba:BifqPOS2 Add '1'<ec> Subtract @INTEGER{130} "E"<15c> INTEGER{130} 
3c6:BifqPOS2 '0'<c4> Gt[3d3] "ReRadix unable"<2d4> Say; "?"<274> 
3d2:Returns; IterCV; AssignConst ""<ac> R{138}; INTEGER{130} 
3db:'0'<c4> Eq[3e5] AssignConst '0'<c4> R{138}; RepEver[40a]; 
3e8:INTEGER{130} '0'<c4> Bool Gt While "0123456789ABCDEF"<2cc> 
3f1:'1'<ec> INTEGER{130} TORADIX{128} Remainder Add '1'<ec> BifSUBSTR3 
3fd:R{138} Abut @R{138} INTEGER{130} TORADIX{128} IntDivide @INTEGER{130} 
409:Iterate; FROMRADIX{120} '2'<2ac> Bool Eq TORADIX{128} '16'<2e4> 
414:Bool Eq And Then[42e]; R{138} SUBJECT{118} Length '3'<2c4> 
421:Add '4'<2fc> IntDivide "0"<a4> BifRIGHT3 @R{138} Jump[44c] 
42e:FROMRADIX{120} '16'<2e4> Bool Eq TORADIX{128} '2'<2ac> Bool 
439:Eq And Then[44c]; R{138} SUBJECT{118} Length '4'<2fc> Multiply 
446:"0"<a4> BifRIGHT3 @R{138} R{138} Returns; '1'<ec> BifqARG1 
453:'0'<c4> Lt[45d] "40.18"<30c> Call "RAISE"<114>; '1'<ec> BifqARG1 
461:"315537897600000000"<314> Ge[46b] "40.18"<30c> Call "RAISE"<114>; 
46b:'1'<ec> BifqARG1 Invoke(1) "TIME2DATE2"<31c> Returns; Raise(2) 
476:"18"<324> Numeric(0); '1'<ec> BifqARG1 @TIME{140} Unstore 
481:'1000000'<334> IntDivide @SECOND{148} TIME{140} '1000000'<334> 
48a:Remainder @MICROSECOND{150} SECOND{148} '60'<344> IntDivide 
492:@MINUTE{158} SECOND{148} '60'<344> Remainder @SECOND{148} 
49b:MINUTE{158} '60'<344> IntDivide @HOUR{160} MINUTE{158} '60'<344> 
4a6:Remainder @MINUTE{158} HOUR{160} '24'<354> IntDivide @DAY{168} 
4b0:HOUR{160} '24'<354> Remainder @HOUR{160} DAY{168} @BASEDAYS{170} 
4bb:DAY{168} '1'<ec> Add @DAY{168} Unstore '366'<364> IntDivide 
4c6:@YEAR{178} DAY{168} YEAR{178} '365'<374> Multiply YEAR{178} 
4d1:'4'<2fc> IntDivide Add YEAR{178} '100'<384> IntDivide Subtract 
4db:YEAR{178} '400'<394> IntDivide Add Subtract @DAY{168} YEAR{178} 
4e6:'1'<ec> Add @YEAR{178} RepEver[512]; DAY{168} '365'<374> 
4f2:YEAR{178} Invoke(1) "LEAP"<39c> Add Bool Gt While DAY{168} 
4fe:'365'<374> YEAR{178} Invoke(1) "LEAP"<39c> Add Subtract @DAY{168} 
50a:YEAR{178} '1'<ec> Add @YEAR{178} Iterate; DAY{168} @YEARDAYS{180} 
516:AssignConst "31 28 31 30 31 30 31 31 30 31 30 31"<3a4> DAYS{188}; 
51b:'1'<ec> Number DAYS{188} BifqWORDS1 To ControlVar MONTH{190}[54e]; 
528:DAYS{188} MONTH{190} BifWORD2 MONTH{190} '2'<2ac> Bool Eq 
534:YEAR{178} Invoke(1) "LEAP"<39c> Multiply Add @THISMONTH{198} 
53e:DAY{168} THISMONTH{198} Le[546] Leave; DAY{168} THISMONTH{198} 
54a:Subtract @DAY{168} IterCV; YEAR{178} MONTH{190} Cat DAY{168} 
555:Cat HOUR{160} Cat MINUTE{158} Cat SECOND{148} Cat MICROSECOND{150} 
561:Cat BASEDAYS{170} Cat YEARDAYS{180} Cat Returns; Raise(2) 
56b:'1'<ec> BifqARG1 '4'<2fc> Remainder '0'<c4> Bool Eq '1'<ec> 
578:BifqARG1 '100'<384> Remainder '0'<c4> Bool Ne '1'<ec> BifqARG1 
585:'400'<394> Remainder '0'<c4> Bool Eq Or And Returns; "Raise at"<3bc> 
591:Say; Exit; "SYNTAX"<3cc> '1'<ec> BifqARG1 !BIF{110} '2'<2ac> 
59d:BifqARG1 '3'<2c4> BifqARG1 '4'<2fc> BifqARG1 Call "!RAISE"<3c4>; 
5aa:"rANY rANY oWHOLE>=0"<3dc> Call "CHECKARGS"<d4>; "1"<e4> 
5b1:Dots(0) !BIF_ARG.{88} @SUBJECT{118} "2"<2a4> Dots(0) !BIF_ARG.{88} 
5bd:@SUBJ{1a0} "3"<2bc> Dots(0) !BIF_ARGEXISTS.{98} Then[5d3]; 
5c8:"3"<2bc> Dots(0) !BIF_ARG.{88} @LENGTH{1a8} Jump[5d8] SUBJ{1a0} 
5d5:Length @LENGTH{1a8} SUBJECT{118} Length SUBJ{1a0} Length 
5de:Bool Ge @COND1{1b0} SUBJ{1a0} Length LENGTH{1a8} Bool Ge 
5e9:@COND2{1b8} SUBJECT{118} '1'<ec> SUBJ{1a0} Length BifSUBSTR3 
5f4:SUBJ{1a0} Bool Seq @COND3{1c0} COND1{1b0} COND2{1b8} And 
5ff:COND3{1c0} And Returns; "rANY rWHOLE>=0 oPAD"<3f4> Call "CHECKARGS"<d4>; 
608:"1"<e4> Dots(0) !BIF_ARG.{88} @STRING{1c8} "2"<2a4> Dots(0) 
614:!BIF_ARG.{88} @LENGTH{1a8} "3"<2bc> Dots(0) !BIF_ARGEXISTS.{98} 
61e:Then[62c]; "3"<2bc> Dots(0) !BIF_ARG.{88} @PAD{1d0} Jump[631] 
62c:AssignConst " "<10c> PAD{1d0}; STRING{1c8} Length LENGTH{1a8} 
636:Subtract @TRIM{1d8} Unstore '0'<c4> Gt[64e] STRING{1c8} TRIM{1d8} 
643:'2'<2ac> IntDivide '1'<ec> Add LENGTH{1a8} BifSUBSTR3 Returns; 
64e:STRING{1c8} PAD{1d0} LENGTH{1a8} BifCOPIES2 TRIM{1d8} Negate 
659:'2'<2ac> IntDivide '1'<ec> Add BifOVERLAY3 Returns; "rANY rANY rANY"<414> 
664:Call "CHECKARGS"<d4>; AssignConst ""<ac> OUTPUT{1e0}; AssignConst 
66d:'1'<ec> POSITION{1e8}; RepEver[6b5]; "1"<e4> Dots(0) !BIF_ARG.{88} 
67a:"2"<2a4> Dots(0) !BIF_ARG.{88} POSITION{1e8} BifPOS3 @FOUNDPOS{1f0} 
686:Unstore '0'<c4> Eq[68d] Leave; OUTPUT{1e0} "2"<2a4> Dots(0) 
693:!BIF_ARG.{88} POSITION{1e8} FOUNDPOS{1f0} POSITION{1e8} Subtract 
69c:BifSUBSTR3 Abut "3"<2bc> Dots(0) !BIF_ARG.{88} Abut @OUTPUT{1e0} 
6a8:FOUNDPOS{1f0} "1"<e4> Dots(0) !BIF_ARG.{88} Length Add @POSITION{1e8} 
6b4:Iterate; OUTPUT{1e0} "2"<2a4> Dots(0) !BIF_ARG.{88} POSITION{1e8} 
6bf:BifSUBSTR2 Abut Returns; "rANY rANY oPAD"<424> Call "CHECKARGS"<d4>; 
6c8:"1"<e4> Dots(0) !BIF_ARG.{88} @STR1{1f8} "2"<2a4> Dots(0) 
6d4:!BIF_ARG.{88} @STR2{200} "3"<2bc> Dots(0) !BIF_ARGEXISTS.{98} 
6de:Then[6ec]; "3"<2bc> Dots(0) !BIF_ARG.{88} @PAD{1d0} Jump[6f1] 
6ec:AssignConst " "<10c> PAD{1d0}; STR1{1f8} Length STR2{200} 
6f6:Length Gt[70c] STR1{1f8} Length @LENGTH{1a8} STR2{200} LENGTH{1a8} 
703:PAD{1d0} BifLEFT3 @STR2{200} Jump[71b] STR2{200} Length @LENGTH{1a8} 
711:STR1{1f8} LENGTH{1a8} PAD{1d0} BifLEFT3 @STR1{1f8} STR1{1f8} 
71d:''<14> !ALLBLANKS{208} " "<10c> BifqTRANSLATE4 @STR1{1f8} 
727:STR2{200} ''<14> !ALLBLANKS{208} " "<10c> BifqTRANSLATE4 
731:@STR2{200} '1'<ec> Number LENGTH{1a8} To ControlVar I{210}[755]; 
73e:STR1{1f8} I{210} '1'<ec> BifSUBSTR3 STR2{200} I{210} '1'<ec> 
74c:BifSUBSTR3 Sne[754] I{210} Returns; IterCV; "0"<a4> Returns; 
758:"rANY rWHOLE>=0"<434> Call "CHECKARGS"<d4>; AssignConst ""<ac> 
760:OUTPUT{1e0}; "2"<2a4> Dots(0) !BIF_ARG.{88} Rep[777]; OUTPUT{1e0} 
76d:"1"<e4> Dots(0) !BIF_ARG.{88} Abut @OUTPUT{1e0} IterRep; 
777:OUTPUT{1e0} Returns; "rANY rANY"<444> Call "CHECKARGS"<d4>; 
77f:AssignConst '0'<c4> OUTPUT{1e0}; "1"<e4> Dots(0) !BIF_ARG.{88} 
78a:"2"<2a4> Dots(0) !BIF_ARG.{88} BifqPOS2 @POSITION{1e8} RepEver[7c0]; 
797:POSITION{1e8} '0'<c4> Bool Gt While OUTPUT{1e0} '1'<ec> Add 
7a3:@OUTPUT{1e0} "1"<e4> Dots(0) !BIF_ARG.{88} "2"<2a4> Dots(0) 
7af:!BIF_ARG.{88} POSITION{1e8} "1"<e4> Dots(0) !BIF_ARG.{88} 
7b9:Length Add BifPOS3 @POSITION{1e8} Iterate; OUTPUT{1e0} Returns; 
7c3:"rANY oABLMNSUWX"<454> Call "CHECKARGS"<d4>; "1"<e4> Dots(0) 
7cc:!BIF_ARG.{88} @STRING{1c8} "2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} 
7d6:Not Then[7df]; Invoke(0) "DTYPEONE"<45c> Returns; "2"<2a4> 
7e1:Dots(0) !BIF_ARG.{88} @TYPE{b0} STRING{1c8} ""<ac> Seq[80b] 
7ee:TYPE{b0} "X"<21c> Seq[7f8] "1"<e4> Returns; TYPE{b0} "B"<234> 
7fc:Bool Seq !NOTJ18{38} Not And Then[808]; "1"<e4> Returns; 
808:"0"<a4> Returns; AssignConst "abcdefghijklmnopqrstuvwxyz"<464> 
80e:AZL{218}; AssignConst "ABCDEFGHIJKLMNOPQRSTUVWXYZ"<46c> AZU{220}; 
815:AssignConst "0123456789"<474> D09{228}; TYPE{b0} "A"<47c> 
81e:Seq[832] STRING{1c8} AZL{218} AZU{220} Abut D09{228} Abut 
82b:BifqVERIFY2 '0'<c4> Bool Eq Returns; TYPE{b0} "B"<234> Seq[8bf] 
839:!NOTJ18{38} Then[849]; STRING{1c8} "01"<48c> BifqVERIFY2 
844:'0'<c4> Bool Eq Returns; STRING{1c8} '1'<ec> BifqLEFT2 !ALLBLANKS{208} 
851:BifqPOS2 '0'<c4> Gt[85b] "0"<a4> Returns; STRING{1c8} '1'<ec> 
85f:BifqRIGHT2 !ALLBLANKS{208} BifqPOS2 '0'<c4> Gt[86d] "0"<a4> 
86c:Returns; AssignConst '0'<c4> BINARYDIGITS{230}; STRING{1c8} 
874:Length Number '1'<ec> Negate By '1'<ec> To ControlVar J{68}[8bc]; 
882:STRING{1c8} J{68} '1'<ec> BifSUBSTR3 @C{238} Unstore !ALLBLANKS{208} 
88f:BifqPOS2 '0'<c4> Gt[8a6] BINARYDIGITS{230} '4'<2fc> Remainder 
89b:'0'<c4> Ne[8a3] "0"<a4> Returns; Jump[8bb] C{238} "01"<48c> 
8aa:BifqVERIFY2 '0'<c4> Ne[8b4] "0"<a4> Returns; BINARYDIGITS{230} 
8b6:'1'<ec> Add @BINARYDIGITS{230} IterCV; "1"<e4> Returns; TYPE{b0} 
8c1:"L"<27c> Seq[8d1] STRING{1c8} AZL{218} BifqVERIFY2 '0'<c4> 
8ce:Bool Eq Returns; TYPE{b0} "M"<494> Seq[8e6] STRING{1c8} AZL{218} 
8dc:AZU{220} Abut BifqVERIFY2 '0'<c4> Bool Eq Returns; TYPE{b0} 
8e8:"N"<154> Seq[8f8] STRING{1c8} Invoke(1) "DATATYPE"<214> "NUM"<144> 
8f5:Bool Seq Returns; TYPE{b0} "S"<24c> Seq[908] STRING{1c8} 
901:BifGroupDATE2 "BAD"<4a4> Bool Sne Returns; TYPE{b0} "U"<4ac> 
90c:Seq[91a] STRING{1c8} AZU{220} BifqVERIFY2 '0'<c4> Bool Eq 
919:Returns; TYPE{b0} "W"<184> Seq[9e7] STRING{1c8} Invoke(1) 
925:"DTYPEONE"<45c> "CHAR"<4b4> Seq[92f] "0"<a4> Returns; '1'<ec> 
931:Then[9a0]; STRING{1c8} Invoke(1) "PLUS0"<4bc> @STRING{1c8} 
93c:AssignConst '0'<c4> INFRACTION{240}; '1'<ec> Number STRING{1c8} 
946:Length To ControlVar J{68}[996]; STRING{1c8} J{68} '1'<ec> 
953:BifSUBSTR3 @C{238} Unstore "Ee"<4c4> BifqPOS2 '0'<c4> Gt[964] 
961:"0"<a4> Returns; INFRACTION{240} C{238} "+-"<4cc> BifqPOS2 
96c:'0'<c4> Bool Gt And Then[977]; "0"<a4> Returns; C{238} "."<4d4> 
97b:Seq[986] AssignConst '1'<ec> INFRACTION{240}; Jump[995] INFRACTION{240} 
988:C{238} "0"<a4> Bool Sne And Then[995]; "0"<a4> Returns; IterCV; 
996:!DATATYPERESULT{b8} '1'<ec> IntDivide @!DATATYPERESULT{b8} 
99d:"1"<e4> Returns; "E"<15c> !DATATYPERESULT{b8} BifqPOS2 '0'<c4> 
9a8:Gt[9ae] "0"<a4> Returns; BEFORE{248} AFTER{250} Abut @STRING{1c8} 
9b5:BEFORE{248} Length EXPWAS{258} Add @J{68} Unstore '0'<c4> 
9c0:Lt[9c8] AssignConst '0'<c4> J{68}; STRING{1c8} J{68} '1'<ec> 
9ce:Add BifSUBSTR2 "0"<a4> BifqVERIFY2 '0'<c4> Gt[9dd] "0"<a4> 
9dc:Returns; !DATATYPERESULT{b8} '1'<ec> IntDivide @!DATATYPERESULT{b8} 
9e4:"1"<e4> Returns; STRING{1c8} '1'<ec> BifqLEFT2 !ALLBLANKS{208} 
9ef:BifqPOS2 '0'<c4> Gt[9f9] "0"<a4> Returns; STRING{1c8} '1'<ec> 
9fd:BifqRIGHT2 !ALLBLANKS{208} BifqPOS2 '0'<c4> Gt[a0b] "0"<a4> 
a0a:Returns; AssignConst '0'<c4> HEXDIGITS{260}; STRING{1c8} 
a12:Length Number '1'<ec> Negate By '1'<ec> To ControlVar J{68}[a5d]; 
a20:STRING{1c8} J{68} '1'<ec> BifSUBSTR3 @C{238} Unstore !ALLBLANKS{208} 
a2d:BifqPOS2 '0'<c4> Gt[a44] HEXDIGITS{260} '2'<2ac> Remainder 
a39:'0'<c4> Ne[a41] "0"<a4> Returns; Jump[a5c] C{238} "abcdefABCDEF"<4dc> 
a48:D09{228} Abut BifqVERIFY2 '0'<c4> Ne[a55] "0"<a4> Returns; 
a55:HEXDIGITS{260} '1'<ec> Add @HEXDIGITS{260} IterCV; "1"<e4> 
a5f:Returns; !LEVEL{e8} Dots(0) !DIGITS.{d8} Numeric(0); !LEVEL{e8} 
a6a:Dots(0) !FORM.{f0} Numeric(4); '0'<c4> '1'<ec> BifqARG1 Add 
a77:Returns; AssignConst "S"<24c> !DATATYPERESULT{b8}; STRING{1c8} 
a7f:BifqSTRIP1 @RESIDUE{268} Unstore ""<ac> Seq[a8c] "CHAR"<4b4> 
a8b:Returns; AssignConst ""<ac> SIGN{270}; RESIDUE{268} '1'<ec> 
a95:BifqLEFT2 "+"<4e4> Bool Seq RESIDUE{268} '1'<ec> BifqLEFT2 
aa1:"-"<4ec> Bool Seq Or Then[abd]; RESIDUE{268} '1'<ec> BifqLEFT2 
aaf:@SIGN{270} RESIDUE{268} '2'<2ac> BifqSUBSTR2 "L"<27c> BifqSTRIP2 
abb:@RESIDUE{268} RESIDUE{268} ""<ac> Seq[ac7] "CHAR"<4b4> Returns; 
ac7:RESIDUE{268} '1'<ec> BifqLEFT2 "."<4d4> Seq[af1] RESIDUE{268} 
ad4:'2'<2ac> BifqSUBSTR2 @RESIDUE{268} AssignConst ""<ac> BEFORE{248}; 
adf:Invoke(0) "DIGITRUN"<4f4> @AFTER{250} Unstore ""<ac> Seq[aee] 
aeb:"CHAR"<4b4> Returns; Jump[b1e] AssignConst ""<ac> AFTER{250}; 
af6:Invoke(0) "DIGITRUN"<4f4> @BEFORE{248} Unstore ""<ac> Seq[b05] 
b02:"CHAR"<4b4> Returns; RESIDUE{268} '1'<ec> BifqLEFT2 "."<4d4> 
b0d:Seq[b1e] RESIDUE{268} '2'<2ac> BifqSUBSTR2 @RESIDUE{268} 
b18:Invoke(0) "DIGITRUN"<4f4> @AFTER{250} AssignConst '0'<c4> 
b21:EXPONENT{278}; RESIDUE{268} ""<ac> Sne[ba2] RESIDUE{268} 
b2c:'1'<ec> BifqLEFT2 "e"<4fc> Bool Sne RESIDUE{268} '1'<ec> 
b38:BifqLEFT2 "E"<15c> Bool Sne And Then[b45]; "CHAR"<4b4> Returns; 
b45:RESIDUE{268} '2'<2ac> BifqSUBSTR2 @RESIDUE{268} Unstore ""<ac> 
b50:Seq[b56] "CHAR"<4b4> Returns; AssignConst ""<ac> ESIGN{280}; 
b5b:RESIDUE{268} '1'<ec> BifqLEFT2 "+"<4e4> Bool Seq RESIDUE{268} 
b67:'1'<ec> BifqLEFT2 "-"<4ec> Bool Seq Or Then[b8c]; RESIDUE{268} 
b75:'1'<ec> BifqLEFT2 @ESIGN{280} RESIDUE{268} '2'<2ac> BifqSUBSTR2 
b81:@RESIDUE{268} Unstore ""<ac> Seq[b8c] "CHAR"<4b4> Returns; 
b8c:Invoke(0) "DIGITRUN"<4f4> @EXPONENT{278} Unstore ""<ac> Seq[b9b] 
b98:"CHAR"<4b4> Returns; ESIGN{280} EXPONENT{278} Abut @EXPONENT{278} 
ba2:RESIDUE{268} ""<ac> Sne[bac] "CHAR"<4b4> Returns; EXPONENT{278} 
bae:@EXPWAS{258} AssignConst "E"<15c> !DATATYPERESULT{b8}; BEFORE{248} 
bb7:"L"<27c> "0"<a4> BifqSTRIP3 @BEFORE{248} Unstore ""<ac> Seq[bca] 
bc5:AssignConst '0'<c4> BEFORE{248}; EXPONENT{278} BEFORE{248} 
bce:Length Add '1'<ec> Subtract @EXPONENT{278} AssignConst '1'<ec> 
bd8:G{288}; !LEVEL{e8} Dots(0) !FORM.{f0} "E"<15c> Seq[c00] EXPONENT{278} 
be7:'3'<2c4> Remainder @G{288} Unstore '0'<c4> Lt[bf9] G{288} 
bf4:'3'<2c4> Add @G{288} EXPONENT{278} G{288} Subtract @EXPONENT{278} 
c00:EXPONENT{278} Length @G{288} EXPONENT{278} '0'<c4> Lt[c13] 
c0c:G{288} '1'<ec> Subtract @G{288} G{288} !LIMIT_EXPONENTDIGITS{290} 
c17:Gt[c1d] "CHAR"<4b4> Returns; !LEVEL{e8} Dots(0) !DIGITS.{d8} 
c23:Numeric(0); !LEVEL{e8} Dots(0) !FORM.{f0} Numeric(4); '0'<c4> 
c2f:"1"<e4> Dots(0) !BIF_ARG.{88} Add @!DATATYPERESULT{b8} "NUM"<144> 
c3a:Returns; AssignConst ""<ac> OUTCOME{298}; RepEver[c6e]; RESIDUE{268} 
c45:""<ac> Bool Sne While RESIDUE{268} '1'<ec> BifqLEFT2 "0123456789"<474> 
c52:BifqPOS2 '0'<c4> Eq[c5a] Leave; OUTCOME{298} RESIDUE{268} 
c5e:'1'<ec> BifqLEFT2 Abut @OUTCOME{298} RESIDUE{268} '2'<2ac> 
c69:BifqSUBSTR2 @RESIDUE{268} Iterate; OUTCOME{298} Returns; 
c71:"rANY rWHOLE>0 oWHOLE>=0"<50c> Call "CHECKARGS"<d4>; "1"<e4> 
c78:Dots(0) !BIF_ARG.{88} @STRING{1c8} "2"<2a4> Dots(0) !BIF_ARG.{88} 
c84:@NUM{2a0} "3"<2bc> Dots(0) !BIF_ARGEXISTS.{98} Then[c97]; 
c8f:"3"<2bc> Dots(0) !BIF_ARG.{88} @LEN{2a8} NUM{2a0} STRING{1c8} 
c9b:Length Gt[ca2] STRING{1c8} Returns; STRING{1c8} '1'<ec> NUM{2a0} 
ca8:'1'<ec> Subtract BifSUBSTR3 @OUTPUT{1e0} "3"<2bc> Dots(0) 
cb3:!BIF_ARGEXISTS.{98} Then[cd1]; NUM{2a0} LEN{2a8} Add STRING{1c8} 
cbf:Length Le[cd1] OUTPUT{1e0} STRING{1c8} NUM{2a0} LEN{2a8} 
ccb:Add BifSUBSTR2 Abut @OUTPUT{1e0} OUTPUT{1e0} Returns; "
rANY rWHOLE>0 oWHOLE>=0"<50c> Call "CHECKARGS"<d4>; "1"<e4> Dots(0) 
cdd:!BIF_ARG.{88} @STRING{1c8} "2"<2a4> Dots(0) !BIF_ARG.{88} 
ce7:@NUM{2a0} "3"<2bc> Dots(0) !BIF_ARGEXISTS.{98} Then[cfa]; 
cf2:"3"<2bc> Dots(0) !BIF_ARG.{88} @LEN{2a8} NUM{2a0} STRING{1c8} 
cfe:BifqWORDS1 Gt[d06] STRING{1c8} Returns; STRING{1c8} NUM{2a0} 
d0a:BifWORDINDEX2 '1'<ec> Subtract @ENDLEFT{2b0} STRING{1c8} 
d13:ENDLEFT{2b0} BifLEFT2 @OUTPUT{1e0} "3"<2bc> Dots(0) !BIF_ARGEXISTS.{98} 
d1f:Then[d3e]; STRING{1c8} NUM{2a0} LEN{2a8} Add BifWORDINDEX2 
d2b:@BEGINRIGHT{2b8} Unstore '0'<c4> Gt[d3e] OUTPUT{1e0} STRING{1c8} 
d37:BEGINRIGHT{2b8} BifSUBSTR2 Abut @OUTPUT{1e0} OUTPUT{1e0} 
d40:Returns; "rANY rANY oWHOLE>=0 oWHOLE>=0 oPAD"<52c> Call "CHECKARGS"<d4>; 
d46:"1"<e4> Dots(0) !BIF_ARG.{88} @NEW{2c0} "2"<2a4> Dots(0) 
d52:!BIF_ARG.{88} @TARGET{2c8} "3"<2bc> Dots(0) !BIF_ARGEXISTS.{98} 
d5c:Then[d6a]; "3"<2bc> Dots(0) !BIF_ARG.{88} @NUM{2a0} Jump[d6f] 
d6a:AssignConst '0'<c4> NUM{2a0}; "4"<2f4> Dots(0) !BIF_ARGEXISTS.{98} 
d75:Then[d83]; "4"<2f4> Dots(0) !BIF_ARG.{88} @LENGTH{1a8} Jump[d88] 
d83:NEW{2c0} Length @LENGTH{1a8} "5"<534> Dots(0) !BIF_ARGEXISTS.{98} 
d8e:Then[d9c]; "5"<534> Dots(0) !BIF_ARG.{88} @PAD{1d0} Jump[da1] 
d9c:AssignConst " "<10c> PAD{1d0}; TARGET{2c8} NUM{2a0} PAD{1d0} 
da7:BifLEFT3 NEW{2c0} LENGTH{1a8} PAD{1d0} BifLEFT3 Abut TARGET{2c8} 
db4:NUM{2a0} '1'<ec> Add BifSUBSTR2 Abut Returns; "rANY rANY oWHOLE>0"<544> 
dbf:Call "CHECKARGS"<d4>; "1"<e4> Dots(0) !BIF_ARG.{88} @NEEDLE{2d0} 
dca:"2"<2a4> Dots(0) !BIF_ARG.{88} @HAYSTACK{2d8} "3"<2bc> Dots(0) 
dd6:!BIF_ARGEXISTS.{98} Then[de6]; "3"<2bc> Dots(0) !BIF_ARG.{88} 
de1:@START{2e0} Jump[deb] HAYSTACK{2d8} Length @START{2e0} NEEDLE{2d0} 
ded:Length @NEEDLELENGTH{2e8} Unstore '0'<c4> Eq[df9] "0"<a4> 
df8:Returns; START{2e0} NEEDLELENGTH{2e8} Subtract '1'<ec> Add 
e01:@START{2e0} Unstore Number '1'<ec> Negate By ControlVar I{210}[e26]; 
e0e:I{210} '0'<c4> Bool Gt While HAYSTACK{2d8} I{210} NEEDLELENGTH{2e8} 
e1b:BifSUBSTR3 NEEDLE{2d0} Seq[e25] I{210} Returns; IterCV; "0"<a4> 
e28:Returns; "rANY rWHOLE>=0 oPAD"<3f4> Call "CHECKARGS"<d4>; 
e2e:"3"<2bc> Dots(0) !BIF_ARGEXISTS.{98} Then[e42]; "3"<2bc> 
e39:Dots(0) !BIF_ARG.{88} @PAD{1d0} Jump[e47] AssignConst " "<10c> 
e45:PAD{1d0}; "1"<e4> Dots(0) !BIF_ARG.{88} '1'<ec> "2"<2a4> 
e51:Dots(0) !BIF_ARG.{88} PAD{1d0} BifSUBSTR4 Returns; "rANY"<55c> 
e5c:Call "CHECKARGS"<d4>; "1"<e4> Dots(0) !BIF_ARG.{88} @STRING{1c8} 
e67:Unstore Invoke(1) "CONFIG_LENGTH"<564> @INDICATION{2f0} !OUTCOME{2f8} 
e70:@LENGTH{1a8} INDICATION{2f0} "1"<e4> Call "CONFIG_SUBSTR"<56c>; 
e79:!OUTCOME{2f8} "E"<15c> Sne[e83] LENGTH{1a8} Returns; STRING{1c8} 
e85:Call "CONFIG_C2B"<574>; "SYNTAX"<3cc> "23.1"<57c> !OUTCOME{2f8} 
e8e:BifB2X1 Call "!RAISE"<3c4>; "rANY rANY oWHOLE>0 oWHOLE>=0 oPAD"<594> 
e95:Call "CHECKARGS"<d4>; "1"<e4> Dots(0) !BIF_ARG.{88} @NEW{2c0} 
ea0:"2"<2a4> Dots(0) !BIF_ARG.{88} @TARGET{2c8} "3"<2bc> Dots(0) 
eac:!BIF_ARGEXISTS.{98} Then[ebc]; "3"<2bc> Dots(0) !BIF_ARG.{88} 
eb7:@NUM{2a0} Jump[ec1] AssignConst '1'<ec> NUM{2a0}; "4"<2f4> 
ec3:Dots(0) !BIF_ARGEXISTS.{98} Then[ed5]; "4"<2f4> Dots(0) !BIF_ARG.{88} 
ed0:@LENGTH{1a8} Jump[eda] NEW{2c0} Length @LENGTH{1a8} "5"<534> 
edc:Dots(0) !BIF_ARGEXISTS.{98} Then[eee]; "5"<534> Dots(0) !BIF_ARG.{88} 
ee9:@PAD{1d0} Jump[ef3] AssignConst " "<10c> PAD{1d0}; TARGET{2c8} 
ef5:NUM{2a0} '1'<ec> Subtract PAD{1d0} BifLEFT3 NEW{2c0} LENGTH{1a8} 
f02:PAD{1d0} BifLEFT3 Abut TARGET{2c8} NUM{2a0} LENGTH{1a8} Add 
f0e:BifSUBSTR2 Abut Returns; "rANY rANY oWHOLE>0"<544> Call "CHECKARGS"<d4>; 
f17:"1"<e4> Dots(0) !BIF_ARG.{88} @NEEDLE{2d0} "2"<2a4> Dots(0) 
f23:!BIF_ARG.{88} @HAYSTACK{2d8} "3"<2bc> Dots(0) !BIF_ARGEXISTS.{98} 
f2d:Then[f3b]; "3"<2bc> Dots(0) !BIF_ARG.{88} @START{2e0} Jump[f40] 
f3b:AssignConst '1'<ec> START{2e0}; NEEDLE{2d0} Length '0'<c4> 
f45:Eq[f4b] "0"<a4> Returns; START{2e0} Number HAYSTACK{2d8} 
f50:Length '1'<ec> Add NEEDLE{2d0} Length Subtract To ControlVar 
f5a:I{210}[f70]; HAYSTACK{2d8} I{210} NEEDLE{2d0} Length BifSUBSTR3 
f67:NEEDLE{2d0} Seq[f6f] I{210} Returns; IterCV; "0"<a4> Returns; 
f73:"rANY"<55c> Call "CHECKARGS"<d4>; "1"<e4> Dots(0) !BIF_ARG.{88} 
f7e:@STRING{1c8} AssignConst ""<ac> OUTPUT{1e0}; '1'<ec> Number 
f88:STRING{1c8} Length To ControlVar I{210}[f9f]; STRING{1c8} 
f93:I{210} '1'<ec> BifSUBSTR3 OUTPUT{1e0} Abut @OUTPUT{1e0} IterCV; 
f9f:OUTPUT{1e0} Returns; "rANY rWHOLE>=0 oPAD"<3f4> Call "CHECKARGS"<d4>; 
fa7:"1"<e4> Dots(0) !BIF_ARG.{88} @STRING{1c8} "2"<2a4> Dots(0) 
fb3:!BIF_ARG.{88} @LENGTH{1a8} "3"<2bc> Dots(0) !BIF_ARGEXISTS.{98} 
fbd:Then[fcb]; "3"<2bc> Dots(0) !BIF_ARG.{88} @PAD{1d0} Jump[fd0] 
fcb:AssignConst " "<10c> PAD{1d0}; STRING{1c8} Length LENGTH{1a8} 
fd5:Subtract @TRIM{1d8} Unstore '0'<c4> Ge[fe8] STRING{1c8} TRIM{1d8} 
fe2:'1'<ec> Add BifSUBSTR2 Returns; PAD{1d0} TRIM{1d8} Negate 
fed:BifCOPIES2 STRING{1c8} Abut Returns; "rANY oWHOLE>=0 oPAD"<5bc> 
ff5:Call "CHECKARGS"<d4>; "1"<e4> Dots(0) !BIF_ARG.{88} @STRING{1c8} 
1000:"2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} Then[1014]; "2"<2a4> 
100b:Dots(0) !BIF_ARG.{88} @NUM{2a0} Jump[1019] AssignConst '1'<ec> 
1017:NUM{2a0}; "3"<2bc> Dots(0) !BIF_ARGEXISTS.{98} Then[102d]; 
1022:"3"<2bc> Dots(0) !BIF_ARG.{88} @PAD{1d0} Jump[1032] AssignConst 
102e:" "<10c> PAD{1d0}; PAD{1d0} NUM{2a0} BifCOPIES2 @PADDING{300} 
103a:STRING{1c8} '1'<ec> '1'<ec> BifqSUBWORD3 @OUTPUT{1e0} '2'<2ac> 
1046:Number STRING{1c8} BifqWORDS1 To ControlVar I{210}[1062]; 
1051:OUTPUT{1e0} PADDING{300} Abut STRING{1c8} I{210} '1'<ec> 
105c:BifSUBWORD3 Abut @OUTPUT{1e0} IterCV; OUTPUT{1e0} Returns; 
1065:"rANY oLTB oPAD"<5d4> Call "CHECKARGS"<d4>; "1"<e4> Dots(0) 
106e:!BIF_ARG.{88} @STRING{1c8} "2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} 
1078:Then[1086]; "2"<2a4> Dots(0) !BIF_ARG.{88} @OPTION{308} 
1083:Jump[108b] AssignConst "B"<234> OPTION{308}; "3"<2bc> Dots(0) 
108f:!BIF_ARGEXISTS.{98} Then[109f]; "3"<2bc> Dots(0) !BIF_ARG.{88} 
109a:@UNWANTED{310} Jump[10a3] !ALLBLANKS{208} @UNWANTED{310} 
10a3:OPTION{308} "L"<27c> Bool Seq OPTION{308} "B"<234> Bool 
10ae:Seq Or Then[10d5]; RepEver[10d5]; STRING{1c8} ""<ac> Bool 
10bb:Sne STRING{1c8} '1'<ec> BifqLEFT2 UNWANTED{310} BifqPOS2 
10c6:'0'<c4> Bool Gt And While STRING{1c8} '2'<2ac> BifqSUBSTR2 
10d2:@STRING{1c8} Iterate; OPTION{308} "T"<5dc> Bool Seq OPTION{308} 
10dd:"B"<234> Bool Seq Or Then[110b]; RepEver[110b]; STRING{1c8} 
10ea:""<ac> Bool Sne STRING{1c8} '1'<ec> BifqRIGHT2 UNWANTED{310} 
10f6:BifqPOS2 '0'<c4> Bool Gt And While STRING{1c8} STRING{1c8} 
1102:Length '1'<ec> Subtract BifLEFT2 @STRING{1c8} Iterate; STRING{1c8} 
110d:Returns; "rANY rWHOLE>0 oWHOLE>=0 oPAD"<5ec> Call "CHECKARGS"<d4>; 
1113:"1"<e4> Dots(0) !BIF_ARG.{88} @STRING{1c8} "2"<2a4> Dots(0) 
111f:!BIF_ARG.{88} @NUM{2a0} "3"<2bc> Dots(0) !BIF_ARGEXISTS.{98} 
1129:Then[1137]; "3"<2bc> Dots(0) !BIF_ARG.{88} @LENGTH{1a8} 
1134:Jump[1142] STRING{1c8} Length '1'<ec> Add NUM{2a0} Subtract 
1140:@LENGTH{1a8} "4"<2f4> Dots(0) !BIF_ARGEXISTS.{98} Then[1156]; 
114b:"4"<2f4> Dots(0) !BIF_ARG.{88} @PAD{1d0} Jump[115b] AssignConst 
1157:" "<10c> PAD{1d0}; AssignConst ""<ac> OUTPUT{1e0}; LENGTH{1a8} 
1162:Rep[11ab]; STRING{1c8} NUM{2a0} Invoke(2) "CONFIG_SUBSTR"<56c> 
116d:@INDICATION{2f0} !OUTCOME{2f8} @CHARACTER{318} NUM{2a0} 
1175:'1'<ec> Add @NUM{2a0} INDICATION{2f0} "1"<e4> Call "CONFIG_SUBSTR"<56c>; 
1181:!OUTCOME{2f8} "E"<15c> Seq[1198] STRING{1c8} Call "CONFIG_C2B"<574>; 
118d:"SYNTAX"<3cc> "23.1"<57c> !OUTCOME{2f8} BifB2X1 Call "!RAISE"<3c4>; 
1198:!OUTCOME{2f8} "M"<494> Seq[11a3] PAD{1d0} @CHARACTER{318} 
11a3:OUTPUT{1e0} CHARACTER{318} Abut @OUTPUT{1e0} IterRep; OUTPUT{1e0} 
11ad:Returns; "rANY rWHOLE>0 oWHOLE>=0"<50c> Call "CHECKARGS"<d4>; 
11b3:"1"<e4> Dots(0) !BIF_ARG.{88} @STRING{1c8} "2"<2a4> Dots(0) 
11bf:!BIF_ARG.{88} @NUM{2a0} "3"<2bc> Dots(0) !BIF_ARGEXISTS.{98} 
11c9:Then[11d7]; "3"<2bc> Dots(0) !BIF_ARG.{88} @LENGTH{1a8} 
11d4:Jump[11dc] STRING{1c8} Length @LENGTH{1a8} LENGTH{1a8} '0'<c4> 
11e0:Eq[11e6] ""<ac> Returns; STRING{1c8} NUM{2a0} BifWORDINDEX2 
11ec:@START{2e0} Unstore '0'<c4> Eq[11f7] ""<ac> Returns; STRING{1c8} 
11f9:NUM{2a0} LENGTH{1a8} Add BifWORDINDEX2 @END{320} Unstore 
1203:'0'<c4> Eq[1210] STRING{1c8} Length '1'<ec> Add @END{320} 
1210:STRING{1c8} START{2e0} END{320} START{2e0} Subtract BifSUBSTR3 
121b:@OUTPUT{1e0} RepEver[1244]; OUTPUT{1e0} ""<ac> Bool Sne 
1226:While OUTPUT{1e0} '1'<ec> BifqRIGHT2 !ALLBLANKS{208} BifqPOS2 
1231:'0'<c4> Eq[1237] Leave; OUTPUT{1e0} OUTPUT{1e0} Length '1'<ec> 
123e:Subtract BifLEFT2 @OUTPUT{1e0} Iterate; OUTPUT{1e0} Returns; 
1247:"rANY oANY oANY oPAD"<604> Call "CHECKARGS"<d4>; "1"<e4> 
124e:Dots(0) !BIF_ARG.{88} @STRING{1c8} "2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} 
125a:Not "3"<2bc> Dots(0) !BIF_ARGEXISTS.{98} Not And Then[1290]; 
1266:AssignConst ""<ac> OUTPUT{1e0}; '1'<ec> Number STRING{1c8} 
1270:Length To ControlVar J{68}[128d]; STRING{1c8} J{68} '1'<ec> 
127d:BifSUBSTR3 Invoke(1) "CONFIG_UPPER"<60c> @INDICATION{2f0} 
1285:OUTPUT{1e0} !OUTCOME{2f8} Abut @OUTPUT{1e0} IterCV; OUTPUT{1e0} 
128f:Returns; "3"<2bc> Dots(0) !BIF_ARGEXISTS.{98} Not Then[12a7]; 
129a:Invoke(0) "CONFIG_XRANGE"<614> @INDICATION{2f0} !OUTCOME{2f8} 
12a2:@TABLEI{328} Jump[12af] "3"<2bc> Dots(0) !BIF_ARG.{88} @TABLEI{328} 
12af:"2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} Then[12c3]; "2"<2a4> 
12ba:Dots(0) !BIF_ARG.{88} @TABLEO{330} Jump[12c8] AssignConst 
12c4:""<ac> TABLEO{330}; "4"<2f4> Dots(0) !BIF_ARGEXISTS.{98} 
12ce:Then[12dc]; "4"<2f4> Dots(0) !BIF_ARG.{88} @PAD{1d0} Jump[12e1] 
12dc:AssignConst " "<10c> PAD{1d0}; TABLEO{330} TABLEI{328} Length 
12e6:PAD{1d0} BifLEFT3 @TABLEO{330} AssignConst ""<ac> OUTPUT{1e0}; 
12f1:'1'<ec> Number STRING{1c8} Length To ControlVar J{68}[132c]; 
12fd:STRING{1c8} J{68} '1'<ec> BifSUBSTR3 @C{238} Unstore TABLEI{328} 
130a:BifqPOS2 @K{338} Unstore '0'<c4> Eq[131e] OUTPUT{1e0} C{238} 
1318:Abut @OUTPUT{1e0} Jump[132b] OUTPUT{1e0} TABLEO{330} K{338} 
1324:'1'<ec> BifSUBSTR3 Abut @OUTPUT{1e0} IterCV; OUTPUT{1e0} 
132e:Returns; "rANY rANY oMN oWHOLE>0"<624> Call "CHECKARGS"<d4>; 
1334:"1"<e4> Dots(0) !BIF_ARG.{88} @STRING{1c8} "2"<2a4> Dots(0) 
1340:!BIF_ARG.{88} @REFERENCE{340} "3"<2bc> Dots(0) !BIF_ARGEXISTS.{98} 
134a:Then[1358]; "3"<2bc> Dots(0) !BIF_ARG.{88} @OPTION{308} 
1355:Jump[135d] AssignConst "N"<154> OPTION{308}; "4"<2f4> Dots(0) 
1361:!BIF_ARGEXISTS.{98} Then[1371]; "4"<2f4> Dots(0) !BIF_ARG.{88} 
136c:@START{2e0} Jump[1376] AssignConst '1'<ec> START{2e0}; STRING{1c8} 
1378:Length @LAST{348} START{2e0} LAST{348} Gt[1385] "0"<a4> 
1384:Returns; REFERENCE{340} ""<ac> Seq[139c] OPTION{308} "N"<154> 
1390:Seq[1399] START{2e0} Returns; Jump[139c] "0"<a4> Returns; 
139c:START{2e0} Number LAST{348} To ControlVar I{210}[13d4]; 
13a7:STRING{1c8} I{210} '1'<ec> BifSUBSTR3 REFERENCE{340} BifqPOS2 
13b3:@T{70} OPTION{308} "N"<154> Seq[13c9] T{70} '0'<c4> Eq[13c6] 
13c3:I{210} Returns; Jump[13d3] T{70} '0'<c4> Gt[13d3] I{210} 
13d2:Returns; IterCV; "0"<a4> Returns; "rANY rWHOLE>0"<634> Call 
13da:"CHECKARGS"<d4>; "1"<e4> Dots(0) !BIF_ARG.{88} "2"<2a4> 
13e4:Dots(0) !BIF_ARG.{88} '1'<ec> BifSUBWORD3 Returns; "rANY rWHOLE>0"<634> 
13ef:Call "CHECKARGS"<d4>; "1"<e4> Dots(0) !BIF_ARG.{88} @STRING{1c8} 
13fa:"2"<2a4> Dots(0) !BIF_ARG.{88} @NUM{2a0} AssignConst '1'<ec> 
1405:START{2e0}; AssignConst '0'<c4> COUNT{350}; RepEver[144b]; 
140f:STRING{1c8} !ALLBLANKS{208} "N"<154> START{2e0} BifVERIFY4 
1419:@START{2e0} Unstore '0'<c4> Eq[1424] "0"<a4> Returns; COUNT{350} 
1426:'1'<ec> Add @COUNT{350} Unstore NUM{2a0} Eq[1432] Leave; 
1432:STRING{1c8} !ALLBLANKS{208} "M"<494> START{2e0} '1'<ec> 
143c:Add BifVERIFY4 @START{2e0} Unstore '0'<c4> Eq[144a] "0"<a4> 
1449:Returns; Iterate; START{2e0} Returns; "rANY rWHOLE>0"<634> 
1450:Call "CHECKARGS"<d4>; "1"<e4> Dots(0) !BIF_ARG.{88} "2"<2a4> 
145b:Dots(0) !BIF_ARG.{88} '1'<ec> BifSUBWORD3 Length Returns; 
1465:"rANY rANY oWHOLE>0"<544> Call "CHECKARGS"<d4>; "1"<e4> 
146c:Dots(0) !BIF_ARG.{88} @PHRASE{358} "2"<2a4> Dots(0) !BIF_ARG.{88} 
1478:@STRING{1c8} "3"<2bc> Dots(0) !BIF_ARGEXISTS.{98} Then[148e]; 
1483:"3"<2bc> Dots(0) !BIF_ARG.{88} @START{2e0} Jump[1493] AssignConst 
148f:'1'<ec> START{2e0}; PHRASE{358} BifqSPACE1 @PHRASE{358} 
1499:Unstore BifqWORDS1 @PHRASEWORDS{360} Unstore '0'<c4> Eq[14a7] 
14a4:"0"<a4> Returns; STRING{1c8} BifqSPACE1 @STRING{1c8} Unstore 
14ae:BifqWORDS1 @STRINGWORDS{368} START{2e0} Number STRINGWORDS{368} 
14b7:PHRASEWORDS{360} Subtract '1'<ec> Add To ControlVar WORDNUMBER{370}[14d4];
 PHRASE{358} STRING{1c8} WORDNUMBER{370} PHRASEWORDS{360} BifSUBWORD3 
14cd:Seq[14d3] WORDNUMBER{370} Returns; IterCV; "0"<a4> Returns; 
14d7:"rANY"<55c> Call "CHECKARGS"<d4>; '0'<c4> Number '1'<ec> 
14e1:By ControlVar COUNT{350}[14fd]; "1"<e4> Dots(0) !BIF_ARG.{88} 
14ed:COUNT{350} '1'<ec> Add BifSUBWORD2 ""<ac> Seq[14fc] COUNT{350} 
14fb:Returns; IterCV; "oPAD oPAD"<66c> Call "CHECKARGS"<d4>; 
1502:"1"<e4> Dots(0) !BIF_ARGEXISTS.{98} Not Then[1513]; ""<ac> 
150e:"1"<e4> AssignDots !BIF_ARG.{88}; "2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} 
1519:Not Then[1524]; ""<ac> "2"<2a4> AssignDots !BIF_ARG.{88}; 
1524:"1"<e4> Dots(0) !BIF_ARG.{88} "2"<2a4> Dots(0) !BIF_ARG.{88} 
1530:Invoke(2) "CONFIG_XRANGE"<614> @INDICATION{2f0} !OUTCOME{2f8} 
1538:Returns; "rNUM"<67c> Call "CHECKARGS"<d4>; "1"<e4> Dots(0) 
1542:!BIF_ARG.{88} @NUMBER{378} Unstore '1'<ec> BifqLEFT2 "-"<4ec> 
154d:Ceq[1558] NUMBER{378} '2'<2ac> BifqSUBSTR2 @NUMBER{378} 
1558:NUMBER{378} Returns; "rNUM oWHOLE>=0 oWHOLE>=0 oWHOLE>=0 oWHOLE>=0"<68c> 
155d:Call "CHECKARGS"<d4>; "2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} 
1566:Then[1571]; "2"<2a4> Dots(0) !BIF_ARG.{88} @BEFORE{248} 
1571:"3"<2bc> Dots(0) !BIF_ARGEXISTS.{98} Then[1582]; "3"<2bc> 
157c:Dots(0) !BIF_ARG.{88} @AFTER{250} "4"<2f4> Dots(0) !BIF_ARGEXISTS.{98} 
1588:Then[1593]; "4"<2f4> Dots(0) !BIF_ARG.{88} @EXPP{380} "5"<534> 
1595:Dots(0) !BIF_ARGEXISTS.{98} Then[15a7]; "5"<534> Dots(0) 
15a0:!BIF_ARG.{88} @EXPT{388} Jump[15af] !LEVEL{e8} Dots(0) !DIGITS.{d8} 
15ad:@EXPT{388} "1"<e4> Dots(0) !BIF_ARG.{88} @NUMBER{378} "0"<a4> 
15b9:Dots(0) !BIF_ARG.{88} '2'<2ac> Lt[15c5] NUMBER{378} Returns; 
15c5:NUMBER{378} Parse(0) "E"<15c> (Pattern) @MANTISSA{390} (PosRest) 
15cf:@EXPONENT{278} (ParseEnd) EXPONENT{278} ""<ac> Seq[15de] 
15d9:AssignConst '0'<c4> EXPONENT{278}; AssignConst '0'<c4> SIGN{270}; 
15e3:MANTISSA{390} '1'<ec> BifqLEFT2 "-"<4ec> Seq[15fb] AssignConst 
15ef:'1'<ec> SIGN{270}; MANTISSA{390} '2'<2ac> BifqSUBSTR2 @MANTISSA{390} 
15fb:MANTISSA{390} Parse(0) "."<4d4> (Pattern) @BEFO{398} (PosRest) 
1605:@AFTE{3a0} (ParseEnd) BEFO{398} AFTE{3a0} Abut @MANTISSA{390} 
160f:EXPONENT{278} AFTE{3a0} Length Subtract @EXPONENT{278} RepEver[1636]; 
161a:MANTISSA{390} Length '1'<ec> Bool Gt MANTISSA{390} '1'<ec> 
1625:BifqLEFT2 "0"<a4> Bool Seq And While MANTISSA{390} '2'<2ac> 
1631:BifqSUBSTR2 @MANTISSA{390} Iterate; MANTISSA{390} Length 
1639:@POINT{3a8} AssignConst '0'<c4> SHOWEXP{3b0}; MANTISSA{390} 
1642:Length EXPONENT{278} Add EXPT{388} Gt[1650] AssignConst 
164c:'1'<ec> SHOWEXP{3b0}; !NOTJ18{38} Then[166e]; EXPONENT{278} 
1657:Negate '2'<2ac> EXPT{388} Multiply Gt[166e] EXPONENT{278} 
1662:Negate MANTISSA{390} Length Ge[166e] AssignConst '1'<ec> 
166c:SHOWEXP{3b0}; !NOTJ18{38} Not Then[1685]; EXPONENT{278} 
1676:Negate MANTISSA{390} Length Subtract '6'<69c> Ge[1685] AssignConst 
1681:'1'<ec> SHOWEXP{3b0}; "4"<2f4> Dots(0) !BIF_ARGEXISTS.{98} 
168b:Then[169a]; EXPP{380} '0'<c4> Eq[169a] AssignConst '0'<c4> 
1698:SHOWEXP{3b0}; SHOWEXP{3b0} Then[16e0]; AssignConst '1'<ec> 
16a2:POINT{3a8}; EXPONENT{278} MANTISSA{390} Length Add '1'<ec> 
16ac:Subtract @EXPONENT{278} !LEVEL{e8} Dots(0) !FORM.{f0} "ENGINEERING"<b4> 
16b7:Seq[16dd] RepEver[16dd]; EXPONENT{278} '3'<2c4> Remainder 
16c2:'0'<c4> Bool Ne While POINT{3a8} '1'<ec> Add @POINT{3a8} 
16ce:EXPONENT{278} '1'<ec> Subtract @EXPONENT{278} MANTISSA{390} 
16d7:"0"<a4> Abut @MANTISSA{390} Iterate; Jump[1732] MANTISSA{390} 
16e2:Length @POINT{3a8} RepEver[1705]; EXPONENT{278} '0'<c4> 
16ec:Bool Gt While MANTISSA{390} "0"<a4> Abut @MANTISSA{390} 
16f6:POINT{3a8} '1'<ec> Add @POINT{3a8} EXPONENT{278} '1'<ec> 
1701:Subtract @EXPONENT{278} Iterate; RepEver[1732]; EXPONENT{278} 
170a:'0'<c4> Bool Lt While POINT{3a8} '1'<ec> Subtract @POINT{3a8} 
1716:Unstore '1'<ec> Lt[172a] "0"<a4> MANTISSA{390} Abut @MANTISSA{390} 
1723:POINT{3a8} '1'<ec> Add @POINT{3a8} EXPONENT{278} '1'<ec> 
172e:Add @EXPONENT{278} Iterate; MANTISSA{390} Length POINT{3a8} 
1737:Subtract @AFTERS{3b8} "3"<2bc> Dots(0) !BIF_ARGEXISTS.{98} 
1740:'0'<c4> Eq[1749] AFTERS{3b8} @AFTER{250} RepEver[1762]; 
174c:AFTERS{3b8} AFTER{250} Bool Lt While AFTERS{3b8} '1'<ec> 
1757:Add @AFTERS{3b8} MANTISSA{390} "0"<a4> Abut @MANTISSA{390} 
1761:Iterate; AFTERS{3b8} AFTER{250} Gt[1810] MANTISSA{390} POINT{3a8} 
176d:AFTER{250} Add '1'<ec> Add '1'<ec> BifSUBSTR3 @R{138} MANTISSA{390} 
177b:POINT{3a8} AFTER{250} Add BifLEFT2 @MANTISSA{390} Unstore 
1785:Length @MANTLEN{3c0} R{138} '5'<6a4> Ge[1796] MANTISSA{390} 
1791:'1'<ec> Add @MANTISSA{390} MANTISSA{390} '0'<c4> Eq[17a2] 
179d:AssignConst '0'<c4> SIGN{270}; MANTISSA{390} Length MANTLEN{3c0} 
17a7:Lt[17b9] "0"<a4> MANTLEN{3c0} MANTISSA{390} Length Subtract 
17b2:BifCOPIES2 MANTISSA{390} Abut @MANTISSA{390} MANTISSA{390} 
17bb:Length MANTLEN{3c0} Gt[17d3] POINT{3a8} '1'<ec> Add @POINT{3a8} 
17c8:Unstore EXPT{388} Gt[17d3] AssignConst '1'<ec> SHOWEXP{3b0}; 
17d3:SHOWEXP{3b0} '1'<ec> Eq[1810] EXPONENT{278} POINT{3a8} '1'<ec> 
17e0:Subtract Add @EXPONENT{278} AssignConst '1'<ec> POINT{3a8}; 
17e9:!LEVEL{e8} Dots(0) !FORM.{f0} "ENGINEERING"<b4> Seq[1810] 
17f4:RepEver[1810]; EXPONENT{278} '3'<2c4> Remainder '0'<c4> 
17fe:Bool Ne While POINT{3a8} '1'<ec> Add @POINT{3a8} EXPONENT{278} 
180a:'1'<ec> Subtract @EXPONENT{278} Iterate; AFTER{250} '0'<c4> 
1814:Gt[182a] "."<4d4> MANTISSA{390} POINT{3a8} '1'<ec> Add AFTER{250} 
1822:BifSUBSTR3 Abut @AFTE{3a0} Jump[182f] AssignConst ""<ac> 
182d:AFTE{3a0}; MANTISSA{390} POINT{3a8} BifLEFT2 @MANTISSA{390} 
1837:"2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} '0'<c4> Eq[1849] POINT{3a8} 
1844:SIGN{270} Add @BEFORE{248} POINT{3a8} BEFORE{248} SIGN{270} 
184f:Subtract Gt[1860] "40.38"<6ac> "2"<2a4> "1"<e4> Dots(0) 
185b:!BIF_ARG.{88} Call "RAISE"<114>; RepEver[1879]; POINT{3a8} 
1865:BEFORE{248} Bool Lt While POINT{3a8} '1'<ec> Add @POINT{3a8} 
1871:"0"<a4> MANTISSA{390} Abut @MANTISSA{390} Iterate; AssignConst 
187a:""<ac> R{138}; AssignConst '0'<c4> TRIGGERED{3c8}; '1'<ec> 
1885:Number MANTISSA{390} Length To ControlVar J{68}[1903]; MANTISSA{390} 
1891:J{68} '1'<ec> BifSUBSTR3 @DIGIT{3d0} TRIGGERED{3c8} '1'<ec> 
189d:Eq[18a8] R{138} DIGIT{3d0} Abut @R{138} IterCV; DIGIT{3d0} 
18aa:'0'<c4> Eq[18d4] MANTISSA{390} J{68} '1'<ec> Add '1'<ec> 
18b8:BifSUBSTR3 '0'<c4> Bool Eq J{68} '1'<ec> Add MANTISSA{390} 
18c5:Length Bool Lt And Then[18d4]; R{138} " "<10c> Abut @R{138} 
18d3:IterCV; DIGIT{3d0} '0'<c4> Bool Eq J{68} MANTISSA{390} Length 
18df:Bool Ne And Then[18ea]; AssignConst " "<10c> DIGIT{3d0}; 
18ea:SIGN{270} '1'<ec> Eq[18f6] AssignConst "-"<4ec> DIGIT{3d0}; 
18f6:R{138} DIGIT{3d0} Abut @R{138} AssignConst '1'<ec> TRIGGERED{3c8}; 
1902:IterCV; R{138} AFTE{3a0} Abut @NUMBER{378} SHOWEXP{3b0} 
190c:'1'<ec> Eq[1997] AssignConst ""<ac> EXPART{3d8}; AssignConst 
1917:'0'<c4> SIGNEXP{3e0}; EXPONENT{278} '0'<c4> Lt[192c] AssignConst 
1923:'1'<ec> SIGNEXP{3e0}; EXPONENT{278} Negate @EXPONENT{278} 
192c:"4"<2f4> Dots(0) !BIF_ARGEXISTS.{98} '0'<c4> Eq[193c] EXPONENT{278} 
1939:Length @EXPP{380} EXPONENT{278} Length EXPP{380} Gt[1951] 
1944:"40.38"<6ac> "4"<2f4> "1"<e4> Dots(0) !BIF_ARG.{88} Call 
194f:"RAISE"<114>; EXPONENT{278} EXPP{380} "0"<a4> BifRIGHT3 
1959:@EXPONENT{278} Unstore '0'<c4> Eq[1978] "4"<2f4> Dots(0) 
1965:!BIF_ARGEXISTS.{98} Then[1975]; " "<10c> EXPP{380} '2'<2ac> 
1970:Add BifCOPIES2 @EXPART{3d8} Jump[1990] SIGNEXP{3e0} '0'<c4> 
197c:Eq[1989] "E+"<6b4> EXPONENT{278} Abut @EXPART{3d8} Jump[1990] 
1989:"E-"<6bc> EXPONENT{278} Abut @EXPART{3d8} NUMBER{378} EXPART{3d8} 
1994:Abut @NUMBER{378} NUMBER{378} Returns; "0"<a4> Dots(0) !BIF_ARG.{88} 
19a0:'1'<ec> Lt[19ac] "40.3"<11c> "1"<e4> Call "RAISE"<114>; 
19ac:"rNUM"<67c> " rNUM"<6cc> "0"<a4> Dots(0) !BIF_ARG.{88} '1'<ec> 
19b8:Subtract BifCOPIES2 Abut Call "CHECKARGS"<d4>; "1"<e4> Dots(0) 
19c3:!BIF_ARG.{88} @MAX{3e8} '2'<2ac> Number "0"<a4> Dots(0) 
19ce:!BIF_ARG.{88} To '1'<ec> By ControlVar I{210}[19ed]; I{210} 
19db:Dots(0) !BIF_ARG.{88} @NEXT{3f0} MAX{3e8} NEXT{3f0} Lt[19ec] 
19e8:NEXT{3f0} @MAX{3e8} IterCV; MAX{3e8} Returns; "0"<a4> Dots(0) 
19f4:!BIF_ARG.{88} '1'<ec> Lt[1a02] "40.3"<11c> "1"<e4> Call 
1a00:"RAISE"<114>; "rNUM"<67c> " rNUM"<6cc> "0"<a4> Dots(0) !BIF_ARG.{88} 
1a0c:'1'<ec> Subtract BifCOPIES2 Abut Call "CHECKARGS"<d4>; "1"<e4> 
1a17:Dots(0) !BIF_ARG.{88} @MIN{3f8} '2'<2ac> Number "0"<a4> 
1a22:Dots(0) !BIF_ARG.{88} To '1'<ec> By ControlVar I{210}[1a43]; 
1a2f:I{210} Dots(0) !BIF_ARG.{88} @NEXT{3f0} MIN{3f8} NEXT{3f0} 
1a3b:Gt[1a42] NEXT{3f0} @MIN{3f8} IterCV; MIN{3f8} Returns; "rNUM"<67c> 
1a48:Call "CHECKARGS"<d4>; "1"<e4> Dots(0) !BIF_ARG.{88} @NUMBER{378} 
1a53:Unstore '0'<c4> Lt[1a61] '1'<ec> Negate @OUTPUT{1e0} Jump[1a81] 
1a61:NUMBER{378} '0'<c4> Eq[1a70] AssignConst '0'<c4> OUTPUT{1e0}; 
1a6d:Jump[1a81] NUMBER{378} '0'<c4> Gt[1a7f] AssignConst '1'<ec> 
1a7a:OUTPUT{1e0}; Jump[1a81] Raise(0) OUTPUT{1e0} Returns; "rNUM oWHOLE>=0"<6ec
> Call "CHECKARGS"<d4>; "1"<e4> Dots(0) !BIF_ARG.{88} @NUMBER{378} 
1a91:"2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} Then[1aa5]; "2"<2a4> 
1a9c:Dots(0) !BIF_ARG.{88} @NUM{2a0} Jump[1aaa] AssignConst '0'<c4> 
1aa8:NUM{2a0}; '10'<6fc> NUM{2a0} Power NUMBER{378} Multiply 
1ab2:'1'<ec> IntDivide @INTEGER{130} NUM{2a0} '0'<c4> Eq[1ac1] 
1abe:INTEGER{130} Returns; INTEGER{130} Length NUM{2a0} Subtract 
1ac7:@T{70} Unstore '0'<c4> Le[1adb] "0."<704> INTEGER{130} NUM{2a0} 
1ad5:"0"<a4> BifRIGHT3 Abut Returns; "."<4d4> INTEGER{130} T{70} 
1ae1:BifINSERT3 Returns; "1"<e4> Dots(0) !BIF_ARGEXISTS.{98} 
1aea:Then[1af8]; "1"<e4> Dots(0) !BIF_ARG.{88} @OPTION1{400} 
1af5:Jump[1afd] AssignConst "N"<154> OPTION1{400}; OPTION1{400} 
1aff:"N"<154> Seq[1b0d] ACTIVE{418} !LEVEL{e8} Dots(8) !ENV_NAME.{408} 
1b0c:Returns; "ACTIVE."<71c> OPTION1{400} Abut "."<4d4> Abut 
1b15:!LEVEL{e8} Abut @TAIL{420} "2"<2a4> Dots(0) !BIF_ARG.{88} 
1b20:"T"<5dc> Ceq[1b30] TAIL{420} Dots(0) !ENV_TYPE.{430} @INFO{428} 
1b2d:Jump[1b82] "2"<2a4> Dots(0) !BIF_ARG.{88} "P"<724> Ceq[1b46] 
1b3b:TAIL{420} Dots(0) !ENV_POSITION.{440} @INFO{428} Jump[1b82] 
1b46:"2"<2a4> Dots(0) !BIF_ARG.{88} "N"<154> Ceq[1b5c] TAIL{420} 
1b53:Dots(0) !ENV_RESOURCE.{450} @INFO{428} Jump[1b82] "2"<2a4> 
1b5e:Dots(0) !BIF_ARG.{88} "A"<47c> Ceq[1b80] TAIL{420} Dots(0) 
1b6b:!ENV_TYPE.{430} TAIL{420} Dots(0) !ENV_POSITION.{440} Cat 
1b74:TAIL{420} Dots(0) !ENV_RESOURCE.{450} Cat @INFO{428} Jump[1b82] 
1b80:Raise(0) INFO{428} Returns; AssignConst "oWHOLE>0 oENO"<734> 
1b88:ARGDATA{460}; "2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} Then[1b98]; 
1b93:AssignConst "rWHOLE>0 rENO"<73c> ARGDATA{460}; ARGDATA{460} 
1b9a:Call "CHECKARGS"<d4>; "1"<e4> Dots(0) !BIF_ARGEXISTS.{98} 
1ba3:Not Then[1bb0]; !LEVEL{e8} "0"<a4> Dots(8) !ARG.{468} Returns; 
1bb0:"1"<e4> Dots(0) !BIF_ARG.{88} @ARGNUM{478} "2"<2a4> Dots(0) 
1bbc:!BIF_ARGEXISTS.{98} Not Then[1bcb]; !LEVEL{e8} ARGNUM{478} 
1bc6:Dots(8) !ARG.{468} Returns; "2"<2a4> Dots(0) !BIF_ARG.{88} 
1bd1:"O"<744> Seq[1be3] !LEVEL{e8} ARGNUM{478} Dots(8) !ARGEXISTS.{480} 
1bde:Not Returns; Jump[1bec] !LEVEL{e8} ARGNUM{478} Dots(8) !ARGEXISTS.{480} 
1beb:Returns; "oCDEIS"<754> Call "CHECKARGS"<d4>; "1"<e4> Dots(0) 
1bf5:!BIF_ARG.{88} @OPTION{308} Unstore "C"<75c> Seq[1c06] !LEVEL{e8} 
1c01:Dots(0) !CONDITION.{490} Returns; OPTION{308} "D"<764> Seq[1c14] 
1c0d:!LEVEL{e8} Dots(0) !CONDITIONDESCRIPTION.{4a0} Returns; 
1c14:OPTION{308} "E"<15c> Seq[1c22] !LEVEL{e8} Dots(0) !CONDITIONEXTRA.{4b0} 
1c21:Returns; OPTION{308} "I"<76c> Seq[1c30] !LEVEL{e8} Dots(0) 
1c2d:!CONDITIONINSTRUCTION.{4c0} Returns; !LEVEL{e8} Dots(0) 
1c34:!CONDITIONSTATE.{4d0} Returns; ""<ac> Call "CHECKARGS"<d4>; 
1c3c:!LEVEL{e8} Dots(0) !DIGITS.{d8} Returns; "r0_90 oSN"<784> 
1c45:Call "CHECKARGS"<d4>; "1"<e4> Dots(0) !BIF_ARG.{88} @MSGCODE{4e0} 
1c50:"2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} Then[1c64]; "2"<2a4> 
1c5b:Dots(0) !BIF_ARG.{88} @OPTION{308} Jump[1c69] AssignConst 
1c65:"N"<154> OPTION{308}; OPTION{308} "S"<24c> Seq[1c77] MSGCODE{4e0} 
1c72:Dots(0) !ERRORTEXT.{4e8} Returns; MSGCODE{4e0} Dots(0) !ERRORTEXT.{4e8} 
1c7d:Returns; ""<ac> Call "CHECKARGS"<d4>; !LEVEL{e8} Dots(0) 
1c87:!FORM.{f0} Returns; ""<ac> Call "CHECKARGS"<d4>; !LEVEL{e8} 
1c91:Dots(0) !FUZZ.{4f8} Returns; "oWHOLE>0"<7a4> Call "CHECKARGS"<d4>; 
1c9b:"1"<e4> Dots(0) !BIF_ARGEXISTS.{98} Not Then[1cac]; "0"<a4> 
1ca7:Dots(0) !SOURCELINE.{508} Returns; "1"<e4> Dots(0) !BIF_ARG.{88} 
1cb2:@NUM{2a0} Unstore "0"<a4> Dots(0) !SOURCELINE.{508} Gt[1ccb] 
1cbe:"40.34"<7ac> NUM{2a0} "0"<a4> Dots(0) !SOURCELINE.{508} 
1cc8:Call "RAISE"<114>; NUM{2a0} Dots(0) !SOURCELINE.{508} Returns; 
1cd2:"oACEFILNOR"<7bc> Call "CHECKARGS"<d4>; !LEVEL{e8} Dots(0) 
1cdb:!TRACING.{518} @OUTPUT{1e0} !LEVEL{e8} Dots(0) !INTERACTING.{528} 
1ce5:Then[1cef]; "?"<274> OUTPUT{1e0} Abut @OUTPUT{1e0} "1"<e4> 
1cf1:Dots(0) !BIF_ARGEXISTS.{98} Not Then[1cfc]; OUTPUT{1e0} 
1cfb:Returns; "1"<e4> Dots(0) !BIF_ARG.{88} @VALUE{a8} Unstore 
1d05:""<ac> Seq[1d11] '0'<c4> !LEVEL{e8} AssignDots !INTERACTING.{528}; 
1d11:RepEver[1d34]; VALUE{a8} '1'<ec> BifqLEFT2 "?"<274> Bool 
1d1d:Seq While !LEVEL{e8} Dots(0) !INTERACTING.{528} Not !LEVEL{e8} 
1d28:AssignDots !INTERACTING.{528}; VALUE{a8} '2'<2ac> BifqSUBSTR2 
1d31:@VALUE{a8} Iterate; VALUE{a8} ""<ac> Seq[1d40] AssignConst 
1d3c:"N"<154> VALUE{a8}; VALUE{a8} '1'<ec> BifqLEFT2 BifqTRANSLATE1 
1d48:@VALUE{a8} Unstore "O"<744> Seq[1d57] '0'<c4> !LEVEL{e8} 
1d54:AssignDots !INTERACTING.{528}; VALUE{a8} !LEVEL{e8} AssignDots 
1d5c:!TRACING.{518}; OUTPUT{1e0} Returns; "rBIN"<7cc> Call "CHECKARGS"<d4>; 
1d66:"1"<e4> Dots(0) !BIF_ARG.{88} '0'<c4> BifqSPACE2 @STRING{1c8} 
1d72:Unstore "2"<2a4> "16"<2dc> Invoke(3) "RERADIX"<2b4> Returns; 
1d7c:"rANY oANY oPAD"<7ec> Call "CHECKARGS"<d4>; "1"<e4> Dots(0) 
1d85:!BIF_ARG.{88} @STRING1{538} "2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} 
1d8f:Then[1d9d]; "2"<2a4> Dots(0) !BIF_ARG.{88} @STRING2{540} 
1d9a:Jump[1da2] AssignConst ""<ac> STRING2{540}; "3"<2bc> Dots(0) 
1da6:!BIF_ARGEXISTS.{98} Then[1dd5]; STRING1{538} Length STRING2{540} 
1db0:Length Gt[1dc6] STRING2{540} STRING1{538} Length "3"<2bc> 
1dbb:Dots(0) !BIF_ARG.{88} BifLEFT3 @STRING2{540} Jump[1dd5] 
1dc6:STRING1{538} STRING2{540} Length "3"<2bc> Dots(0) !BIF_ARG.{88} 
1dd1:BifLEFT3 @STRING1{538} STRING1{538} Invoke(1) "CONFIG_C2B"<574> 
1ddb:@INDICATION{2f0} !OUTCOME{2f8} @STRING1{538} STRING2{540} 
1de3:Invoke(1) "CONFIG_C2B"<574> @INDICATION{2f0} !OUTCOME{2f8} 
1deb:@STRING2{540} STRING1{538} Length STRING2{540} Length Lt[1e02] 
1df6:STRING1{538} @T{70} STRING2{540} @STRING1{538} T{70} @STRING2{540} 
1e02:AssignConst ""<ac> R{138}; '1'<ec> Number STRING2{540} Length 
1e0d:To ControlVar J{68}[1e64]; STRING1{538} J{68} '1'<ec> BifSUBSTR3 
1e1b:@B1{548} STRING2{540} J{68} '1'<ec> BifSUBSTR3 @B2{550} 
1e27:!BIF{110} "BITAND"<7f4> Ceq[1e38] B1{548} B2{550} And @B1{548} 
1e35:Jump[1e5c] !BIF{110} "BITOR"<7fc> Ceq[1e49] B1{548} B2{550} 
1e43:Or @B1{548} Jump[1e5c] !BIF{110} "BITXOR"<804> Ceq[1e5a] 
1e50:B1{548} B2{550} Xor @B1{548} Jump[1e5c] Raise(0) R{138} 
1e5e:B1{548} Abut @R{138} IterCV; R{138} STRING1{538} STRING1{538} 
1e6a:Length STRING2{540} Length Subtract BifRIGHT2 Abut @R{138} 
1e74:Unstore BifB2X1 BifX2C1 Returns; "rANY oWHOLE>=0"<81c> Call 
1e7d:"CHECKARGS"<d4>; "1"<e4> Dots(0) !BIF_ARG.{88} Length '0'<c4> 
1e88:Eq[1e8e] "0"<a4> Returns; "2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} 
1e94:Then[1f06]; "2"<2a4> Dots(0) !BIF_ARG.{88} @SIZE{558} Unstore 
1ea0:'0'<c4> Eq[1ea8] "0"<a4> Returns; "1"<e4> Dots(0) !BIF_ARG.{88} 
1eae:SIZE{558} BifqXRANGE0 '1'<ec> BifqLEFT2 BifRIGHT3 @T{70} 
1eba:Unstore Call "CONFIG_C2B"<574>; !OUTCOME{2f8} '1'<ec> BifqLEFT2 
1ec4:@SIGN{270} !OUTCOME{2f8} '2'<2ac> BifqSUBSTR2 @!OUTCOME{2f8} 
1ece:Unstore "2"<2a4> "10"<6f4> Invoke(3) "RERADIX"<2b4> @T{70} 
1ed9:SIGN{270} Then[1ee9]; T{70} '2'<2ac> !OUTCOME{2f8} Length 
1ee5:Power Subtract @T{70} T{70} BifABS1 '10'<6fc> !LEVEL{e8} 
1ef1:Dots(0) !DIGITS.{d8} Power '1'<ec> Subtract Gt[1f03] "40.35"<834> 
1efe:T{70} Call "RAISE"<114>; T{70} Returns; "1"<e4> Dots(0) 
1f0a:!BIF_ARG.{88} Call "CONFIG_C2B"<574>; !OUTCOME{2f8} "2"<2a4> 
1f13:"10"<6f4> Invoke(3) "RERADIX"<2b4> @T{70} Unstore '10'<6fc> 
1f1e:!LEVEL{e8} Dots(0) !DIGITS.{d8} Power '1'<ec> Subtract Gt[1f32] 
1f2b:"40.35"<834> T{70} Call "RAISE"<114>; T{70} Returns; "rANY"<55c> 
1f37:Call "CHECKARGS"<d4>; "1"<e4> Dots(0) !BIF_ARG.{88} Length 
1f41:'0'<c4> Eq[1f49] ""<ac> Returns; "1"<e4> Dots(0) !BIF_ARG.{88} 
1f4f:Call "CONFIG_C2B"<574>; !OUTCOME{2f8} "2"<2a4> "16"<2dc> 
1f58:Invoke(3) "RERADIX"<2b4> Returns; "2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} 
1f63:Not Then[1f6f]; AssignConst "rWHOLENUM>=0"<84c> ARGDATA{460}; 
1f6c:Jump[1f74] AssignConst "rWHOLENUM rWHOLE>=0"<854> ARGDATA{460}; 
1f74:ARGDATA{460} Call "CHECKARGS"<d4>; "1"<e4> Dots(0) !BIF_ARG.{88} 
1f7f:BifABS1 @SUBJECT{118} Unstore "10"<6f4> "2"<2a4> Invoke(3) 
1f8a:"RERADIX"<2b4> @R{138} Unstore Length @LENGTH{1a8} RepEver[1fa7]; 
1f95:LENGTH{1a8} '8'<864> Remainder '0'<c4> Bool Ne While LENGTH{1a8} 
1fa1:'1'<ec> Add @LENGTH{1a8} Iterate; R{138} LENGTH{1a8} "0"<a4> 
1fad:BifRIGHT3 @R{138} "1"<e4> Dots(0) !BIF_ARG.{88} '0'<c4> 
1fb9:Lt[1fd2] '2'<2ac> R{138} Length Power SUBJECT{118} Subtract 
1fc5:@SUBJECT{118} Unstore "10"<6f4> "2"<2a4> Invoke(3) "RERADIX"<2b4> 
1fd0:@R{138} R{138} Invoke(1) "CONFIG_B2C"<86c> @INDICATION{2f0} 
1fda:!OUTCOME{2f8} @OUTPUT{1e0} "2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} 
1fe4:Not Then[1feb]; OUTPUT{1e0} Returns; "1"<e4> Dots(0) !BIF_ARG.{88} 
1ff1:'0'<c4> Ge[200a] OUTPUT{1e0} "2"<2a4> Dots(0) !BIF_ARG.{88} 
1ffe:BifqXRANGE0 '1'<ec> BifqLEFT2 BifRIGHT3 Returns; Jump[201b] 
200a:OUTPUT{1e0} "2"<2a4> Dots(0) !BIF_ARG.{88} BifqXRANGE0 '1'<ec> 
2016:BifqRIGHT2 BifRIGHT3 Returns; "2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} 
2021:Not Then[202d]; AssignConst "rWHOLENUM>=0"<84c> ARGDATA{460}; 
202a:Jump[2032] AssignConst "rWHOLENUM rWHOLE>=0"<854> ARGDATA{460}; 
2032:ARGDATA{460} Call "CHECKARGS"<d4>; "1"<e4> Dots(0) !BIF_ARG.{88} 
203d:BifABS1 @SUBJECT{118} Unstore "10"<6f4> "16"<2dc> Invoke(3) 
2048:"RERADIX"<2b4> @R{138} "1"<e4> Dots(0) !BIF_ARG.{88} '0'<c4> 
2054:Lt[206d] '16'<2e4> R{138} Length Power SUBJECT{118} Subtract 
2060:@SUBJECT{118} Unstore "10"<6f4> "16"<2dc> Invoke(3) "RERADIX"<2b4> 
206b:@R{138} "2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} Not Then[207a]; 
2077:R{138} Returns; "1"<e4> Dots(0) !BIF_ARG.{88} '0'<c4> Ge[2095] 
2085:R{138} "2"<2a4> Dots(0) !BIF_ARG.{88} "0"<a4> BifRIGHT3 
2091:Returns; Jump[20a2] R{138} "2"<2a4> Dots(0) !BIF_ARG.{88} 
209d:"F"<87c> BifRIGHT3 Returns; "rHEX"<88c> Call "CHECKARGS"<d4>; 
20a7:"1"<e4> Dots(0) !BIF_ARG.{88} @SUBJECT{118} Unstore ""<ac> 
20b2:Seq[20b8] ""<ac> Returns; SUBJECT{118} '0'<c4> BifqSPACE2 
20be:@SUBJECT{118} Unstore BifqTRANSLATE1 "16"<2dc> "2"<2a4> 
20c7:Invoke(3) "RERADIX"<2b4> Returns; "rHEX"<88c> Call "CHECKARGS"<d4>; 
20d1:"1"<e4> Dots(0) !BIF_ARG.{88} @SUBJECT{118} Unstore ""<ac> 
20dc:Seq[20e2] ""<ac> Returns; SUBJECT{118} '0'<c4> BifqSPACE2 
20e8:@SUBJECT{118} Unstore BifqTRANSLATE1 "16"<2dc> "2"<2a4> 
20f1:Invoke(3) "RERADIX"<2b4> @R{138} '8'<864> SUBJECT{118} Length 
20fc:'1'<ec> Add '2'<2ac> IntDivide Multiply @LENGTH{1a8} R{138} 
2107:LENGTH{1a8} "0"<a4> BifRIGHT3 Invoke(1) "CONFIG_B2C"<86c> 
2111:@INDICATION{2f0} !OUTCOME{2f8} Returns; "rHEX oWHOLE>=0"<8a4> 
2118:Call "CHECKARGS"<d4>; "1"<e4> Dots(0) !BIF_ARG.{88} @SUBJECT{118} 
2123:Unstore ""<ac> Seq[212c] "0"<a4> Returns; SUBJECT{118} '0'<c4> 
2130:BifqSPACE2 BifqTRANSLATE1 @SUBJECT{118} "2"<2a4> Dots(0) 
213a:!BIF_ARGEXISTS.{98} Then[2155]; SUBJECT{118} "2"<2a4> Dots(0) 
2145:!BIF_ARG.{88} SUBJECT{118} Length '1'<ec> Add Min(1) "0"<a4> 
2151:BifRIGHT3 @SUBJECT{118} SUBJECT{118} ""<ac> Seq[215f] "0"<a4> 
215e:Returns; "2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} Then[2175]; 
2168:SUBJECT{118} BifX2B1 '1'<ec> BifqLEFT2 @SIGNBIT{560} Jump[217a] 
2175:AssignConst '0'<c4> SIGNBIT{560}; SUBJECT{118} "16"<2dc> 
217e:"10"<6f4> Invoke(3) "RERADIX"<2b4> @R{138} SIGNBIT{560} 
2188:Then[219c]; R{138} '2'<2ac> '4'<2fc> "2"<2a4> Dots(0) !BIF_ARG.{88} 
2197:Multiply Power Subtract @R{138} R{138} BifABS1 '10'<6fc> 
21a2:!LEVEL{e8} Dots(0) !DIGITS.{d8} Power '1'<ec> Subtract Gt[21b6] 
21af:"40.35"<834> T{70} Call "RAISE"<114>; R{138} Returns; "
oANY oWHOLE>0 oWHOLE>=0"<8c4> Call "CHECKARGS"<d4>; "1"<e4> Dots(0) 
21c2:!BIF_ARGEXISTS.{98} Then[21d2]; "1"<e4> Dots(0) !BIF_ARG.{88} 
21cd:@STREAM{568} Jump[21d7] AssignConst ""<ac> STREAM{568}; 
21d7:"2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} Then[2207]; "2"<2a4> 
21e2:Dots(0) !BIF_ARG.{88} @CHARPOS{570} STREAM{568} "CHARIN"<8d4> 
21ec:CHARPOS{570} Invoke(3) "CONFIG_POSITION"<8cc> @INDICATION{2f0} 
21f4:Unstore '1'<ec> BifqLEFT2 "B"<234> Seq[2207] "40.27"<8dc> 
2200:"1"<e4> STREAM{568} Call "RAISE"<114>; "3"<2bc> Dots(0) 
220b:!BIF_ARGEXISTS.{98} Then[221b]; "3"<2bc> Dots(0) !BIF_ARG.{88} 
2216:@COUNT{350} Jump[2220] AssignConst '1'<ec> COUNT{350}; COUNT{350} 
2222:'0'<c4> Eq[2231] STREAM{568} "NULL"<8ec> Call "CONFIG_CHARIN"<8e4>; 
222e:""<ac> Returns; STREAM{568} Call "CONFIG_STREAMQUERY"<8f4>; 
2236:!OUTCOME{2f8} @MODE{578} AssignConst ""<ac> R{138}; RepEver[2271]; 
2242:Jump[224c] COUNT{350} '0'<c4> Bool Eq Until STREAM{568} 
224e:"CHARIN"<8d4> Call "CONFIG_CHARIN"<8e4>; !THIS_EXCEPTION{580} 
2255:"READY"<8fc> Sne[2262] "NOTREADY"<904> STREAM{568} Call 
225f:"!RAISE"<3c4>; Leave; R{138} !OUTCOME{2f8} Abut @R{138} 
2269:COUNT{350} '1'<ec> Subtract @COUNT{350} Iterate; MODE{578} 
2273:"B"<234> Seq[2281] R{138} Call "CONFIG_B2C"<86c>; !OUTCOME{2f8} 
227f:@R{138} R{138} Returns; "oANY oANY oWHOLE>0"<914> Call "CHECKARGS"<d4>; 
2289:"1"<e4> Dots(0) !BIF_ARGEXISTS.{98} Then[229d]; "1"<e4> 
2294:Dots(0) !BIF_ARG.{88} @STREAM{568} Jump[22a2] AssignConst 
229e:""<ac> STREAM{568}; "3"<2bc> Dots(0) !BIF_ARGEXISTS.{98} 
22a8:Then[22bc]; "3"<2bc> Dots(0) !BIF_ARG.{88} @CHARPOS{570} 
22b3:STREAM{568} "CHAROUT"<91c> CHARPOS{570} Call "CONFIG_POSITION"<8cc>; 
22bc:"2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} Not Then[22f1]; "3"<2bc> 
22c8:Dots(0) !BIF_ARGEXISTS.{98} Then[22d2]; "0"<a4> Returns; 
22d2:RepEver[22ee]; Jump[22e3] INDICATION{2f0} '1'<ec> BifqLEFT2 
22de:"N"<154> Bool Sne Until STREAM{568} "CHARIN"<8d4> Invoke(2) 
22e9:"CONFIG_CHARIN"<8e4> @INDICATION{2f0} Iterate; "0"<a4> Returns; 
22f1:"2"<2a4> Dots(0) !BIF_ARG.{88} @STRING{1c8} AssignConst 
22fa:'1'<ec> STRIDE{588}; STRING{1c8} Length @RESIDUE{268} STREAM{568} 
2305:Call "CONFIG_STREAMQUERY"<8f4>; !OUTCOME{2f8} @MODE{578} 
230c:Unstore "B"<234> Seq[2328] STRING{1c8} Call "CONFIG_C2B"<574>; 
2317:!OUTCOME{2f8} @STRING{1c8} AssignConst '8'<864> STRIDE{588}; 
2320:STRING{1c8} Length '8'<864> Divide @RESIDUE{268} AssignConst 
2329:'1'<ec> CURSOR{590}; RepEver[2366]; RESIDUE{268} '0'<c4> 
2334:Bool Gt While STRING{1c8} CURSOR{590} STRIDE{588} BifSUBSTR3 
233f:@PIECE{598} CURSOR{590} STRIDE{588} Add @CURSOR{590} STREAM{568} 
234a:PIECE{598} Call "CONFIG_CHAROUT"<924>; !THIS_EXCEPTION{580} 
2351:"READY"<8fc> Sne[235e] !THIS_EXCEPTION{580} Call "!RAISE"<3c4>; 
235b:RESIDUE{268} Returns; RESIDUE{268} '1'<ec> Subtract @RESIDUE{268} 
2365:Iterate; "0"<a4> Returns; "oANY oNIC"<934> Call "CHECKARGS"<d4>; 
236e:"1"<e4> Dots(0) !BIF_ARGEXISTS.{98} Then[2382]; "1"<e4> 
2379:Dots(0) !BIF_ARG.{88} @STREAM{568} Jump[2387] AssignConst 
2383:""<ac> STREAM{568}; "2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} 
238d:Then[239b]; "2"<2a4> Dots(0) !BIF_ARG.{88} @OPTION{308} 
2398:Jump[23a0] AssignConst "N"<154> OPTION{308}; STREAM{568} 
23a2:"CHARIN"<8d4> OPTION{308} Call "CONFIG_STREAMCOUNT"<93c>; 
23a9:!OUTCOME{2f8} Returns; "oANY oWHOLE>0 oWHOLE>=0"<8c4> Call 
23af:"CHECKARGS"<d4>; "1"<e4> Dots(0) !BIF_ARGEXISTS.{98} Then[23c5]; 
23ba:"1"<e4> Dots(0) !BIF_ARG.{88} @STREAM{568} Jump[23ca] AssignConst 
23c6:""<ac> STREAM{568}; "2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} 
23d0:Then[23e4]; "2"<2a4> Dots(0) !BIF_ARG.{88} @LINEPOS{5a0} 
23db:STREAM{568} "LINEIN"<94c> LINEPOS{5a0} Call "CONFIG_POSITION"<8cc>; 
23e4:"3"<2bc> Dots(0) !BIF_ARGEXISTS.{98} Then[23f8]; "3"<2bc> 
23ef:Dots(0) !BIF_ARG.{88} @COUNT{350} Jump[23fd] AssignConst 
23f9:'1'<ec> COUNT{350}; COUNT{350} '1'<ec> Gt[240b] "40.42"<954> 
2406:COUNT{350} Call "RAISE"<114>; COUNT{350} '0'<c4> Eq[2415] 
2412:""<ac> Returns; STREAM{568} Call "CONFIG_STREAMQUERY"<8f4>; 
241a:!OUTCOME{2f8} @MODE{578} AssignConst ""<ac> R{138}; STREAM{568} 
2425:Dots(0) !LINEIN_POSITION.{5a8} @T{70} RepEver[246f]; Jump[243c] 
2431:T{70} STREAM{568} Dots(0) !LINEIN_POSITION.{5a8} Bool Ne 
243b:Until RepEver[2458]; Jump[244d] INDICATION{2f0} '1'<ec> 
2446:BifqLEFT2 "T"<5dc> Bool Sne Until STREAM{568} "LINEIN"<94c> 
2451:Invoke(2) "CONFIG_CHARIN"<8e4> @INDICATION{2f0} Iterate; 
2458:!THIS_EXCEPTION{580} "READY"<8fc> Sne[2467] !THIS_EXCEPTION{580} 
2461:Call "!RAISE"<3c4>; ""<ac> Returns; R{138} !OUTCOME{2f8} 
246b:Abut @R{138} Iterate; MODE{578} "B"<234> Seq[247f] R{138} 
2478:Call "CONFIG_B2C"<86c>; !OUTCOME{2f8} @R{138} R{138} Returns; 
2482:"oANY oANY oWHOLE>0"<914> Call "CHECKARGS"<d4>; "1"<e4> 
2489:Dots(0) !BIF_ARGEXISTS.{98} Then[249b]; "1"<e4> Dots(0) 
2494:!BIF_ARG.{88} @STREAM{568} Jump[24a0] AssignConst ""<ac> 
249e:STREAM{568}; "3"<2bc> Dots(0) !BIF_ARGEXISTS.{98} Then[24ba]; 
24a9:"3"<2bc> Dots(0) !BIF_ARG.{88} @LINEPOS{5a0} STREAM{568} 
24b3:"LINEOUT"<964> LINEPOS{5a0} Call "CONFIG_POSITION"<8cc>; 
24ba:"2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} Not Then[24ef]; "3"<2bc> 
24c6:Dots(0) !BIF_ARGEXISTS.{98} Then[24d0]; "0"<a4> Returns; 
24d0:RepEver[24ec]; Jump[24e1] INDICATION{2f0} '1'<ec> BifqLEFT2 
24dc:"N"<154> Bool Sne Until STREAM{568} "LINEIN"<94c> Invoke(2) 
24e7:"CONFIG_CHARIN"<8e4> @INDICATION{2f0} Iterate; "0"<a4> Returns; 
24ef:"2"<2a4> Dots(0) !BIF_ARG.{88} @STRING{1c8} AssignConst 
24f8:'1'<ec> STRIDE{588}; STRING{1c8} Length @RESIDUE{268} STREAM{568} 
2503:Call "CONFIG_STREAMQUERY"<8f4>; !OUTCOME{2f8} @MODE{578} 
250a:Unstore "B"<234> Seq[2526] STRING{1c8} Call "CONFIG_C2B"<574>; 
2515:!OUTCOME{2f8} @STRING{1c8} AssignConst '8'<864> STRIDE{588}; 
251e:STRING{1c8} Length '8'<864> Divide @RESIDUE{268} AssignConst 
2527:'1'<ec> CURSOR{590}; RepEver[2564]; RESIDUE{268} '0'<c4> 
2532:Bool Gt While STRING{1c8} CURSOR{590} STRIDE{588} BifSUBSTR3 
253d:@PIECE{598} CURSOR{590} STRIDE{588} Add @CURSOR{590} STREAM{568} 
2548:PIECE{598} Call "CONFIG_CHAROUT"<924>; !THIS_EXCEPTION{580} 
254f:"READY"<8fc> Sne[255c] !THIS_EXCEPTION{580} Call "!RAISE"<3c4>; 
2559:"1"<e4> Returns; RESIDUE{268} '1'<ec> Subtract @RESIDUE{268} 
2563:Iterate; "0"<a4> Returns; "oANY oCNI"<974> Call "CHECKARGS"<d4>; 
256c:"1"<e4> Dots(0) !BIF_ARGEXISTS.{98} Then[2580]; "1"<e4> 
2577:Dots(0) !BIF_ARG.{88} @STREAM{568} Jump[2585] AssignConst 
2581:""<ac> STREAM{568}; "2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} 
258b:Then[2599]; "2"<2a4> Dots(0) !BIF_ARG.{88} @OPTION{308} 
2596:Jump[259e] AssignConst "N"<154> OPTION{308}; STREAM{568} 
25a0:"LINEIN"<94c> OPTION{308} Call "CONFIG_STREAMCOUNT"<93c>; 
25a7:!OUTCOME{2f8} Returns; "oANY"<984> Call "CHECKARGS"<d4>; 
25af:"1"<e4> Dots(0) !BIF_ARGEXISTS.{98} Then[25c3]; "1"<e4> 
25ba:Dots(0) !BIF_ARG.{88} @STREAM{568} Jump[25c8] AssignConst 
25c4:""<ac> STREAM{568}; STREAM{568} Invoke(1) "CONFIG_QUALIFIED_NAME"<98c> 
25ce:@INDICATION{2f0} !OUTCOME{2f8} Returns; "2"<2a4> Dots(0) 
25d7:!BIF_ARGEXISTS.{98} "2"<2a4> Dots(0) !BIF_ARG.{88} '1'<ec> 
25e1:BifqLEFT2 BifqTRANSLATE1 "C"<75c> Bool Seq And Then[25f5]; 
25ed:AssignConst "rANY rCDS rANY"<99c> ARGDATA{460}; Jump[25fa] 
25f5:AssignConst "rANY oCDS"<9a4> ARGDATA{460}; ARGDATA{460} 
25fc:Call "CHECKARGS"<d4>; "1"<e4> Dots(0) !BIF_ARG.{88} @STREAM{568} 
2607:"2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} Then[261b]; "2"<2a4> 
2612:Dots(0) !BIF_ARG.{88} @OPERATION{5b8} Jump[2620] AssignConst 
261c:"S"<24c> OPERATION{5b8}; OPERATION{5b8} "C"<75c> Seq[2638] 
2627:STREAM{568} "3"<2bc> Dots(0) !BIF_ARG.{88} Call "CONFIG_STREAMCOMMAND"<9ac
>; !OUTCOME{2f8} Returns; Jump[265e] OPERATION{5b8} "D"<764> 
263c:Seq[264a] STREAM{568} Call "CONFIG_STREAMSTATE"<9b4>; !DESCRIPTION{5c0} 
2646:Returns; Jump[265e] OPERATION{5b8} "S"<24c> Seq[265c] STREAM{568} 
2653:Call "CONFIG_STREAMSTATE"<9b4>; !THIS_EXCEPTION{580} Returns; 
2659:Jump[265e] Raise(0) "oBDEMNOSUW oANY oBDENOSU"<9c4> Call 
2661:"CHECKARGS"<d4>; "3"<2bc> Dots(0) !BIF_ARGEXISTS.{98} "2"<2a4> 
266b:Dots(0) !BIF_ARGEXISTS.{98} Not And Then[2681]; "40.19"<9cc> 
2676:""<ac> "3"<2bc> Dots(0) !BIF_ARG.{88} Call "RAISE"<114>; 
2681:"1"<e4> Dots(0) !BIF_ARGEXISTS.{98} Then[2695]; "1"<e4> 
268c:Dots(0) !BIF_ARG.{88} @OPTION{308} Jump[269a] AssignConst 
2696:"N"<154> OPTION{308}; !LEVEL{e8} Dots(0) !CLAUSETIME.{5c8} 
26a0:""<ac> Seq[26bc] Invoke(0) "CONFIG_TIME"<9d4> @!RESPONSE{5d8} 
26ab:!TIME{5e0} !LEVEL{e8} AssignDots !CLAUSETIME.{5c8}; !TIME{5e0} 
26b4:!ADJUST{5e8} Add !LEVEL{e8} AssignDots !CLAUSELOCAL.{5f0}; 
26bc:"January February March April May June July"<9dc> "
August September October November December"<9e4> Cat @MONTHS{600} 
26c3:AssignConst "Monday Tuesday Wednesday Thursday Friday Saturday Sunday"<9ec
> WEEKDAYS{608}; "2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} Not Then[26df]; 
26d2:!LEVEL{e8} Dots(0) !CLAUSELOCAL.{5f0} OPTION{308} Invoke(2) 
26dc:"DATEFORMAT"<9f4> Returns; "2"<2a4> Dots(0) !BIF_ARG.{88} 
26e5:@VALUE{a8} "3"<2bc> Dots(0) !BIF_ARGEXISTS.{98} Then[26fb]; 
26f0:"3"<2bc> Dots(0) !BIF_ARG.{88} @INOPTION{610} Jump[2700] 
26fb:AssignConst "N"<154> INOPTION{610}; AssignConst "NS"<9fc> 
2703:LOGIC{618}; INOPTION{610} "N"<154> Seq[2737] VALUE{a8} Parse(0) 
2710:(PosRest) @DAY{168} @MONTHIS{620} @YEAR{178} (ParseEnd) 
2718:'1'<ec> Number '12'<a0c> To ControlVar MONTH{190}[2734]; 
2723:MONTHS{600} MONTH{190} BifWORD2 '3'<2c4> BifqLEFT2 MONTHIS{620} 
272f:Seq[2733] Leave; IterCV; Jump[2758] INOPTION{610} "S"<24c> 
273b:Seq[2753] VALUE{a8} Parse(0) '4'<2fc> (PosPlus) @YEAR{178} 
2747:'2'<2ac> (PosPlus) @MONTH{190} (PosRest) @DAY{168} (ParseEnd) 
2750:Jump[2758] AssignConst "EOU"<a14> LOGIC{618}; LOGIC{618} 
275a:"EOU"<a14> Ceq[27b8] INOPTION{610} "E"<15c> Seq[277b] VALUE{a8} 
2768:Parse(0) "/"<a1c> (Pattern) @DAY{168} "/"<a1c> (Pattern) 
2772:@MONTH{190} (PosRest) @YY{628} (ParseEnd) Jump[27b8] INOPTION{610} 
277d:"O"<744> Seq[2797] VALUE{a8} Parse(0) "/"<a1c> (Pattern) 
2789:@YY{628} "/"<a1c> (Pattern) @MONTH{190} (PosRest) @DAY{168} 
2793:(ParseEnd) Jump[27b8] INOPTION{610} "U"<4ac> Seq[27b3] VALUE{a8} 
27a0:Parse(0) "/"<a1c> (Pattern) @MONTH{190} "/"<a1c> (Pattern) 
27aa:@DAY{168} (PosRest) @YY{628} (ParseEnd) Jump[27b8] AssignConst 
27b4:"BD"<a24> LOGIC{618}; LOGIC{618} "EOU"<a14> Ceq[27ff] YY{628} 
27c1:"W"<184> Invoke(2) "DATATYPE"<214> Not Then[27d4]; "40.19"<9cc> 
27cd:VALUE{a8} INOPTION{610} Call "RAISE"<114>; !LEVEL{e8} Dots(0) 
27d8:!CLAUSELOCAL.{5f0} Invoke(1) "TIME2DATE"<304> Parse(2) (PosRest) 
27e1:@YEARNOW{630} @.{10} (ParseEnd) YY{628} @YEAR{178} RepEver[27ff]; 
27ed:YEAR{178} YEARNOW{630} '50'<a34> Subtract Bool Lt While 
27f7:YEAR{178} '100'<384> Add @YEAR{178} Iterate; LOGIC{618} 
2801:"BD"<a24> Cne[284e] MONTH{190} "W"<184> Invoke(2) "DATATYPE"<214> 
280e:Not DAY{168} "W"<184> Invoke(2) "DATATYPE"<214> Not Or YEAR{178} 
281b:"W"<184> Invoke(2) "DATATYPE"<214> Not Or Then[282f]; "40.19"<9cc> 
2828:VALUE{a8} INOPTION{610} Call "RAISE"<114>; "
0 31 59 90 120 151 181 212 243 273 304 334"<a3c> MONTH{190} BifWORD2 
2835:MONTH{190} '2'<2ac> Bool Gt YEAR{178} Invoke(1) "LEAP"<39c> 
2841:Multiply Add DAY{168} Add '1'<ec> Subtract @DAYS{188} Jump[2863] 
284e:VALUE{a8} "W"<184> Invoke(2) "DATATYPE"<214> Not Then[2863]; 
285a:"40.19"<9cc> VALUE{a8} INOPTION{610} Call "RAISE"<114>; 
2863:INOPTION{610} "D"<764> Seq[2883] !LEVEL{e8} Dots(0) !CLAUSELOCAL.{5f0} 
2870:Invoke(1) "TIME2DATE"<304> Parse(2) (PosRest) @YEAR{178} 
2879:@.{10} (ParseEnd) VALUE{a8} '1'<ec> Subtract @DAYS{188} 
2883:INOPTION{610} "B"<234> Sne[28b5] YEAR{178} '1'<ec> Subtract 
288f:'365'<374> Multiply YEAR{178} '1'<ec> Subtract '4'<2fc> 
2899:IntDivide Add YEAR{178} '1'<ec> Subtract '100'<384> IntDivide 
28a3:Subtract YEAR{178} '1'<ec> Subtract '400'<394> IntDivide 
28ac:Add DAYS{188} Add @BASEDAYS{170} Jump[28b9] VALUE{a8} @BASEDAYS{170} 
28b9:BASEDAYS{170} '86400'<a4c> Multiply '1000000'<334> Multiply 
28c1:@MICRO{638} Unstore INOPTION{610} Invoke(2) "DATEFORMAT"<9f4> 
28ca:VALUE{a8} Sne[28d8] "40.19"<9cc> VALUE{a8} INOPTION{610} 
28d5:Call "RAISE"<114>; MICRO{638} OPTION{308} Invoke(2) "DATEFORMAT"<9f4> 
28e0:Returns; '1'<ec> BifqARG1 Invoke(1) "TIME2DATE"<304> Parse(2) 
28eb:(PosRest) @YEAR{178} @MONTH{190} @DAY{168} @HOUR{160} @MINUTE{158} 
28f6:@SECOND{148} @MICROSECOND{150} @BASE{640} @DAYS{188} (ParseEnd) 
28ff:'2'<2ac> BifqARG1 "B"<234> Seq[290e] BASE{640} Returns; 
290b:Jump[2a0e] '2'<2ac> BifqARG1 "D"<764> Seq[291d] DAYS{188} 
2919:Returns; Jump[2a0e] '2'<2ac> BifqARG1 "E"<15c> Seq[294a] 
2926:DAY{168} '2'<2ac> "0"<a4> BifqRIGHT3 "/"<a1c> Abut MONTH{190} 
2933:'2'<2ac> "0"<a4> BifqRIGHT3 Abut "/"<a1c> Abut YEAR{178} 
293f:'2'<2ac> "0"<a4> BifqRIGHT3 Abut Returns; Jump[2a0e] '2'<2ac> 
294c:BifqARG1 "M"<494> Seq[295d] MONTHS{600} MONTH{190} BifWORD2 
2959:Returns; Jump[2a0e] '2'<2ac> BifqARG1 "N"<154> Seq[2980] 
2966:DAY{168} MONTHS{600} MONTH{190} BifWORD2 '3'<2c4> BifqLEFT2 
2972:Cat YEAR{178} '4'<2fc> "0"<a4> BifqRIGHT3 Cat Returns; Jump[2a0e] 
2980:'2'<2ac> BifqARG1 "O"<744> Seq[29ad] YEAR{178} '2'<2ac> 
298d:"0"<a4> BifqRIGHT3 "/"<a1c> Abut MONTH{190} '2'<2ac> "0"<a4> 
299a:BifqRIGHT3 Abut "/"<a1c> Abut DAY{168} '2'<2ac> "0"<a4> 
29a6:BifqRIGHT3 Abut Returns; Jump[2a0e] '2'<2ac> BifqARG1 "S"<24c> 
29b3:Seq[29d4] YEAR{178} '4'<2fc> "0"<a4> BifqRIGHT3 MONTH{190} 
29c0:'2'<2ac> "0"<a4> BifqRIGHT3 Abut DAY{168} '2'<2ac> "0"<a4> 
29cd:BifqRIGHT3 Abut Returns; Jump[2a0e] '2'<2ac> BifqARG1 "U"<4ac> 
29da:Seq[2a01] MONTH{190} '2'<2ac> "0"<a4> BifqRIGHT3 "/"<a1c> 
29e7:Abut DAY{168} '2'<2ac> "0"<a4> BifqRIGHT3 Abut "/"<a1c> 
29f3:Abut YEAR{178} '2'<2ac> "0"<a4> BifqRIGHT3 Abut Returns; 
29fe:Jump[2a0e] WEEKDAYS{608} '1'<ec> BASE{640} '7'<a5c> Remainder 
2a0a:Add BifWORD2 Returns; Return; ""<ac> Call "CHECKARGS"<d4>; 
2a14:Invoke(0) "CONFIG_QUEUED"<a6c> @INDICATION{2f0} !OUTCOME{2f8} 
2a1c:Returns; "oWHOLE>=0 oWHOLE>=0 oWHOLE>=0"<a7c> Call "CHECKARGS"<d4>; 
2a22:"0"<a4> Dots(0) !BIF_ARG.{88} '1'<ec> Eq[2a4a] AssignConst 
2a2e:'0'<c4> MINIMUM{648}; "1"<e4> Dots(0) !BIF_ARG.{88} @MAXIMUM{650} 
2a3a:Unstore '100000'<a8c> Gt[2a47] "40.31"<a94> MAXIMUM{650} 
2a44:Call "RAISE"<114>; Jump[2a7c] "1"<e4> Dots(0) !BIF_ARGEXISTS.{98} 
2a50:Then[2a5e]; "1"<e4> Dots(0) !BIF_ARG.{88} @MINIMUM{648} 
2a5b:Jump[2a63] AssignConst '0'<c4> MINIMUM{648}; "2"<2a4> Dots(0) 
2a67:!BIF_ARGEXISTS.{98} Then[2a77]; "2"<2a4> Dots(0) !BIF_ARG.{88} 
2a72:@MAXIMUM{650} Jump[2a7c] AssignConst '999'<aa4> MAXIMUM{650}; 
2a7c:MAXIMUM{650} MINIMUM{648} Subtract '100000'<a8c> Gt[2a8f] 
2a86:"40.32"<aac> MINIMUM{648} MAXIMUM{650} Call "RAISE"<114>; 
2a8f:MAXIMUM{650} MINIMUM{648} Subtract '0'<c4> Lt[2aa2] "40.33"<ab4> 
2a9b:MINIMUM{648} MAXIMUM{650} Call "RAISE"<114>; "3"<2bc> Dots(0) 
2aa6:!BIF_ARGEXISTS.{98} Then[2ab4]; "3"<2bc> Dots(0) !BIF_ARG.{88} 
2ab1:Call "CONFIG_RANDOM_SEED"<abc>; MINIMUM{648} MAXIMUM{650} 
2ab8:Call "CONFIG_RANDOM_NEXT"<ac4>; !OUTCOME{2f8} Returns; "
oCEHLMNORS oANY oCHLMNS"<adc> Call "CHECKARGS"<d4>; "3"<2bc> 
2ac5:Dots(0) !BIF_ARGEXISTS.{98} "2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} 
2acf:Not And Then[2ae1]; "40.19"<9cc> ""<ac> "3"<2bc> Dots(0) 
2adc:!BIF_ARG.{88} Call "RAISE"<114>; "1"<e4> Dots(0) !BIF_ARGEXISTS.{98} 
2ae7:Then[2af5]; "1"<e4> Dots(0) !BIF_ARG.{88} @OPTION{308} Jump[2afa] 
2af5:AssignConst "N"<154> OPTION{308}; !LEVEL{e8} Dots(0) !CLAUSETIME.{5c8} 
2b00:""<ac> Seq[2b1c] Invoke(0) "CONFIG_TIME"<9d4> @!RESPONSE{5d8} 
2b0b:!TIME{5e0} !LEVEL{e8} AssignDots !CLAUSETIME.{5c8}; !TIME{5e0} 
2b14:!ADJUST{5e8} Add !LEVEL{e8} AssignDots !CLAUSELOCAL.{5f0}; 
2b1c:"2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} Not Then[2b33]; !LEVEL{e8} 
2b28:Dots(0) !CLAUSELOCAL.{5f0} OPTION{308} Invoke(2) "TIMEFORMAT"<ae4> 
2b32:Returns; OPTION{308} "ERO"<aec> BifqPOS2 '0'<c4> Gt[2b45] 
2b3e:"40.29"<af4> OPTION{308} Call "RAISE"<114>; "2"<2a4> Dots(0) 
2b49:!BIF_ARG.{88} @INVALUE{658} "3"<2bc> Dots(0) !BIF_ARGEXISTS.{98} 
2b53:Then[2b61]; "3"<2bc> Dots(0) !BIF_ARG.{88} @INOPTION{610} 
2b5e:Jump[2b66] AssignConst "N"<154> INOPTION{610}; AssignConst 
2b67:'0'<c4> HH{660}; AssignConst '0'<c4> MM{668}; AssignConst 
2b71:'0'<c4> SS{670}; AssignConst '0'<c4> HOURADJUST{678}; INOPTION{610} 
2b7c:"C"<75c> Seq[2bb3] INVALUE{658} Parse(0) ":"<afc> (Pattern) 
2b88:@HH{660} '1'<ec> (PosPlus) @.{10} '2'<2ac> (PosPlus) @MM{668} 
2b94:(PosRest) @XX{680} (ParseEnd) HH{660} '12'<a0c> Eq[2ba4] 
2b9f:AssignConst '0'<c4> HH{660}; XX{680} "pm"<b04> Seq[2bb0] 
2bab:AssignConst '12'<a0c> HOURADJUST{678}; Jump[2bf8] INOPTION{610} 
2bb5:"H"<b0c> Seq[2bc1] INVALUE{658} @HH{660} Jump[2bf8] INOPTION{610} 
2bc3:"L"<27c> Bool Seq INOPTION{610} "N"<154> Bool Seq Or When[2be6]; 
2bd1:INVALUE{658} Parse(0) ":"<afc> (Pattern) @HH{660} ":"<afc> 
2bdc:(Pattern) @MM{668} (PosRest) @SS{670} (ParseEnd) Jump[2bf8] 
2be6:INOPTION{610} "M"<494> Seq[2bf4] INVALUE{658} @MM{668} Jump[2bf8] 
2bf4:INVALUE{658} @SS{670} HH{660} "W"<184> Invoke(2) "DATATYPE"<214> 
2c00:Not MM{668} "W"<184> Invoke(2) "DATATYPE"<214> Not Or SS{670} 
2c0d:"N"<154> Invoke(2) "DATATYPE"<214> Not Or Then[2c21]; "40.19"<9cc> 
2c1a:INVALUE{658} INOPTION{610} Call "RAISE"<114>; HH{660} HOURADJUST{678} 
2c25:Add @HH{660} Unstore '60'<344> Multiply MM{668} Add '60'<344> 
2c31:Multiply SS{670} Add '1000000'<334> Multiply BifTRUNC1 @MICRO{638} 
2c3c:Unstore INOPTION{610} Invoke(2) "TIMEFORMAT"<ae4> INVALUE{658} 
2c45:Sne[2c51] "40.19"<9cc> INVALUE{658} INOPTION{610} Call "RAISE"<114>; 
2c51:MICRO{638} OPTION{308} Invoke(2) "TIMEFORMAT"<ae4> Returns; 
2c5a:'1'<ec> BifqARG1 Invoke(1) "TIME2DATE"<304> Parse(2) (PosRest) 
2c65:@YEAR{178} @MONTH{190} @DAY{168} @HOUR{160} @MINUTE{158} 
2c6f:@SECOND{148} @MICROSECOND{150} @BASE{640} @DAYS{188} (ParseEnd) 
2c78:'2'<2ac> BifqARG1 "C"<75c> Seq[2cf3] HOUR{160} '12'<a0c> 
2c85:Gt[2ca0] HOUR{160} '12'<a0c> Subtract ":"<afc> Abut MINUTE{158} 
2c92:'2'<2ac> "0"<a4> BifqRIGHT3 Abut "pm"<b04> Abut Returns; 
2c9d:Jump[2cf0] HOUR{160} '12'<a0c> Eq[2cb9] "12:"<b1c> MINUTE{158} 
2cab:'2'<2ac> "0"<a4> BifqRIGHT3 Abut "pm"<b04> Abut Returns; 
2cb6:Jump[2cf0] HOUR{160} '0'<c4> Gt[2cd5] HOUR{160} ":"<afc> 
2cc4:Abut MINUTE{158} '2'<2ac> "0"<a4> BifqRIGHT3 Abut "am"<b24> 
2cd0:Abut Returns; Jump[2cf0] HOUR{160} '0'<c4> Eq[2cee] "12:"<b1c> 
2cde:MINUTE{158} '2'<2ac> "0"<a4> BifqRIGHT3 Abut "am"<b24> Abut 
2cea:Returns; Jump[2cf0] Raise(0) Jump[2e04] '2'<2ac> BifqARG1 
2cf7:"E"<15c> Bool Seq '2'<2ac> BifqARG1 "R"<b2c> Bool Seq Or 
2d04:When[2d4c]; !LEVEL{e8} Dots(0) !STARTTIME.{688} ""<ac> Seq[2d20] 
2d12:!LEVEL{e8} Dots(0) !CLAUSETIME.{5c8} !LEVEL{e8} AssignDots 
2d1b:!STARTTIME.{688}; "0"<a4> Returns; !LEVEL{e8} Dots(0) !CLAUSETIME.{5c8} 
2d26:!LEVEL{e8} Dots(0) !STARTTIME.{688} Subtract @OUTPUT{1e0} 
2d2f:'2'<2ac> BifqARG1 "R"<b2c> Seq[2d43] !LEVEL{e8} Dots(0) 
2d3c:!CLAUSETIME.{5c8} !LEVEL{e8} AssignDots !STARTTIME.{688}; 
2d43:OUTPUT{1e0} '1E-6'<b3c> Multiply Returns; Jump[2e04] '2'<2ac> 
2d4e:BifqARG1 "H"<b0c> Seq[2d5b] HOUR{160} Returns; Jump[2e04] 
2d5b:'2'<2ac> BifqARG1 "L"<27c> Seq[2d94] HOUR{160} '2'<2ac> 
2d68:"0"<a4> BifqRIGHT3 ":"<afc> Abut MINUTE{158} '2'<2ac> "0"<a4> 
2d75:BifqRIGHT3 Abut ":"<afc> Abut SECOND{148} '2'<2ac> "0"<a4> 
2d81:BifqRIGHT3 Abut "."<4d4> Abut MICROSECOND{150} '6'<69c> 
2d8b:"0"<a4> BifqRIGHT3 Abut Returns; Jump[2e04] '2'<2ac> BifqARG1 
2d98:"M"<494> Seq[2da9] '60'<344> HOUR{160} Multiply MINUTE{158} 
2da4:Add Returns; Jump[2e04] '2'<2ac> BifqARG1 "N"<154> Seq[2dd6] 
2db2:HOUR{160} '2'<2ac> "0"<a4> BifqRIGHT3 ":"<afc> Abut MINUTE{158} 
2dbf:'2'<2ac> "0"<a4> BifqRIGHT3 Abut ":"<afc> Abut SECOND{148} 
2dcb:'2'<2ac> "0"<a4> BifqRIGHT3 Abut Returns; Jump[2e04] '2'<2ac> 
2dd8:BifqARG1 "O"<744> Seq[2df5] !LEVEL{e8} Dots(0) !CLAUSELOCAL.{5f0} 
2de5:!LEVEL{e8} Dots(0) !CLAUSETIME.{5c8} Subtract '1E+6'<b4c> 
2dee:Divide BifTRUNC1 Returns; Jump[2e04] '3600'<b5c> HOUR{160} 
2df9:Multiply '60'<344> MINUTE{158} Multiply Add SECOND{148} 
2e02:Add Returns; "3"<2bc> Dots(0) !BIF_ARGEXISTS.{98} Then[2e15]; 
2e0d:AssignConst "rANY oANY oANY"<b6c> ARGDATA{460}; Jump[2e1a] 
2e15:AssignConst "rSYM oANY oANY"<b74> ARGDATA{460}; ARGDATA{460} 
2e1c:Call "CHECKARGS"<d4>; "1"<e4> Dots(0) !BIF_ARG.{88} @SUBJECT{118} 
2e27:"3"<2bc> Dots(0) !BIF_ARGEXISTS.{98} Then[2e9f]; "3"<2bc> 
2e32:Dots(0) !BIF_ARG.{88} @POOL{698} Unstore SUBJECT{118} Invoke(2) 
2e3d:"CONFIG_GET"<b7c> @INDICATION{2f0} Unstore '1'<ec> BifqLEFT2 
2e46:@INDICATOR{6a0} Unstore "F"<87c> Seq[2e55] "40.36"<b84> 
2e50:SUBJECT{118} Call "RAISE"<114>; INDICATOR{6a0} "P"<724> 
2e59:Seq[2e63] "40.37"<b8c> POOL{698} Call "RAISE"<114>; !OUTCOME{2f8} 
2e65:@VALUE{a8} "2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} Then[2e9c]; 
2e70:POOL{698} SUBJECT{118} "2"<2a4> Dots(0) !BIF_ARG.{88} Invoke(3) 
2e7c:"CONFIG_SET"<b94> @INDICATION{2f0} INDICATOR{6a0} "P"<724> 
2e84:Seq[2e8e] "40.37"<b8c> POOL{698} Call "RAISE"<114>; INDICATOR{6a0} 
2e90:"F"<87c> Seq[2e9c] "40.36"<b84> SUBJECT{118} Call "RAISE"<114>; 
2e9c:VALUE{a8} Returns; SUBJECT{118} BifqTRANSLATE1 @SUBJECT{118} 
2ea5:Unstore "."<4d4> BifqPOS2 @P{6a8} Unstore '0'<c4> Bool Eq 
2eb1:P{6a8} SUBJECT{118} Length Bool Eq Or Then[2eea]; !POOL{6b0} 
2ebe:SUBJECT{118} "0"<a4> Invoke(3) "VAR_VALUE"<b9c> @INDICATION{2f0} 
2ec8:!OUTCOME{2f8} @VALUE{a8} "2"<2a4> Dots(0) !BIF_ARGEXISTS.{98} 
2ed2:Then[2ee7]; !POOL{6b0} SUBJECT{118} "0"<a4> "2"<2a4> Dots(0) 
2edf:!BIF_ARG.{88} Invoke(4) "VAR_SET"<ba4> @INDICATION{2f0} 
2ee7:VALUE{a8} Returns; SUBJECT{118} P{6a8} '1'<ec> Subtract 
2ef1:BifLEFT2 @EXPANDED{6b8} RepEver[2f51]; P{6a8} '1'<ec> Add 
2efd:@START{2e0} SUBJECT{118} "."<4d4> START{2e0} BifPOS3 @P{6a8} 
2f09:Unstore '0'<c4> Eq[2f14] SUBJECT{118} Length @P{6a8} SUBJECT{118} 
2f16:START{2e0} P{6a8} START{2e0} Subtract BifSUBSTR3 @ITEM{6c0} 
2f21:Unstore ""<ac> Sne[2f46] ITEM{6c0} '1'<ec> BifqLEFT2 "0123456789"<474> 
2f2f:BifqPOS2 '0'<c4> Eq[2f46] !POOL{6b0} ITEM{6c0} "0"<a4> Invoke(3) 
2f3e:"VAR_VALUE"<b9c> @INDICATION{2f0} !OUTCOME{2f8} @ITEM{6c0} 
2f46:EXPANDED{6b8} "."<4d4> Abut ITEM{6c0} Abut @EXPANDED{6b8} 
2f50:Iterate; !POOL{6b0} EXPANDED{6b8} "1"<e4> Invoke(3) "VAR_VALUE"<b9c> 
2f5b:@INDICATION{2f0} !OUTCOME{2f8} @VALUE{a8} "2"<2a4> Dots(0) 
2f65:!BIF_ARGEXISTS.{98} Then[2f7c]; !POOL{6b0} EXPANDED{6b8} 
2f6e:"1"<e4> "2"<2a4> Dots(0) !BIF_ARG.{88} Invoke(4) "VAR_SET"<ba4> 
2f7a:@INDICATION{2f0} VALUE{a8} Returns; '1'<ec> BifqARG1 BifqTRANSLATE1 
2f85:@!OUTCOME{2f8} "N"<154> Returns; '1'<ec> BifqARG1 BifB2X1 
2f90:BifX2C1 @!OUTCOME{2f8} "N"<154> Returns; '1'<ec> BifqARG1 
2f9b:BifqC2X1 BifX2B1 @!OUTCOME{2f8} "N"<154> Returns; '1'<ec> 
2fa6:BifqARG1 @S{6c8} '2'<2ac> BifqARG1 @P{6a8} Unstore S{6c8} 
2fb3:Length Gt[2fbf] AssignConst ""<ac> !OUTCOME{2f8}; "M"<494> 
2fbe:Returns; S{6c8} P{6a8} '1'<ec> BifSUBSTR3 @!OUTCOME{2f8} 
2fc9:"N"<154> Returns; '1'<ec> BifqARG1 Length @!OUTCOME{2f8} 
2fd3:"N"<154> Returns; BifGroupDATE0 @!OUTCOME{2f8} "N"<154> 
2fdc:Returns; '1'<ec> BifqARG1 @STREAMNAME{6d0} Unstore BifSTREAM1 
2fe6:"READY"<8fc> Bool Sne Nop; Then[2ffc]; Nop; AssignConst 
2ff0:""<ac> !OUTCOME{2f8}; AssignConst "NOTREADY"<904> !THIS_EXCEPTION{580}; 
2ff9:"N"<154> Returns; STREAMNAME{6d0} BifCHARIN1 @!OUTCOME{2f8} 
3002:Nop; !OUTCOME{2f8} ""<bcc> Ceq[3018] STREAMNAME{6d0} Dots(0) 
300e:!LINEIN_POSITION.{5a8} '1'<ec> Add STREAMNAME{6d0} AssignDots 
3016:!LINEIN_POSITION.{5a8}; AssignConst "READY"<8fc> !THIS_EXCEPTION{580}; 
301d:"N"<154> Returns; '1'<ec> BifqARG1 @S{6c8} '3'<2c4> BifqARG1 
302a:@P{6a8} '2'<2ac> BifqARG1 "CHARIN"<8d4> Ceq[3049] S{6c8} 
3037:P{6a8} '0'<c4> BifCHARIN3 Result; Nop; P{6a8} S{6c8} AssignDots 
3044:!CHARIN_POSITION.{6d8}; Jump[3094] '2'<2ac> BifqARG1 "LINEIN"<94c> 
304f:Ceq[3066] S{6c8} P{6a8} '0'<c4> BifLINEIN3 Result; Nop; 
305c:P{6a8} S{6c8} AssignDots !LINEIN_POSITION.{5a8}; Jump[3094] 
3066:'2'<2ac> BifqARG1 "CHAROUT"<91c> Ceq[3083] S{6c8} ""<ac> 
3073:P{6a8} BifCHAROUT3 Result; Nop; P{6a8} S{6c8} AssignDots 
307e:!CHAROUT_POSITION.{6e8}; Jump[3094] S{6c8} ""<ac> P{6a8} 
3089:BifLINEOUT3 Result; Nop; P{6a8} S{6c8} AssignDots !LINEOUT_POSITION.{6f8};
 "N"<154> Returns; AssignConst "Done"<bec> !OUTCOME{2f8}; "N"<154> 
309e:Returns; '1'<ec> BifqARG1 "S"<24c> BifSTREAM2 @!OUTCOME{2f8} 
30a9:Nop; '1'<ec> BifqARG1 "D"<764> BifSTREAM2 @!DESCRIPTION{5c0} 
30b4:Nop; "N"<154> Returns; '1'<ec> BifqARG1 @STREAMNAME{6d0} 
30be:Unstore '2'<2ac> BifqARG1 BifCHAROUT2 Result; Nop; AssignConst 
30c8:"READY"<8fc> !THIS_EXCEPTION{580}; "N"<154> Returns; '1'<ec> 
30d1:BifqARG1 @!OUTCOME{2f8} "N"<154> Returns; AssignConst "C"<75c> 
30db:!OUTCOME{2f8}; "N"<154> Returns; '1'<ec> BifqARG1 BifLINEOUT1 
30e6:Result; Nop; "N"<154> Returns; ??{708} @!OUTCOME{2f8} "N"<154> 
30f1:Returns; ??{708} @!OUTCOME{2f8} "N"<154> Returns; ??{708} 
30fb:@!OUTCOME{2f8} "N"<154> Returns; "O"<744> BifqDATE1 "L"<27c> 
3106:BifqTIME1 Cat ''<14> "/:."<c0c> BifqTRANSLATE3 @T{70} Nop; 
3112:T{70} '1'<ec> BifqLEFT2 "0"<a4> Seq[3127] "20"<c14> T{70} 
3121:Abut @T{70} Jump[312e] "19"<c1c> T{70} Abut @T{70} T{70} 
3130:Invoke(1) "DATE2TIME"<c24> @!TIME{5e0} AssignConst '0'<c4> 
3139:!ADJUST{5e8}; "N"<154> Returns; Raise(2) "18"<324> Numeric(0); 
3144:Parse(4) (PosRest) @YEAR{178} @MONTH{190} @DAY{168} @HOUR{160} 
314f:@MINUTE{158} @SECOND{148} @MICROSECOND{150} @.{10} (ParseEnd) 
3158:YEAR{178} '1'<ec> Subtract '365'<374> Multiply YEAR{178} 
3162:'1'<ec> Subtract '4'<2fc> IntDivide Add YEAR{178} '1'<ec> 
316d:Subtract '100'<384> IntDivide Subtract YEAR{178} '1'<ec> 
3176:Subtract '400'<394> IntDivide Add "
0 31 59 90 120 151 181 212 243 273 304 334"<a3c> MONTH{190} BifWORD2 
3181:Add MONTH{190} '2'<2ac> Bool Gt YEAR{178} Invoke(1) "LEAP"<39c> 
318e:Multiply Add DAY{168} Add '1'<ec> Subtract '86400'<a4c> 
3198:Multiply HOUR{160} '3600'<b5c> Multiply Add MINUTE{158} 
31a1:'60'<344> Multiply Add SECOND{148} Add '1000000'<334> Multiply 
31ab:MICROSECOND{150} Add Returns; '0'<c4> '0'<c4> "S"<24c> BifqTIME1 
31b7:BifRANDOM3 Result; Nop; "N"<154> Returns; '1'<ec> BifqARG1 
31c2:'2'<2ac> BifqARG1 BifRANDOM2 @!OUTCOME{2f8} "N"<154> Returns; 
31cd:'1'<ec> BifqARG1 @LB{710} '2'<2ac> BifqARG1 @HB{718} LB{710} 
31db:""<ac> Ceq[31e5] AssignConst "
31e9:Ceq[31f1] AssignConst "ÿ"<c3c> HB{718}; LB{710} HB{718} 
31f5:BifXRANGE2 @!OUTCOME{2f8} "N"<154> Returns; "
Sorry, can't do things that require keeping history from call to call."<c44> 
31fe:Say; Exit; BifqARG0 '1'<ec> Eq[3233] '1'<ec> BifqARG1 Invoke(1) 
320d:"DATATYPE"<214> "NUM"<144> Sne[3217] "CHAR"<4b4> Returns; 
3217:!LEVEL{e8} Dots(0) !DIGITS.{d8} Numeric(0); !LEVEL{e8} Dots(0) 
3223:!FORM.{f0} Numeric(4); '1'<ec> BifqARG1 '0'<c4> Add @!DATATYPERESULT{b8} 
3230:"NUM"<144> Returns; '2'<2ac> BifqARG1 "B"<234> Ceq[3279] 
323c:'1'<ec> BifqARG1 ""<ac> Seq[324b] "1"<e4> Returns; Jump[3279] 
324b:'1'<ec> BifqARG1 '1'<ec> BifqLEFT2 " "<10c> Bool Ceq '1'<ec> 
3259:BifqARG1 '1'<ec> BifqRIGHT2 " "<10c> Bool Ceq Or Then[326a]; 
3267:"0"<a4> Returns; '1'<ec> BifqARG1 '0'<c4> BifqSPACE2 "B"<234> 
3274:Invoke(2) "DATATYPE"<214> Returns; '2'<2ac> BifqARG1 "W"<184> 
327f:Bool Ceq '2'<2ac> BifqARG1 "N"<154> Bool Ceq Or Then[32b5]; 
328d:'1'<ec> BifqARG1 '2'<2ac> BifqARG1 Invoke(2) "DATATYPE"<214> 
3299:Then[32b5]; '1'<ec> BifqARG1 '0'<c4> Add @!DATATYPERESULT{b8} 
32a5:'2'<2ac> BifqARG1 "W"<184> Ceq[32b5] !DATATYPERESULT{b8} 
32b0:'1'<ec> IntDivide @!DATATYPERESULT{b8} '1'<ec> BifqARG1 
32b9:'2'<2ac> BifqARG1 Invoke(2) "DATATYPE"<214> Returns; "999"<a9c> 
32c4:Numeric(0); BifGroupDATE0 '0'<c4> Eq[32d1] "
This version is not conversational"<c4c> Say; Exit; SignalOn(2) 
32d3:"NOVALUE"<c54>; Call "GLOBAL_VARS"<c5c>; Parse(8) (PosRest) 
32db:@!BIF{110} @.{10} (ParseEnd) Parse(8) (PosRest) (ParseEscape) 
32e4:!LEVEL{e8} AssignDotsP !DIGITS.{d8} @.{10} (ParseEnd) Parse(8) 
32ee:(PosRest) (ParseEscape) !LEVEL{e8} AssignDotsP !FORM.{f0} 
32f5:@.{10} (ParseEnd) Parse(8) (PosRest) (ParseEscape) !LEVEL{e8} 
32fe:AssignDotsP !FUZZ.{4f8} @.{10} (ParseEnd) '0'<c4> AssignStem 
3307:!BIF_ARGEXISTS.{98}; ""<ac> AssignStem !BIF_ARG.{88}; Parse(8) 
3310:(PosRest) (ParseEscape) "0"<a4> AssignDotsP !BIF_ARG.{88} 
3317:@.{10} (ParseEnd) '1'<ec> Number "0"<a4> Dots(0) !BIF_ARG.{88} 
3323:To ControlVar J{68}[334b]; Parse(8) (PosRest) (ParseEscape) 
332d:J{68} AssignDotsP !BIF_ARGEXISTS.{98} @.{10} (ParseEnd) 
3335:J{68} Dots(0) !BIF_ARGEXISTS.{98} '1'<ec> Eq[334a] Parse(8) 
3342:(PosRest) (ParseEscape) J{68} AssignDotsP !BIF_ARG.{88} 
3349:(ParseEnd) IterCV; "answer=_"<c64> !BIF{110} Abut "()"<c6c> 
3352:Abut @DYNAMIC{720} !BIF{110} "SOURCELINE"<c74> Ceq[338b] 
335c:""<ac> AssignStem !SOURCELINE.{508}; Parse(8) (Upper) (PosRest) 
3365:(ParseEscape) "0"<a4> AssignDotsP !SOURCELINE.{508} (ParseEnd) 
336c:"0"<a4> Dots(0) !SOURCELINE.{508} Number '1'<ec> Negate 
3376:By '1'<ec> To ControlVar I{210}[338b]; Parse(8) (Upper) 
3382:(PosRest) (ParseEscape) I{210} AssignDotsP !SOURCELINE.{508} 
3389:(ParseEnd) IterCV; "["<c7c> DYNAMIC{720} Abut "]"<c84> Abut 
3393:Say; DYNAMIC{720} Interpret; ANSWER{728} Returns; AssignConst 
339b:""<ac> !DATATYPERESULT{b8}; AssignConst " "<10c> !ALLBLANKS{208}; 
33a4:AssignConst '13'<c94> !POOL{6b0}; AssignConst '999'<aa4> 
33ac:!LIMIT_DIGITS{730}; AssignConst '999999'<ca4> !LIMIT_STRING{738}; 
33b3:AssignConst '250'<cb4> !LIMIT_LITERAL{740}; AssignConst 
33b9:'250'<cb4> !LIMIT_NAME{748}; AssignConst '250'<cb4> !LIMIT_ENVIRONMENTNAME
{750}; AssignConst '9'<cbc> !LIMIT_EXPONENTDIGITS{290}; '777'<ccc> 
33c9:AssignStem !DIGITS.{d8}; AssignConst '99'<cdc> !LEVEL{e8}; 
33d1:'0'<c4> AssignStem !ARGEXISTS.{480}; ""<ac> AssignStem !ARG.{468}; 
33db:'2'<2ac> !LEVEL{e8} "0"<a4> AssignDots !ARGEXISTS.{480}; 
33e4:'1'<ec> !LEVEL{e8} "2"<2a4> AssignDots !ARGEXISTS.{480}; 
33ed:"Whatever"<ce4> !LEVEL{e8} "2"<2a4> AssignDots !ARG.{468}; 
33f6:AssignConst '0'<c4> INDEX{758}; AssignConst ""<ac> CONDITION{760}; 
3400:""<ac> AssignStem !STARTTIME.{688}; ""<ac> AssignStem !CLAUSETIME.{5c8}; 
340a:""<ac> !LEVEL{e8} AssignDots !CONDITION.{490}; ""<ac> !LEVEL{e8} 
3415:AssignDots !CONDITIONDESCRIPTION.{4a0}; ""<ac> !LEVEL{e8} 
341c:AssignDots !CONDITIONINSTRUCTION.{4c0}; ""<ac> !LEVEL{e8} 
3423:AssignDots !CONDITIONSTATE.{4d0}; '9'<cbc> AssignStem !CONFIG_DIGITS.{100}
; BifqTRACE0 !LEVEL{e8} AssignDots !TRACING.{518}; BifqADDRESS0 
3434:!LEVEL{e8} AssignDots !ENV_NAME.{408}; "ECST"<cfc> !LEVEL{e8} 
343d:AssignDots !ENV_SOURCETYPE.{768}; "ECSP"<d04> !LEVEL{e8} 
3444:AssignDots !ENV_SOURCEPOSITION.{778}; "ECSN"<d0c> !LEVEL{e8} 
344b:AssignDots !ENV_SOURCENAME.{788}; "ECDT"<d14> !LEVEL{e8} 
3452:AssignDots !ENV_DESTINATIONTYPE.{798}; "ECDP"<d1c> !LEVEL{e8} 
3459:AssignDots !ENV_DESTINATIONPOSITION.{7a8}; "ECDN"<d24> !LEVEL{e8} 
3460:AssignDots !ENV_DESTINATIONNAME.{7b8}; '1'<ec> AssignStem 
3466:!CHARIN_POSITION.{6d8}; '1'<ec> AssignStem !CHAROUT_POSITION.{6e8}; 
346d:'1'<ec> AssignStem !LINEIN_POSITION.{5a8}; '1'<ec> AssignStem 
3475:!LINEOUT_POSITION.{6f8}; "OFF"<d2c> !LEVEL{e8} ERROR{7d8} 
347d:AssignDots !ENABLING.{7c8}; "OFF"<d2c> !LEVEL{e8} FAILURE{7e0} 
3486:AssignDots !ENABLING.{7c8}; "OFF"<d2c> !LEVEL{e8} HALT{7e8} 
348f:AssignDots !ENABLING.{7c8}; "OFF"<d2c> !LEVEL{e8} NOVALUE{7f0} 
3498:AssignDots !ENABLING.{7c8}; "OFF"<d2c> !LEVEL{e8} NOTREADY{7f8} 
34a1:AssignDots !ENABLING.{7c8}; "OFF"<d2c> !LEVEL{e8} SYNTAX{800} 
34aa:AssignDots !ENABLING.{7c8}; ""<ac> !LEVEL{e8} AssignDots 
34b2:!CONDITION.{490}; ""<ac> !LEVEL{e8} AssignDots !DESCRIPTION.{808}; 
34bb:""<ac> !LEVEL{e8} AssignDots !INSTRUCTION.{818}; ""<ac> 
34c4:!LEVEL{e8} AssignDots !STATE.{828}; "ERROR"<d34> !LEVEL{e8} 
34cd:ERROR{7d8} AssignDots !TRAPNAME.{838}; "FAILURE"<d3c> !LEVEL{e8} 
34d6:FAILURE{7e0} AssignDots !TRAPNAME.{838}; "HALT"<d44> LEVEL{848} 
34df:HALT{7e8} AssignDots !TRAPNAME.{838}; "NOVALUE"<d4c> !LEVEL{e8} 
34e8:NOVALUE{7f0} AssignDots !TRAPNAME.{838}; "NOTREADY"<904> 
34ef:!LEVEL{e8} NOTREADY{7f8} AssignDots !TRAPNAME.{838}; "SYNTAX"<3cc> 
34f8:!LEVEL{e8} SYNTAX{800} AssignDots !TRAPNAME.{838}; ""<ac> 
3501:AssignStem !ERRORTEXT.{4e8}; "
Error <value> running <source>, line <linenumber>:"<d54> "0"<a4> 
3508:"1"<e4> AssignDots !ERRORTEXT.{4e8}; "Error <value> in interactive trace:"
<d5c> "0"<a4> "2"<2a4> AssignDots !ERRORTEXT.{4e8}; "
Interactive trace.  "Trace Off" to end debug. "<d64> "ENTER to continue."<d6c> 
351a:Cat "0"<a4> "3"<2bc> AssignDots !ERRORTEXT.{4e8}; "
Failure during finalization"<d74> "2"<2a4> AssignDots !ERRORTEXT.{4e8}; 
3529:"Failure during finalization: <description>"<d7c> "2"<2a4> 
352d:"1"<e4> AssignDots !ERRORTEXT.{4e8}; "Failure during initialization"<d84> 
3534:"3"<2bc> AssignDots !ERRORTEXT.{4e8}; "
Failure during initialization: <description>"<d8c> "3"<2bc> "1"<e4> 
353f:AssignDots !ERRORTEXT.{4e8}; "Program interrupted"<d94> 
3544:"4"<2f4> AssignDots !ERRORTEXT.{4e8}; "
Program interrupted with HALT condition"<d9c> "4"<2f4> "1"<e4> 
354f:AssignDots !ERRORTEXT.{4e8}; "System resources exhausted"<da4> 
3554:"5"<534> AssignDots !ERRORTEXT.{4e8}; "
System resources exhausted: <description>"<dac> "5"<534> "1"<e4> 
355f:AssignDots !ERRORTEXT.{4e8}; "Unmatched "/*" or quote"<db4> 
3564:"6"<694> AssignDots !ERRORTEXT.{4e8}; "Unmatched comment delimiter ("/*")"
<dbc> "6"<694> "1"<e4> AssignDots !ERRORTEXT.{4e8}; "Unmatched single quote (')
"<dc4> "6"<694> "2"<2a4> AssignDots !ERRORTEXT.{4e8}; "
Unmatched double quote (")"<dcc> "6"<694> "3"<2bc> AssignDots 
3582:!ERRORTEXT.{4e8}; "WHEN or OTHERWISE expected"<dd4> "7"<a54> 
3588:AssignDots !ERRORTEXT.{4e8}; "SELECT on line <linenumber> requires WHEN;"<
ddc> "found "<token>""<de4> Cat "7"<a54> "1"<e4> AssignDots !ERRORTEXT.{4e8}; 
3597:"SELECT on line <linenumber> requires WHEN, OTHERWISE,"<dec> 
3599:"or END; found "<token>""<df4> Cat "7"<a54> "2"<2a4> AssignDots 
35a1:!ERRORTEXT.{4e8}; "All WHEN expressions of SELECT on line <linenumber> are
"<dfc> "false; OTHERWISE expected"<e04> Cat "7"<a54> "3"<2bc> 
35ac:AssignDots !ERRORTEXT.{4e8}; "Unexpected THEN or ELSE"<e0c> 
35b1:"8"<85c> AssignDots !ERRORTEXT.{4e8}; "
THEN has no corresponding IF or WHEN clause"<e14> "8"<85c> "1"<e4> 
35bc:AssignDots !ERRORTEXT.{4e8}; "ELSE has no corresponding THEN clause"<e1c> 
35c1:"8"<85c> "2"<2a4> AssignDots !ERRORTEXT.{4e8}; "
Unexpected WHEN or OTHERWISE"<e24> "9"<9c> AssignDots !ERRORTEXT.{4e8}; 
35cf:"WHEN has no corresponding SELECT"<e2c> "9"<9c> "1"<e4> 
35d5:AssignDots !ERRORTEXT.{4e8}; "OTHERWISE has no corresponding SELECT"<e34> 
35da:"9"<9c> "2"<2a4> AssignDots !ERRORTEXT.{4e8}; "Unexpected or unmatched END
"<e3c> "10"<6f4> AssignDots !ERRORTEXT.{4e8}; "
END has no corresponding DO or SELECT"<e44> "10"<6f4> "1"<e4> 
35ee:AssignDots !ERRORTEXT.{4e8}; "END corresponding to DO on line <linenumber>
"<e4c> "must have a symbol following that matches"<e54> Cat "
the control variable (or no symbol);"<e5c> Cat "found "<token>""<de4> 
35fb:Cat "10"<6f4> "2"<2a4> AssignDots !ERRORTEXT.{4e8}; "
END corresponding to DO on line <linenumber>"<e4c> "
must not have a symbol following it because"<e64> Cat "
there is no control variable;"<e6c> Cat "found "<token>""<de4> 
360d:Cat "10"<6f4> "3"<2bc> AssignDots !ERRORTEXT.{4e8}; "
END corresponding to SELECT on line <linenumber>"<e74> "
must not have a symbol following;"<e7c> Cat "found "<token>""<de4> 
361c:Cat "10"<6f4> "4"<2f4> AssignDots !ERRORTEXT.{4e8}; "
END must not immediately follow THEN"<e84> "10"<6f4> "5"<534> 
362a:AssignDots !ERRORTEXT.{4e8}; "END must not immediately follow ELSE"<e8c> 
362f:"10"<6f4> "6"<694> AssignDots !ERRORTEXT.{4e8}; "
Invalid character in program"<e94> "13"<c8c> AssignDots !ERRORTEXT.{4e8}; 
363d:"Invalid character in program "<character>""<e9c> "('<hex-encoding>'X)"<
ea4> Cat "13"<c8c> "1"<e4> AssignDots !ERRORTEXT.{4e8}; "
Incomplete DO/SELECT/IF"<eac> "14"<eb4> AssignDots !ERRORTEXT.{4e8}; 
3650:"DO instruction requires a matching END"<ebc> "14"<eb4> 
3654:"1"<e4> AssignDots !ERRORTEXT.{4e8}; "
SELECT instruction requires a matching END"<ec4> "14"<eb4> "2"<2a4> 
365f:AssignDots !ERRORTEXT.{4e8}; "THEN requires a following instruction"<ecc> 
3664:"14"<eb4> "3"<2bc> AssignDots !ERRORTEXT.{4e8}; "
ELSE requires a following instruction"<ed4> "14"<eb4> "4"<2f4> 
3671:AssignDots !ERRORTEXT.{4e8}; "Invalid hexadecimal or binary string"<edc> 
3676:"15"<ee4> AssignDots !ERRORTEXT.{4e8}; "
Invalid location of blank in position"<eec> "<position> in hexadecimal string"<
ef4> Cat "15"<ee4> "1"<e4> AssignDots !ERRORTEXT.{4e8}; "
Invalid location of blank in position"<eec> "<position> in binary string"<efc> 
368b:Cat "15"<ee4> "2"<2a4> AssignDots !ERRORTEXT.{4e8}; "
Only 0-9, a-f, A-F, and blank are valid in a"<f04> "
hexadecimal string; found "<char>""<f0c> Cat "15"<ee4> "3"<2bc> 
369c:AssignDots !ERRORTEXT.{4e8}; "Only 0, 1, and blank are valid in a"<f14> 
36a1:"binary string; found "<char>""<f1c> Cat "15"<ee4> "4"<2f4> 
36a8:AssignDots !ERRORTEXT.{4e8}; "Label not found"<f24> "16"<2dc> 
36af:AssignDots !ERRORTEXT.{4e8}; "Label "<name>" not found"<f2c> 
36b4:"16"<2dc> "1"<e4> AssignDots !ERRORTEXT.{4e8}; "
Cannot SIGNAL to label "<name>" because it is"<f34> "
inside an IF, SELECT or DO group"<f3c> Cat "16"<2dc> "2"<2a4> 
36c4:AssignDots !ERRORTEXT.{4e8}; "Cannot invoke label "<name>" because it is"<
f44> "inside an IF, SELECT or DO group"<f3c> Cat "16"<2dc> "3"<2bc> 
36d0:AssignDots !ERRORTEXT.{4e8}; "Unexpected PROCEDURE"<f4c> 
36d5:"17"<f54> AssignDots !ERRORTEXT.{4e8}; "
PROCEDURE is valid only when it is the first"<f5c> "
instruction executed after an internal CALL"<f64> Cat "or function invocation"<
f6c> Cat "17"<f54> "1"<e4> AssignDots !ERRORTEXT.{4e8}; "THEN expected"<f74> 
36eb:"18"<324> AssignDots !ERRORTEXT.{4e8}; "
IF keyword on line <linenumber> requires"<f7c> "
matching THEN clause; found "<token>""<f84> Cat "18"<324> "1"<e4> 
36f9:AssignDots !ERRORTEXT.{4e8}; "WHEN keyword on line <linenumber> requires"<
f8c> "matching THEN clause; found "<token>""<f84> Cat "18"<324> 
3703:"2"<2a4> AssignDots !ERRORTEXT.{4e8}; "String or symbol expected"<f94> 
370a:"19"<c1c> AssignDots !ERRORTEXT.{4e8}; "
String or symbol expected after ADDRESS keyword;"<f9c> "found "<token>""<de4> 
3713:Cat "19"<c1c> "1"<e4> AssignDots !ERRORTEXT.{4e8}; "
String or symbol expected after CALL keyword;"<fa4> "found "<token>""<de4> 
371f:Cat "19"<c1c> "2"<2a4> AssignDots !ERRORTEXT.{4e8}; "
String or symbol expected after NAME keyword;"<fac> "found "<token>""<de4> 
372b:Cat "19"<c1c> "3"<2bc> AssignDots !ERRORTEXT.{4e8}; "
String or symbol expected after SIGNAL keyword;"<fb4> "found "<token>""<de4> 
3737:Cat "19"<c1c> "4"<2f4> AssignDots !ERRORTEXT.{4e8}; "
String or symbol expected after TRACE keyword;"<fbc> "found "<token>""<de4> 
3743:Cat "19"<c1c> "6"<694> AssignDots !ERRORTEXT.{4e8}; "
Symbol expected in parsing pattern;"<fc4> "found "<token>""<de4> 
374f:Cat "19"<c1c> "7"<a54> AssignDots !ERRORTEXT.{4e8}; "Name expected"<fcc> 
3759:"20"<c14> AssignDots !ERRORTEXT.{4e8}; "Name required; found "<token>""<
fd4> "20"<c14> "1"<e4> AssignDots !ERRORTEXT.{4e8}; "
Found "<token>" where only a name is valid"<fdc> "20"<c14> "2"<2a4> 
376d:AssignDots !ERRORTEXT.{4e8}; "Invalid data on end of clause"<fe4> 
3772:"21"<fec> AssignDots !ERRORTEXT.{4e8}; "
The clause ended at an unexpected token;"<ff4> "found "<token>""<de4> 
377b:Cat "21"<fec> "1"<e4> AssignDots !ERRORTEXT.{4e8}; "
Invalid character string"<ffc> "22"<1004> AssignDots !ERRORTEXT.{4e8}; 
378a:"Invalid character string '<hex-encoding>'X"<100c> "22"<1004> 
378e:"1"<e4> AssignDots !ERRORTEXT.{4e8}; "Invalid data string"<1014> 
3795:"23"<101c> AssignDots !ERRORTEXT.{4e8}; "
Invalid data string '<hex-encoding>'X"<1024> "23"<101c> "1"<e4> 
37a0:AssignDots !ERRORTEXT.{4e8}; "Invalid TRACE request"<102c> 
37a5:"24"<34c> AssignDots !ERRORTEXT.{4e8}; "
TRACE request must be one character of"<1034> ""ACEFILNOR"; found "<value>""<
103c> Cat "24"<34c> "1"<e4> AssignDots !ERRORTEXT.{4e8}; "
Invalid sub-keyword found"<1044> "25"<104c> AssignDots !ERRORTEXT.{4e8}; 
37bd:"CALL ON must be followed by one of the"<1054> "
keywords <keywords>; found "<token>""<105c> Cat "25"<104c> "1"<e4> 
37c6:AssignDots !ERRORTEXT.{4e8}; "CALL OFF must be followed by one of the"<
1064> "keywords <keywords>; found "<token>""<105c> Cat "25"<104c> 
37d0:"2"<2a4> AssignDots !ERRORTEXT.{4e8}; "
SIGNAL ON must be followed by one of the"<106c> "
keywords <keywords>; found "<token>""<105c> Cat "25"<104c> "3"<2bc> 
37de:AssignDots !ERRORTEXT.{4e8}; "SIGNAL OFF must be followed by one of the"<
1074> "keywords <keywords>; found "<token>""<105c> Cat "25"<104c> 
37e8:"4"<2f4> AssignDots !ERRORTEXT.{4e8}; "
ADDRESS WITH must be followed by one of the"<107c> "
keywords <keywords>; found "<token>""<105c> Cat "25"<104c> "5"<534> 
37f6:AssignDots !ERRORTEXT.{4e8}; "INPUT must be followed by one of the"<1084> 
37fb:"keywords <keywords>; found "<token>""<105c> Cat "25"<104c> 
3800:"6"<694> AssignDots !ERRORTEXT.{4e8}; "
OUTPUT must be followed by one of the"<108c> "
keywords <keywords>; found "<token>""<105c> Cat "25"<104c> "7"<a54> 
380e:AssignDots !ERRORTEXT.{4e8}; "APPEND must be followed by one of the"<1094>
 "keywords <keywords>; found "<token>""<105c> Cat "25"<104c> 
3818:"8"<85c> AssignDots !ERRORTEXT.{4e8}; "
REPLACE must be followed by one of the"<109c> "
keywords <keywords>; found "<token>""<105c> Cat "25"<104c> "9"<9c> 
3826:AssignDots !ERRORTEXT.{4e8}; "NUMERIC FORM must be followed by one of the"
<10a4> "keywords <keywords>; found "<token>""<105c> Cat "25"<104c> 
3830:"11"<10ac> AssignDots !ERRORTEXT.{4e8}; "
PARSE must be followed by one of the"<10b4> "
keywords <keywords>; found "<token>""<105c> Cat "25"<104c> "12"<a04> 
383e:AssignDots !ERRORTEXT.{4e8}; "UPPER must be followed by one of the"<10bc> 
3843:"keywords <keywords>; found "<token>""<105c> Cat "25"<104c> 
3848:"13"<c8c> AssignDots !ERRORTEXT.{4e8}; "
ERROR must be followed by one of the"<10c4> "
keywords <keywords>; found "<token>""<105c> Cat "25"<104c> "14"<eb4> 
3856:AssignDots !ERRORTEXT.{4e8}; "NUMERIC must be followed by one of the"<10cc
> "keywords <keywords>; found "<token>""<105c> Cat "25"<104c> 
3860:"15"<ee4> AssignDots !ERRORTEXT.{4e8}; "
FOREVER must be followed by one of the"<10d4> "
keywords <keywords> or nothing; found "<token>""<10dc> Cat "25"<104c> 
386c:"16"<2dc> AssignDots !ERRORTEXT.{4e8}; "
PROCEDURE must be followed by the keyword"<10e4> "
EXPOSE or nothing; found "<token>""<10ec> Cat "25"<104c> "17"<f54> 
387a:AssignDots !ERRORTEXT.{4e8}; "Invalid whole number"<10f4> 
387f:"26"<10fc> AssignDots !ERRORTEXT.{4e8}; "
Whole numbers must fit within current DIGITS"<1104> "
setting(<value>); found "<value>""<110c> Cat "26"<10fc> "1"<e4> 
388d:AssignDots !ERRORTEXT.{4e8}; "
Value of repetition count expression in DO instruction"<1114> 
3892:"must be zero or a positive whole number;"<111c> Cat "found "<value>""<
1124> Cat "26"<10fc> "2"<2a4> AssignDots !ERRORTEXT.{4e8}; "
Value of FOR expression in DO instruction"<112c> "
must be zero or a positive whole number;"<111c> Cat "found "<value>""<1124> 
38a6:Cat "26"<10fc> "3"<2bc> AssignDots !ERRORTEXT.{4e8}; "
Positional pattern of parsing template"<1134> "
must be a whole number; found "<value>""<113c> Cat "26"<10fc> 
38b5:"4"<2f4> AssignDots !ERRORTEXT.{4e8}; "NUMERIC DIGITS value"<1144> 
38bc:"must be a positive whole number; found "<value>""<114c> 
38be:Cat "26"<10fc> "5"<534> AssignDots !ERRORTEXT.{4e8}; "NUMERIC FUZZ value"<
1154> "must be zero or a positive whole number;"<111c> Cat "found "<value>""<
1124> Cat "26"<10fc> "6"<694> AssignDots !ERRORTEXT.{4e8}; "
Number used in TRACE setting"<115c> "must be a whole number; found "<value>""<
113c> Cat "26"<10fc> "7"<a54> AssignDots !ERRORTEXT.{4e8}; "
Operand to right of the power operator ("**")"<1164> "
must be a whole number; found "<value>""<113c> Cat "26"<10fc> 
38e8:"8"<85c> AssignDots !ERRORTEXT.{4e8}; "
Result of <value> % <value> operation would need"<116c> "
exponential notation at current NUMERIC DIGITS <value>"<1174> 
38f1:Cat "26"<10fc> "11"<10ac> AssignDots !ERRORTEXT.{4e8}; "
Result of % operation used for <value> // <value>"<117c> "operation would need"
<1184> Cat "exponential notation at current NUMERIC DIGITS <value>"<1174> 
3900:Cat "26"<10fc> "12"<a04> AssignDots !ERRORTEXT.{4e8}; "Invalid DO syntax"<
118c> "27"<1194> AssignDots !ERRORTEXT.{4e8}; "
Invalid use of keyword <token> in DO clause"<119c> "27"<1194> 
3913:"1"<e4> AssignDots !ERRORTEXT.{4e8}; "Invalid LEAVE or ITERATE"<11a4> 
391a:"28"<11ac> AssignDots !ERRORTEXT.{4e8}; "
LEAVE is valid only within a repetitive DO loop"<11b4> "28"<11ac> 
3923:"1"<e4> AssignDots !ERRORTEXT.{4e8}; "
ITERATE is valid only within a repetitive DO loop"<11bc> "28"<11ac> 
392c:"2"<2a4> AssignDots !ERRORTEXT.{4e8}; "
Symbol following LEAVE ("<token>") must"<11c4> "
either match control variable of a current"<11cc> Cat "DO loop or be omitted"<
11d4> Cat "28"<11ac> "3"<2bc> AssignDots !ERRORTEXT.{4e8}; "
Symbol following ITERATE ("<token>") must"<11dc> "
either match control variable of a current"<11cc> Cat "DO loop or be omitted"<
11d4> Cat "28"<11ac> "4"<2f4> AssignDots !ERRORTEXT.{4e8}; "
Environment name longer than"<11e4> !LIMIT_ENVIRONMENTNAME{750} 
3953:Cat "characters"<11ec> Cat "29"<11f4> AssignDots !ERRORTEXT.{4e8}; 
395c:"Environment name exceeds"<11fc> !LIMIT_ENVIRONMENTNAME{750} 
3960:Cat "characters "<name>""<1204> Cat "29"<11f4> "1"<e4> AssignDots 
3969:!ERRORTEXT.{4e8}; "Name or string too long"<120c> "30"<1214> 
396f:AssignDots !ERRORTEXT.{4e8}; "Name exceeds"<121c> !LIMIT_NAME{748} 
3976:Cat "characters"<11ec> Cat "30"<1214> "1"<e4> AssignDots 
397f:!ERRORTEXT.{4e8}; "Literal string exceeds"<1224> !LIMIT_LITERAL{740} 
3985:Cat "characters"<11ec> Cat "30"<1214> "2"<2a4> AssignDots 
398e:!ERRORTEXT.{4e8}; "Name starts with number or ".""<122c> 
3992:"31"<1234> AssignDots !ERRORTEXT.{4e8}; "
A value cannot be assigned to a number;"<123c> "found "<token>""<de4> 
399b:Cat "31"<1234> "1"<e4> AssignDots !ERRORTEXT.{4e8}; "
Variable symbol must not start with a number;"<1244> "found "<token>""<de4> 
39a7:Cat "31"<1234> "2"<2a4> AssignDots !ERRORTEXT.{4e8}; "
Variable symbol must not start with a ".";"<124c> "found "<token>""<de4> 
39b3:Cat "31"<1234> "3"<2bc> AssignDots !ERRORTEXT.{4e8}; "
Invalid expression result"<1254> "33"<125c> AssignDots !ERRORTEXT.{4e8}; 
39c2:"Value of NUMERIC DIGITS ("<value>")"<1264> "
must exceed value of NUMERIC FUZZ "(<value>)""<126c> Cat "33"<125c> 
39c9:"1"<e4> AssignDots !ERRORTEXT.{4e8}; "Value of NUMERIC DIGITS ("<value>")"
<1264> "must not exceed"<1274> Cat !LIMIT_DIGITS{730} Cat "33"<125c> 
39d8:"2"<2a4> AssignDots !ERRORTEXT.{4e8}; "
Result of expression following NUMERIC FORM"<127c> "
must start with "E" or "S"; found "<value>""<1284> Cat "33"<125c> 
39e4:"6"<694> AssignDots !ERRORTEXT.{4e8}; "Logical value not "0" or "1""<128c>
 "34"<1294> AssignDots !ERRORTEXT.{4e8}; "
Value of expression following IF keyword"<129c> "
must be exactly "0" or "1"; found "<value>""<12a4> Cat "34"<1294> 
39f7:"1"<e4> AssignDots !ERRORTEXT.{4e8}; "
Value of expression following WHEN keyword"<12ac> "
must be exactly "0" or "1"; found "<value>""<12a4> Cat "34"<1294> 
3a03:"2"<2a4> AssignDots !ERRORTEXT.{4e8}; "
Value of expression following WHILE keyword"<12b4> "
must be exactly "0" or "1"; found "<value>""<12a4> Cat "34"<1294> 
3a0f:"3"<2bc> AssignDots !ERRORTEXT.{4e8}; "
Value of expression following UNTIL keyword"<12bc> "
must be exactly "0" or "1"; found "<value>""<12a4> Cat "34"<1294> 
3a1b:"4"<2f4> AssignDots !ERRORTEXT.{4e8}; "Value of expression to left"<12c4> 
3a22:"of logical operator "<operator>""<12cc> Cat "
must be exactly "0" or "1"; found "<value>""<12a4> Cat "34"<1294> 
3a2a:"5"<534> AssignDots !ERRORTEXT.{4e8}; "Value of expression to right"<12d4>
 "of logical operator "<operator>""<12cc> Cat "
must be exactly "0" or "1"; found "<value>""<12a4> Cat "34"<1294> 
3a39:"6"<694> AssignDots !ERRORTEXT.{4e8}; "Invalid expression"<12dc> 
3a40:"35"<12e4> AssignDots !ERRORTEXT.{4e8}; "
Invalid expression detected at "<token>""<12ec> "35"<12e4> "1"<e4> 
3a4b:AssignDots !ERRORTEXT.{4e8}; "Unmatched "(" in expression"<12f4> 
3a50:"36"<12fc> AssignDots !ERRORTEXT.{4e8}; "Unexpected "," or ")""<1304> 
3a57:"37"<130c> AssignDots !ERRORTEXT.{4e8}; "Unexpected ",""<1314> 
3a5e:"37"<130c> "1"<e4> AssignDots !ERRORTEXT.{4e8}; "
Unmatched ")" in expression"<131c> "37"<130c> "2"<2a4> AssignDots 
3a6c:!ERRORTEXT.{4e8}; "Invalid template or pattern"<1324> "38"<132c> 
3a72:AssignDots !ERRORTEXT.{4e8}; "
Invalid parsing template detected at "<token>""<1334> "38"<132c> 
3a79:"1"<e4> AssignDots !ERRORTEXT.{4e8}; "
Invalid parsing position detected at "<token>""<133c> "38"<132c> 
3a82:"2"<2a4> AssignDots !ERRORTEXT.{4e8}; "
PARSE VALUE instruction requires WITH keyword"<1344> "38"<132c> 
3a8b:"3"<2bc> AssignDots !ERRORTEXT.{4e8}; "Incorrect call to routine"<134c> 
3a92:"40"<1354> AssignDots !ERRORTEXT.{4e8}; "External routine <name> failed"<
135c> "40"<1354> "1"<e4> AssignDots !ERRORTEXT.{4e8}; "
Not enough arguments in invocation of <bif>;"<1364> "
minimum expected is <argnumber>"<136c> Cat "40"<1354> "3"<2bc> 
3aa9:AssignDots !ERRORTEXT.{4e8}; "Too many arguments in invocation of <bif>;"<
1374> "maximum expected is <argnumber>"<137c> Cat "40"<1354> 
3ab3:"4"<2f4> AssignDots !ERRORTEXT.{4e8}; "
Missing argument in invocation of <bif>;"<1384> "
argument <argnumber> is required"<138c> Cat "40"<1354> "5"<534> 
3ac1:AssignDots !ERRORTEXT.{4e8}; "<bif> argument <argnumber>"<1394> 
3ac6:"Exponent exceeds"<139c> Cat !LIMIT_EXPONENTDIGITS{290} 
3acb:Cat "digits"<13a4> Cat "40"<1354> "9"<9c> AssignDots !ERRORTEXT.{4e8}; 
3ad6:"<bif> argument <argnumber>"<1394> "must be a number; found "<value>""<
13ac> Cat "40"<1354> "11"<10ac> AssignDots !ERRORTEXT.{4e8}; 
3ae2:"<bif> argument <argnumber>"<1394> "
must be a whole number; found "<value>""<113c> Cat "40"<1354> 
3ae9:"12"<a04> AssignDots !ERRORTEXT.{4e8}; "<bif> argument <argnumber>"<1394> 
3af0:"must be zero or positive; found "<value>""<13b4> Cat "40"<1354> 
3af5:"13"<c8c> AssignDots !ERRORTEXT.{4e8}; "<bif> argument <argnumber>"<1394> 
3afc:"must be positive; found "<value>""<13bc> Cat "40"<1354> 
3b01:"14"<eb4> AssignDots !ERRORTEXT.{4e8}; "<bif> argument <argnumber>"<1394> 
3b08:"must fit in <value> digits; found "<value>""<13c4> Cat 
3b0b:"40"<1354> "15"<ee4> AssignDots !ERRORTEXT.{4e8}; "
<bif> argument <argnumber>"<1394> "Requires a whole number fitting within"<13cc
> Cat "DIGITS(<value>); found "<value>""<13d4> Cat "40"<1354> 
3b1c:"16"<2dc> AssignDots !ERRORTEXT.{4e8}; "<bif> argument 1"<13dc> 
3b23:"must have an integer part in the range 0:90 and a"<13e4> 
3b25:Cat "decimal part no larger than .9; found "<value>""<13ec> 
3b28:Cat "40"<1354> "17"<f54> AssignDots !ERRORTEXT.{4e8}; "
<bif> conversion must"<13f4> "have a year in the range 0001 to 9999"<13fc> 
3b34:Cat "40"<1354> "18"<324> AssignDots !ERRORTEXT.{4e8}; "
<bif> argument 2, "<value>", is not in the format"<1404> "
described by argument 3, "<value>""<140c> Cat "40"<1354> "19"<c1c> 
3b45:AssignDots !ERRORTEXT.{4e8}; "<bif> argument <argnumber> must not be null"
<1414> "40"<1354> "21"<fec> AssignDots !ERRORTEXT.{4e8}; "
<bif> argument <argnumber>"<1394> "must be a single character or null;"<141c> 
3b55:Cat "found "<value>""<1124> Cat "40"<1354> "22"<1004> AssignDots 
3b5e:!ERRORTEXT.{4e8}; "<bif> argument <argnumber>"<1394> "
must be a single character; found "<value>""<1424> Cat "40"<1354> 
3b67:"23"<101c> AssignDots !ERRORTEXT.{4e8}; "<bif> argument 1"<13dc> 
3b6e:"must be a binary string; found "<value>""<142c> Cat "40"<1354> 
3b73:"24"<34c> AssignDots !ERRORTEXT.{4e8}; "<bif> argument 1"<13dc> 
3b7a:"must be a hexadecimal string; found "<value>""<1434> Cat 
3b7d:"40"<1354> "25"<104c> AssignDots !ERRORTEXT.{4e8}; "<bif> argument 1"<13dc
> "must be a valid symbol; found "<value>""<143c> Cat "40"<1354> 
3b8b:"26"<10fc> AssignDots !ERRORTEXT.{4e8}; "<bif> argument 1"<13dc> 
3b92:"must be a valid stream name; found "<value>""<1444> Cat 
3b95:"40"<1354> "27"<1194> AssignDots !ERRORTEXT.{4e8}; "
<bif> argument <argnumber>"<1394> "must start with one of "<optionslist>";"<
144c> Cat "found "<value>""<1124> Cat "40"<1354> "28"<11ac> AssignDots 
3ba9:!ERRORTEXT.{4e8}; "<bif> conversion to format "<value>" is not allowed"<
1454> "40"<1354> "29"<11f4> AssignDots !ERRORTEXT.{4e8}; "
<bif> argument 1 ("<value>") must not exceed 100000"<145c> "40"<1354> 
3bb8:"31"<1234> AssignDots !ERRORTEXT.{4e8}; "
<bif> the difference between argument 1 ("<value>") and"<1464> 
3bbf:"argument 2 ("<value>") must not exceed 100000"<146c> Cat 
3bc2:"40"<1354> "32"<1474> AssignDots !ERRORTEXT.{4e8}; "
<bif> argument 1 ("<value>") must be less than"<147c> "
or equal to argument 2 ("<value>")"<1484> Cat "40"<1354> "33"<125c> 
3bd2:AssignDots !ERRORTEXT.{4e8}; "
<bif> argument 1 ("<value>") must be less than"<147c> "
or equal to the number of lines"<148c> Cat "in the program (<sourceline()>)"<
1494> Cat "40"<1354> "34"<1294> AssignDots !ERRORTEXT.{4e8}; 
3be4:"<bif> argument 1 cannot be expressed as a whole number;"<149c> 
3be6:"found "<value>""<1124> Cat "40"<1354> "35"<12e4> AssignDots 
3bee:!ERRORTEXT.{4e8}; "<bif> argument 1"<13dc> "
must be the name of a variable in the pool;"<14a4> Cat "found "<value>""<1124> 
3bf7:Cat "40"<1354> "36"<12fc> AssignDots !ERRORTEXT.{4e8}; "<bif> argument 3"<
14ac> "must be the name of a pool; found "<value>""<14b4> Cat 
3c04:"40"<1354> "37"<130c> AssignDots !ERRORTEXT.{4e8}; "
<bif> argument <argnumber>"<1394> "is not large enough to format "<value>""<
14bc> Cat "40"<1354> "38"<132c> AssignDots !ERRORTEXT.{4e8}; 
3c17:"<bif> argument <argnumber>"<1394> "
must be within the bounds of the stream;"<14c4> Cat "found "<value>""<1124> 
3c1e:Cat "40"<1354> "41"<14cc> AssignDots !ERRORTEXT.{4e8}; "
<bif> argument 3 is not zero or one; found "<value>""<14d4> "40"<1354> 
3c2a:"42"<14dc> AssignDots !ERRORTEXT.{4e8}; "Bad arithmetic conversion"<14e4> 
3c31:"41"<14cc> AssignDots !ERRORTEXT.{4e8}; "Non-numeric value ("<value>")"<
14ec> "to left of arithmetic operation "<operator>""<14f4> Cat 
3c3b:"41"<14cc> "1"<e4> AssignDots !ERRORTEXT.{4e8}; "
Non-numeric value ("<value>")"<14ec> "
to right of arithmetic operation "<operator>""<14fc> Cat "41"<14cc> 
3c49:"2"<2a4> AssignDots !ERRORTEXT.{4e8}; "Non-numeric value ("<value>")"<14ec
> "used with prefix operator "<operator>""<1504> Cat "41"<14cc> 
3c55:"3"<2bc> AssignDots !ERRORTEXT.{4e8}; "
Value of TO expression in DO instruction"<150c> "
must be numeric; found "<value>""<1514> Cat "41"<14cc> "4"<2f4> 
3c63:AssignDots !ERRORTEXT.{4e8}; "Value of BY expression in DO instruction"<
151c> "must be numeric; found "<value>""<1514> Cat "41"<14cc> 
3c6d:"5"<534> AssignDots !ERRORTEXT.{4e8}; "
Value of control variable expression of DO instruction"<1524> 
3c74:"must be numeric; found "<value>""<1514> Cat "41"<14cc> 
3c79:"6"<694> AssignDots !ERRORTEXT.{4e8}; "Exponent exceeds"<139c> 
3c80:!LIMIT_EXPONENTDIGITS{290} Cat "digits;"<152c> Cat "found "<value>""<1124>
 Cat "41"<14cc> "7"<a54> AssignDots !ERRORTEXT.{4e8}; "
Arithmetic overflow/underflow"<1534> "42"<14dc> AssignDots !ERRORTEXT.{4e8}; 
3c97:"Arithmetic overflow detected at"<153c> ""<value> <operation> <value>";"<
1544> Cat "exponent of result requires more than"<154c> Cat 
!LIMIT_EXPONENTDIGITS{290} Cat "digits"<13a4> Cat "42"<14dc> 
3ca7:"1"<e4> AssignDots !ERRORTEXT.{4e8}; "Arithmetic underflow detected at"<
1554> ""<value> <operation> <value>";"<1544> Cat "
exponent of result requires more than"<154c> Cat !LIMIT_EXPONENTDIGITS{290} 
3cb6:Cat "digits"<13a4> Cat "42"<14dc> "2"<2a4> AssignDots !ERRORTEXT.{4e8}; 
3cc1:"Arithmetic overflow; divisor must not be zero"<155c> "42"<14dc> 
3cc5:"3"<2bc> AssignDots !ERRORTEXT.{4e8}; "Routine not found"<1564> 
3ccc:"43"<156c> AssignDots !ERRORTEXT.{4e8}; "Could not find routine "<name>""<
1574> "43"<156c> "1"<e4> AssignDots !ERRORTEXT.{4e8}; "
Function did not return data"<157c> "44"<1584> AssignDots !ERRORTEXT.{4e8}; 
3ce1:"No data returned from function "<name>""<158c> "44"<1584> 
3ce5:"1"<e4> AssignDots !ERRORTEXT.{4e8}; "No data specified on function RETURN
"<1594> "45"<159c> AssignDots !ERRORTEXT.{4e8}; "
Data expected on RETURN instruction because"<15a4> "
routine "<name>" was called as a function"<15ac> Cat "45"<159c> 
3cf8:"1"<e4> AssignDots !ERRORTEXT.{4e8}; "Invalid variable reference"<15b4> 
3cff:"46"<15bc> AssignDots !ERRORTEXT.{4e8}; "
Extra token ("<token>") found in variable"<15c4> "reference; ")" expected"<15cc
> Cat "46"<15bc> "1"<e4> AssignDots !ERRORTEXT.{4e8}; "Unexpected label"<15d4> 
3d12:"47"<15dc> AssignDots !ERRORTEXT.{4e8}; "
INTERPRET data must not contain labels;"<15e4> "found "<name>""<15ec> 
3d1b:Cat "47"<15dc> "1"<e4> AssignDots !ERRORTEXT.{4e8}; "
Failure in system service"<15f4> "48"<15fc> AssignDots !ERRORTEXT.{4e8}; 
3d2a:"Failure in system service: <description>"<1604> "48"<15fc> 
3d2e:"1"<e4> AssignDots !ERRORTEXT.{4e8}; "Interpretation Error"<160c> 
3d35:"49"<1614> AssignDots !ERRORTEXT.{4e8}; "
Interpretation Error: <description>"<161c> "49"<1614> "1"<e4> 
3d40:AssignDots !ERRORTEXT.{4e8}; "Unrecognized reserved symbol"<1624> 
3d45:"50"<a2c> AssignDots !ERRORTEXT.{4e8}; "
Unrecognized reserved symbol "<token>""<162c> "50"<a2c> "1"<e4> 
3d50:AssignDots !ERRORTEXT.{4e8}; "Invalid function name"<1634> 
3d55:"51"<163c> AssignDots !ERRORTEXT.{4e8}; "
Unquoted function names must not end with a period;"<1644> "found "<token>""<
de4> Cat "51"<163c> "1"<e4> AssignDots !ERRORTEXT.{4e8}; "
Result returned by <name> is longer than"<164c> !LIMIT_STRING{738} 
3d6a:Cat "characters"<11ec> Cat "52"<1654> AssignDots !ERRORTEXT.{4e8}; 
3d73:"Invalid option"<165c> "53"<1664> AssignDots !ERRORTEXT.{4e8}; 
3d7a:"String or symbol or variable reference expected"<166c> 
3d7c:"after STREAM keyword; found "<token>""<1674> Cat "53"<1664> 
3d81:"1"<e4> AssignDots !ERRORTEXT.{4e8}; "
Symbol or variable reference expected"<167c> "
after STEM keyword; found "<token>""<1684> Cat "53"<1664> "2"<2a4> 
3d8f:AssignDots !ERRORTEXT.{4e8}; "Argument to STEM must have one period,"<168c
> "as its last character; found "<name>""<1694> Cat "53"<1664> 
3d99:"3"<2bc> AssignDots !ERRORTEXT.{4e8}; "Invalid STEM value"<169c> 
3da0:"54"<16a4> AssignDots !ERRORTEXT.{4e8}; "
For this STEM APPEND, the value of "<name>" must be a"<16ac> 
3da7:"count of lines; found: "<value>""<16b4> Cat "54"<16a4> 
3dac:"1"<e4> AssignDots !ERRORTEXT.{4e8}; "0"<a4> Returns; SIGL{30} 
3db6:Say; "?R"<16c4> Trace; "C"<75c> BifqCONDITION1 @COND{850} 
3dc0:"D"<764> BifqCONDITION1 @DESC{858} SIGL{30} BifSOURCELINE1 
3dca:Parse(2) (PosRest) @LABEL{860} @.{10} (ParseEnd) "Line"<16dc> 
3dd4:SIGL{30} Cat ":"<afc> Abut COND{850} Cat "condition raised:"<16e4> 
3ddf:Cat RC{28} BifERRORTEXT1 Cat "."<4d4> Abut Say; DESC{858} 
3deb:Say; SIGL{30} BifSOURCELINE1 Say; Exit; '1'<ec> BifqARG1 
3df6:@COND{850} '2'<2ac> BifqARG1 @ERRORNUMBER{868} '3'<2c4> 
3e00:BifqARG1 "1"<e4> AssignDots INSERT.{870}; '4'<2fc> BifqARG1 
3e0b:"2"<2a4> AssignDots INSERT.{870}; '5'<6a4> BifqARG1 "3"<2bc> 
3e16:AssignDots INSERT.{870}; '6'<69c> BifqARG1 "4"<2f4> AssignDots 
3e20:INSERT.{870}; ERRORNUMBER{868} Dots(0) !ERRORTEXT.{4e8} 
3e28:@TEXT{880} AssignConst ""<ac> EXPANDED{6b8}; '1'<ec> Number 
3e32:ControlVar I{210}[3e82]; TEXT{880} Parse(0) "<"<16f4> (Pattern) 
3e3e:@BEGIN{888} ">"<16fc> (Pattern) @INSERT{890} '1'<ec> (PosPlus) 
3e48:(PosRest) @TEXT{880} (ParseEnd) INSERT{890} ""<ac> Ceq[3e54] 
3e53:Leave; I{210} Dots(0) INSERT.{870} Length '50'<a34> Gt[3e6f] 
3e60:I{210} Dots(0) INSERT.{870} '50'<a34> BifqLEFT2 @T{70} Jump[3e77] 
3e6f:I{210} Dots(0) INSERT.{870} @T{70} EXPANDED{6b8} BEGIN{888} 
3e7b:Abut T{70} Abut @EXPANDED{6b8} IterCV; EXPANDED{6b8} BEGIN{888} 
3e86:Abut @EXPANDED{6b8} "$SYN$"<1704> ERRORNUMBER{868} Abut 
3e8e:EXPANDED{6b8} Cat Exit; Exit;
