#    ??
# Borland C++ IDE generated makefile
# Generated 12/18/2011 at 11:35:06 
#
.AUTODEPEND


#
# Borland C++ tools
#
IMPLIB  = Implib
BCC32   = Bcc32 +BccW32.cfg 
BCC32I  = Bcc32i +BccW32.cfg 
TLINK32 = TLink32
ILINK32 = Ilink32
TLIB    = TLib
BRC32   = Brc32
TASM32  = Tasm32
#
# IDE macros
#


#
# Options
#
IDE_LinkFLAGS32 =  -LC:\BC5\LIB
CompLocalOptsAtC32_CcbCRXbBIT32xbmsgcdexe =  -WC
LinkerLocalOptsAtC32_CcbCRXbBIT32xbmsgcdexe =  -Tpe -ap -c
ResLocalOptsAtC32_CcbCRXbBIT32xbmsgcdexe = 
BLocalOptsAtC32_CcbCRXbBIT32xbmsgcdexe = 
CompOptsAt_CcbCRXbBIT32xbmsgcdexe = $(CompLocalOptsAtC32_CcbCRXbBIT32xbmsgcdexe)
CompInheritOptsAt_CcbCRXbBIT32xbmsgcdexe = -IC:\BC5\INCLUDE;C:\CRX\BIT32; -D_RTLDLL;_BIDSDLL;
LinkerInheritOptsAt_CcbCRXbBIT32xbmsgcdexe = -x
LinkerOptsAt_CcbCRXbBIT32xbmsgcdexe = $(LinkerLocalOptsAtC32_CcbCRXbBIT32xbmsgcdexe)
ResOptsAt_CcbCRXbBIT32xbmsgcdexe = $(ResLocalOptsAtC32_CcbCRXbBIT32xbmsgcdexe)
BOptsAt_CcbCRXbBIT32xbmsgcdexe = $(BLocalOptsAtC32_CcbCRXbBIT32xbmsgcdexe)
#
# The following section is generated by duplicate target C:\CRX\BIT32;\msgc.exe.
#
CompLocalOptsAtC32_CcbCRXbBIT32xbmsgcdexe =  -WC
LinkerLocalOptsAtC32_CcbCRXbBIT32xbmsgcdexe =  -Tpe -ap -c
ResLocalOptsAtC32_CcbCRXbBIT32xbmsgcdexe = 
BLocalOptsAtC32_CcbCRXbBIT32xbmsgcdexe = 
CompOptsAt_CcbCRXbBIT32xbmsgcdexe = $(CompLocalOptsAtC32_CcbCRXbBIT32xbmsgcdexe)
CompInheritOptsAt_CcbCRXbBIT32xbmsgcdexe = -IC:\BC5\INCLUDE;C:\CRX\BIT32; -D_RTLDLL;_BIDSDLL;
LinkerInheritOptsAt_CcbCRXbBIT32xbmsgcdexe = -x
LinkerOptsAt_CcbCRXbBIT32xbmsgcdexe = $(LinkerLocalOptsAtC32_CcbCRXbBIT32xbmsgcdexe)
ResOptsAt_CcbCRXbBIT32xbmsgcdexe = $(ResLocalOptsAtC32_CcbCRXbBIT32xbmsgcdexe)
BOptsAt_CcbCRXbBIT32xbmsgcdexe = $(BLocalOptsAtC32_CcbCRXbBIT32xbmsgcdexe)
#
## The above section is generated by duplicate target C:\CRX\BIT32;\msgc.exe.
##
#
#

#
# Dependency List
#
Dep_msgc = \
   C:\CRX\BIT32;\msgc.exe\
   C:\CRX\BIT32;\msgc.exe

msgc : BccW32.cfg $(Dep_msgc)
  echo MakeNode

Dep_CcbCRXbBIT32xbmsgcdexe = \
   C:\CRX\BIT32;\msgc.obj\
   msgc.def\
   C:\CRX\BIT32;\msgc.res\
   C:\CRX\BIT32\msgc.exe

C:\CRX\BIT32;\msgc.exe : $(Dep_CcbCRXbBIT32xbmsgcdexe)
  $(ILINK32) @&&|
 /v $(IDE_LinkFLAGS32) $(LinkerOptsAt_CcbCRXbBIT32xbmsgcdexe) $(LinkerInheritOptsAt_CcbCRXbBIT32xbmsgcdexe) +
C:\BC5\LIB\c0x32.obj+
C:\CRX\BIT32;\msgc.obj
$<,$*
C:\BC5\LIB\bidsfi.lib+
C:\BC5\LIB\import32.lib+
C:\BC5\LIB\cw32i.lib
msgc.def
C:\CRX\BIT32;\msgc.res

|
C:\CRX\BIT32;\msgc.obj :  msgc.cpp
  $(BCC32) -c @&&|
 $(CompOptsAt_CcbCRXbBIT32xbmsgcdexe) $(CompInheritOptsAt_CcbCRXbBIT32xbmsgcdexe) -o$@ msgc.cpp
|

C:\CRX\BIT32;\msgc.res :  msgc.rc
  $(BRC) -R @&&|
 $(IDE_ResFLAGS) $(ROptsAt_CcbCRXbBIT32xbmsgcdexe) $(CompInheritOptsAt_CcbCRXbBIT32xbmsgcdexe)  -FO$@ msgc.rc
|
#
## The following section is generated by duplicate target C:\CRX\BIT32;\msgc.exe.
##
#Dep_CcbCRXbBIT32xbmsgcdexe = \
#   C:\CRX\BIT32;\msgc.obj\
#   msgc.def\
#   C:\CRX\BIT32;\msgc.res\
#   C:\CRX\BIT32\msgc.exe
#
#C:\CRX\BIT32;\msgc.exe : $(Dep_CcbCRXbBIT32xbmsgcdexe)
#  $(ILINK32) @&&|
# /v $(IDE_LinkFLAGS32) $(LinkerOptsAt_CcbCRXbBIT32xbmsgcdexe) $(LinkerInheritOptsAt_CcbCRXbBIT32xbmsgcdexe) +
#C:\BC5\LIB\c0x32.obj+
#C:\CRX\BIT32;\msgc.obj
#$<,$*
#C:\BC5\LIB\bidsfi.lib+
#C:\BC5\LIB\import32.lib+
#C:\BC5\LIB\cw32i.lib
#msgc.def
#C:\CRX\BIT32;\msgc.res
#
#|
##
## The above section is generated by duplicate target C:\CRX\BIT32;\msgc.exe.
##
#
#
#
## The following section is generated by duplicate target C:\CRX\BIT32;\msgc.obj.
##
#C:\CRX\BIT32;\msgc.obj :  msgc.cpp
#  $(BCC32) -c @&&|
# $(CompOptsAt_CcbCRXbBIT32xbmsgcdexe) $(CompInheritOptsAt_CcbCRXbBIT32xbmsgcdexe) -o$@ msgc.cpp
#|
#
##
## The above section is generated by duplicate target C:\CRX\BIT32;\msgc.obj.
##
#
#
#
## The following section is generated by duplicate target C:\CRX\BIT32;\msgc.res.
##
#C:\CRX\BIT32;\msgc.res :  msgc.rc
#  $(BRC) -R @&&|
# $(IDE_ResFLAGS) $(ROptsAt_CcbCRXbBIT32xbmsgcdexe) $(CompInheritOptsAt_CcbCRXbBIT32xbmsgcdexe)  -FO$@ msgc.rc
#|
##
## The above section is generated by duplicate target C:\CRX\BIT32;\msgc.res.
##
#
#
# Compiler configuration file
BccW32.cfg : 
   Copy &&|
-w
-R
-v
-WM-
-vi
-H
-H=msgc.csm
| $@


